# Generated by Django 5.1.7 on 2026-09-22 10:25

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tables", "0249_merge_webhook_path_scoping_migrations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Organization",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("is_active", models.BooleanField(default=True)),
                        ("is_default", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "db_table": "rbac_organization",
                        "constraints": [
                            models.UniqueConstraint(
                                django.db.models.functions.text.Lower("name"),
                                name="rbac_organization_name_ci_uniq",
                            ),
                            models.UniqueConstraint(
                                condition=models.Q(("is_default", True)),
                                fields=("is_default",),
                                name="rbac_organization_single_default",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="PasswordResetToken",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("token_hash", models.CharField(max_length=64, unique=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="password_reset_tokens",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "rbac_password_reset_token",
                    },
                ),
                migrations.CreateModel(
                    name="Role",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("is_built_in", models.BooleanField(default=False)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "org",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="roles",
                                to="rbac.organization",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "rbac_role",
                    },
                ),
                migrations.CreateModel(
                    name="OrganizationUser",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("joined_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "org",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="members",
                                to="rbac.organization",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="organization_memberships",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "role",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="organization_users",
                                to="rbac.role",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "rbac_organization_user",
                    },
                ),
                migrations.CreateModel(
                    name="RolePermission",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "resource_type",
                            models.CharField(
                                choices=[
                                    ("organizations", "Organizations"),
                                    ("roles", "Roles"),
                                    ("memberships", "Members"),
                                    ("api_keys", "API Keys"),
                                    ("flows", "Flows"),
                                    ("agents", "Agents"),
                                    ("tools", "Tools"),
                                    ("knowledge_sources", "Knowledge Sources"),
                                    ("files", "Files"),
                                    ("projects", "Projects"),
                                    ("llm_configs", "LLM Configs"),
                                    ("secrets", "Secrets"),
                                    ("voice", "Voice"),
                                    ("surfaces", "Surfaces"),
                                    ("webhooks", "Webhooks"),
                                ],
                                max_length=32,
                            ),
                        ),
                        ("permissions", models.IntegerField(default=0)),
                        (
                            "role",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="permissions_set",
                                to="rbac.role",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "rbac_role_permission",
                    },
                ),
                migrations.CreateModel(
                    name="ApiKey",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        (
                            "key_type",
                            models.CharField(
                                choices=[("system", "System"), ("user", "User")],
                                default="user",
                                max_length=8,
                            ),
                        ),
                        ("prefix", models.CharField(db_index=True, max_length=12)),
                        ("key_hash", models.CharField(max_length=64, unique=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("expires_at", models.DateTimeField(blank=True, null=True)),
                        ("revoked_at", models.DateTimeField(blank=True, null=True)),
                        ("last_used_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "created_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="api_keys",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tables_apikey",
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(
                                    models.Q(
                                        ("created_by__isnull", False),
                                        ("key_type", "user"),
                                    ),
                                    models.Q(
                                        ("created_by__isnull", True),
                                        ("expires_at__isnull", True),
                                        ("key_type", "system"),
                                    ),
                                    _connector="OR",
                                ),
                                name="api_key_type_invariants",
                            )
                        ],
                    },
                ),
                migrations.AddConstraint(
                    model_name="role",
                    constraint=models.UniqueConstraint(
                        models.F("org"),
                        django.db.models.functions.text.Lower("name"),
                        name="rbac_role_org_name_ci_uniq",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="organizationuser",
                    constraint=models.UniqueConstraint(
                        fields=("user", "org"),
                        name="rbac_organization_user_user_org_uniq",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="rolepermission",
                    unique_together={("role", "resource_type")},
                ),
            ],
            database_operations=[],
        ),
    ]
