# Generated by Django 5.1.7 on 2026-09-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="apikey",
            table="rbac_apikey",
        ),
    ]
