# Generated by Django 5.1.14 on 2026-10-06 15:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_organization_config(apps, schema_editor):
    """Give every existing Organization its config row.

    The model default only applies to rows created from now on; code reads
    `org.config` unconditionally, so organizations that predate this table
    need a row too.
    """
    Organization = apps.get_model("rbac", "Organization")
    OrganizationConfig = apps.get_model("rbac", "OrganizationConfig")
    OrganizationConfig.objects.bulk_create(
        [
            OrganizationConfig(org=organization, audit_retention_days=0)
            for organization in Organization.objects.filter(config__isnull=True)
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_key_value_tables_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationConfig',
            fields=[
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='rbac.organization')),
                ('audit_retention_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'rbac_organization_config',
            },
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='resource_type',
            field=models.CharField(choices=[('organizations', 'Organizations'), ('roles', 'Roles'), ('memberships', 'Members'), ('api_keys', 'API Keys'), ('flows', 'Flows'), ('agents', 'Agents'), ('tools', 'Tools'), ('knowledge_sources', 'Knowledge Sources'), ('files', 'Files'), ('projects', 'Projects'), ('llm_configs', 'LLM Configs'), ('secrets', 'Secrets'), ('audit', 'Audit'), ('voice', 'Voice'), ('surfaces', 'Surfaces'), ('webhooks', 'Webhooks'), ('key_value_tables', 'Key-Value Tables')], max_length=32),
        ),
        # Reverse is a noop: reversing CreateModel drops the table and its rows.
        migrations.RunPython(backfill_organization_config, migrations.RunPython.noop),
    ]
