# Generated by Django 5.1.14 on 2026-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_key_value_tables_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='resource_type',
            field=models.CharField(choices=[('organizations', 'Organizations'), ('roles', 'Roles'), ('memberships', 'Members'), ('api_keys', 'API Keys'), ('flows', 'Flows'), ('agents', 'Agents'), ('tools', 'Tools'), ('knowledge_sources', 'Knowledge Sources'), ('files', 'Files'), ('projects', 'Projects'), ('llm_configs', 'LLM Configs'), ('secrets', 'Secrets'), ('voice', 'Voice'), ('surfaces', 'Surfaces'), ('webhooks', 'Webhooks'), ('key_value_tables', 'Key-Value Tables'), ('plugins', 'Plugins')], max_length=32),
        ),
    ]
