# Generated by Django 5.1.14 on 2026-10-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_organization_config'),
        ('rbac', '0005_release_authorship_of_non_members'),
    ]

    operations = [
    ]
