import { NodeType } from './node-type';

export const NODE_ICONS: Record<NodeType, string> = {
    [NodeType.AGENT]: 'robot',
    [NodeType.TASK]: 'list-check',
    [NodeType.TOOL]: 'tools',
    [NodeType.LLM]: 'brain',
    [NodeType.PROJECT]: 'folder',
    [NodeType.PYTHON]: 'python',
    [NodeType.EDGE]: 'route-alt-left',
    [NodeType.START]: 'player-play-filled',
    [NodeType.TABLE]: 'table',
    [NodeType.NOTE]: 'note',
    [NodeType.FILE_EXTRACTOR]: 'file',
    [NodeType.WEBHOOK_TRIGGER]: 'world',
    [NodeType.TELEGRAM_TRIGGER]: 'telegram',
    [NodeType.END]: 'square-rounded',
    [NodeType.SUBGRAPH]: 'hierarchy-2',
    [NodeType.AUDIO_TO_TEXT]: 'music',
    [NodeType.CODE_AGENT]: 'terminal-2',
};

export const NODE_COLORS: Record<NodeType, string> = {
    [NodeType.AGENT]: '#8e5cd9',
    [NodeType.TASK]: '#30a46c',
    [NodeType.TOOL]: '#9f6a00',
    [NodeType.LLM]: '#e0575b',
    [NodeType.PROJECT]: '#5672cd',
    [NodeType.PYTHON]: '#ffcf3f',
    [NodeType.EDGE]: '#8e5cd9',
    [NodeType.START]: '#d3d3d3',
    [NodeType.TABLE]: '#00aaff',
    [NodeType.NOTE]: '#ffffd1',
    [NodeType.FILE_EXTRACTOR]: '#2196F3',
    [NodeType.WEBHOOK_TRIGGER]: '#21f367ff',
    [NodeType.TELEGRAM_TRIGGER]: '#229ED9',
    [NodeType.END]: '#d3d3d3',
    [NodeType.SUBGRAPH]: '#00bfa5',
    [NodeType.AUDIO_TO_TEXT]: '#ff7be9ff',
    [NodeType.CODE_AGENT]: '#00e676',
};
