# Generated by Django 5.1.14 on 2026-10-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0259_alter_secret_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryStorageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=255, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('python_code_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncoderesult')),
                ('realtime_agent_chat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.realtimeagentchat')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.session')),
            ],
            options={
                'verbose_name': 'Temporary Storage Account',
                'verbose_name_plural': 'Temporary Storage Accounts',
                'db_table': 'storage_credentials_temp_account',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('session__isnull', False), ('python_code_result__isnull', True), ('realtime_agent_chat__isnull', True)), models.Q(('session__isnull', True), ('python_code_result__isnull', False), ('realtime_agent_chat__isnull', True)), models.Q(('session__isnull', True), ('python_code_result__isnull', True), ('realtime_agent_chat__isnull', False)), _connector='OR'), name='exactly_one_fk_is_not_null')],
            },
        ),
    ]
