"""
Django settings for django_app project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from dotenv import find_dotenv, load_dotenv
from loguru import logger

from tables.services.rbac.first_setup_mode import FirstSetupMode

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes", "on")


def _require_env(name: str) -> str:
    """Return the environment variable's stripped value, refusing to start when it is missing or blank."""
    value = (os.getenv(name) or "").strip()
    if not value:
        raise ImproperlyConfigured(
            f"{name} is not set. EpicStaff ships no default signing key: generate a "
            f"random value (e.g. `openssl rand -base64 48`) and pass it to the "
            f"django_app container. Rotating SECRET_KEY makes every stored Secret "
            f"undecryptable, so generate it once and keep it."
        )
    return value


SECRET_KEY = _require_env("SECRET_KEY")

ALLOWED_HOSTS = [
    "*",  # host.strip() for host in os.getenv("ALLOWED_HOSTS", "0.0.0.0, 127.0.0.1").split(",")
]


# Logging

_VALID_LOG_LEVELS = {"CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG", "NOTSET"}


def _resolve_log_level() -> str:
    """Resolve the stdlib root log level from DJANGO_LOG_LEVEL, falling back to WARNING on an invalid/missing value."""
    raw_level = os.getenv("DJANGO_LOG_LEVEL", "WARNING").strip().upper()
    if raw_level not in _VALID_LOG_LEVELS:
        logger.warning(
            "Ignoring invalid DJANGO_LOG_LEVEL={!r}; falling back to WARNING.",
            raw_level,
        )
        return "WARNING"
    return raw_level


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "loguru": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
        },
    },
    "root": {
        "handlers": ["loguru"],
        "level": _resolve_log_level(),
    },
    "loggers": {
        "litellm": {
            "handlers": ["loguru"],
            "level": "WARNING",
            "propagate": False,
        },
        "LiteLLM": {
            "handlers": ["loguru"],
            "level": "WARNING",
            "propagate": False,
        },
        "LiteLLM Router": {
            "handlers": ["loguru"],
            "level": "WARNING",
            "propagate": False,
        },
        "LiteLLM Proxy": {
            "handlers": ["loguru"],
            "level": "WARNING",
            "propagate": False,
        },
        "boto3": {
            "handlers": ["loguru"],
            "level": "WARNING",
            "propagate": False,
        },
        "botocore": {
            "handlers": ["loguru"],
            "level": "WARNING",
            "propagate": False,
        },
        "s3transfer": {
            "handlers": ["loguru"],
            "level": "WARNING",
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["loguru"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    "health_check",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tables",
    "agents",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "django_redis",
    "channels",
    "channels_redis",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "tables.services.rbac.authentication.JwtAuthentication",
        "tables.services.rbac.authentication.ApiKeyAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "login": os.getenv("LOGIN_THROTTLE_RATE", "5/min"),
        "password_reset_request": os.getenv(
            "PASSWORD_RESET_REQUEST_THROTTLE_RATE", "5/hour"
        ),
        "notify_email": os.getenv("NOTIFY_EMAIL_THROTTLE_RATE", "10/hour"),
    },
}

FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:4200").rstrip("/")

# The docker-compose stack fronts the frontend with nginx on DOMAIN_NAME
# (src/docker-compose.yaml's epicstaff-nginx service), which is a different
# origin than FRONTEND_BASE_URL's dev-server default — trust both by default.
_domain_name = os.getenv("DOMAIN_NAME", "localhost").strip().strip('"')
_default_cors_origins = ",".join(
    [FRONTEND_BASE_URL, f"http://{_domain_name}", f"https://{_domain_name}"]
)

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CORS_ALLOWED_ORIGINS", _default_cors_origins).split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (*default_headers, "x-organization-id")

JWT_SECRET = os.getenv("JWT_SECRET", SECRET_KEY)

SIMPLE_JWT = {
    "SIGNING_KEY": JWT_SECRET,
    "ALGORITHM": "HS256",
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_MINUTES", "15"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

ROOT_URLCONF = "django_app.urls"
ASGI_APPLICATION = "django_app.asgi.application"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "crew"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "admin"),
        "HOST": os.environ.get("DB_HOST_NAME", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "tables.services.rbac.utils.printable_ascii_password_validator.PrintableAsciiPasswordValidator",
    },
]

TELEGRAM_TRIGGER_FIELDS_PATH = (
    BASE_DIR / "tables" / "utils" / "data" / "telegram_fields.json"
)

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIMEZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
            "PASSWORD": REDIS_PASSWORD,
        },
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "host": REDIS_HOST,
                    "port": REDIS_PORT,
                    "password": REDIS_PASSWORD,
                }
            ],
        },
    },
}

GRAPH_WS_TICKET_TTL_SECONDS = 30

MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", os.path.join(BASE_DIR, "media"))
MEDIA_URL = "/media/"

AUTH_USER_MODEL = "tables.User"

PASSWORD_RESET_TOKEN_TTL = int(os.getenv("PASSWORD_RESET_TOKEN_TTL", "900"))

# Email / password-recovery delivery.
#
# Two independent knobs:
#   * `EMAIL_HOST`         — "is SMTP delivery configured at all?" If set,
#                            Django uses the SMTP backend; if blank, it
#                            falls back to the console backend so the
#                            reset link is still observable in stdout.
#   * `EMAIL_HOST_USER` +  — "should Django authenticate?" Both blank =
#     `EMAIL_HOST_PASSWORD`  unauthenticated relay (mailpit, local Postfix,
#                            some corporate MTAs). Both set = plain SMTP
#                            AUTH against the configured host.
#
# Setting a user/password against a server that does NOT implement SMTP
# AUTH (mailpit is the common one) will raise `SMTPNotSupportedError` —
# leave them blank for those servers.
#
# Business-layer code that needs to branch on "should we advertise email
# delivery to the end user?" must ask `SmtpConfigService.is_configured()`
# rather than inspecting `EMAIL_BACKEND`.
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes", "on")
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in (
    "true",
    "1",
    "yes",
    "on",
)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@epicstaff.local")

if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

FRONTEND_PASSWORD_RESET_PATH = os.getenv(
    "FRONTEND_PASSWORD_RESET_PATH", "/reset-password"
)

SSE_TICKET_TTL_SECONDS = 30

DEFAULT_ORGANIZATION_NAME = os.getenv("DEFAULT_ORGANIZATION_NAME") or "Organization"

# Which superadmin-creation path is live. See FirstSetupMode. Defaults to
# cli_only so an internet-exposed deployment fails closed.
FIRST_SETUP_MODE = FirstSetupMode.validate(
    (os.getenv("FIRST_SETUP_MODE") or FirstSetupMode.CLI_ONLY).strip().lower()
)

PASSWORD_CHANGE_TICKET_TTL_SECONDS = int(
    os.getenv("PASSWORD_CHANGE_TICKET_TTL_SECONDS", "300")
)
AVATAR_MAX_BYTES = int(os.getenv("AVATAR_MAX_BYTES", str(5 * 1024 * 1024)))
AVATAR_ALLOWED_FORMATS = [
    fmt.strip()
    for fmt in os.getenv("AVATAR_ALLOWED_FORMATS", "JPEG,PNG").split(",")
    if fmt.strip()
]

# Object storage
STORAGE_ENDPOINT = os.getenv("STORAGE_ENDPOINT", "")
STORAGE_ACCESS_KEY = os.getenv("STORAGE_ACCESS_KEY", "")
STORAGE_SECRET_KEY = os.getenv("STORAGE_SECRET_KEY", "")
STORAGE_BUCKET_NAME = os.getenv("STORAGE_BUCKET_NAME", "epicstaff")

MAX_TOTAL_FILE_SIZE = 10 * 1024 * 1024  # 10MB

REDIS_TUNNEL_CONFIG_CHANNEL = os.getenv(
    "REDIS_TUNNEL_CONFIG_CHANNEL", "REDIS_TUNNEL_CONFIG_CHANNEL"
)
TUNNEL_URLS_HASH_KEY = os.getenv("TUNNEL_URLS_HASH_KEY", "tunnel_urls")
KNOWLEDGE_DOCUMENT_CHUNK_CHANNEL = os.getenv(
    "KNOWLEDGE_DOCUMENT_CHUNK_CHANNEL", "knowledge:chunk"
)
KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE = os.getenv(
    "KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE", "knowledge:chunk:response"
)
KNOWLEDGE_INDEXING_CHANNEL = os.getenv(
    "KNOWLEDGE_INDEXING_CHANNEL", "knowledge:indexing"
)
STOP_SESSION_CHANNEL = os.getenv("STOP_SESSION_CHANNEL", "sessions:stop")

WEBHOOK_USE_TUNNEL = os.getenv("WEBHOOK_USE_TUNNEL", "False") in ["True", "true", 1]

if WEBHOOK_USE_TUNNEL:
    WEBHOOK_TUNNEL = os.getenv("WEBHOOK_TUNNEL", None)
else:
    WEBHOOK_TUNNEL = None

REQUEST_WEBHOOK_UPDATE_CHANNEL = os.getenv(
    "REQUEST_WEBHOOK_UPDATE_CHANNEL", "REQUEST_WEBHOOK_UPDATE_CHANNEL"
)
SESSION_STATUS_CHANNEL = os.environ.get(
    "SESSION_STATUS_CHANNEL", "sessions:session_status"
)
CODE_RESULT_CHANNEL = os.environ.get("CODE_RESULT_CHANNEL", "code_results")
GRAPH_MESSAGES_CHANNEL = os.environ.get("GRAPH_MESSAGES_CHANNEL", "graph:messages")
GRAPH_MESSAGE_UPDATE_CHANNEL = os.environ.get(
    "GRAPH_MESSAGE_UPDATE_CHANNEL", "graph:message:update"
)
WEBHOOK_MESSAGE_CHANNEL = os.environ.get("WEBHOOK_MESSAGE_CHANNEL", "webhooks")
STORAGE_MUTATION_CHANNEL = os.environ.get(
    "STORAGE_MUTATION_CHANNEL", "storage_mutations"
)
TELEGRAM_TRIGGER_PREFIX = "telegram-trigger/"
SCHEDULE_CHANNEL = os.environ.get("SCHEDULE_CHANNEL", "schedule_channel")


WEBHOOK_HOST_NAME = os.getenv("WEBHOOK_HOST_NAME", "localhost")
WEBHOOK_PORT = int(os.getenv("WEBHOOK_PORT", 8009))

SPECTACULAR_SETTINGS = {
    "TITLE": "EpicStaff API",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "django_app.spectacular_hooks.assign_tags_postprocessing_hook",
        "django_app.spectacular_hooks.add_org_header_postprocessing_hook",
    ],
}
