# Generated by Django 5.1.3 on 2026-07-13 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tables", "0190_merge_20260624_1254"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentInlineSurface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form text appended to the agent prompt when this surface is active. Empty string means no extra instructions.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentInlineSurfaceGraphBasicSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The basic search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "k",
                    models.IntegerField(
                        default=10,
                        help_text="The number of text units to include in search context.",
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentInlineSurfaceGraphLocalSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The local search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "text_unit_prop",
                    models.FloatField(
                        default=0.5, help_text="The text unit proportion."
                    ),
                ),
                (
                    "community_prop",
                    models.FloatField(
                        default=0.15, help_text="The community proportion."
                    ),
                ),
                (
                    "conversation_history_max_turns",
                    models.IntegerField(
                        default=5, help_text="The conversation history maximum turns."
                    ),
                ),
                (
                    "top_k_entities",
                    models.IntegerField(
                        default=10, help_text="The top k mapped entities."
                    ),
                ),
                (
                    "top_k_relationships",
                    models.IntegerField(
                        default=10, help_text="The top k mapped relations."
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentInlineSurfaceKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentInlineSurfaceMcpTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        help_text="Whether this tool is explicitly allowed or denied for this surface.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentInlineSurfaceNaiveSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="Integer between 0 and 1000 for knowledge",
                    ),
                ),
                (
                    "similarity_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.2,
                        help_text="Float between 0.00 and 1.00 for knowledge",
                        max_digits=3,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentInlineSurfacePythonTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        help_text="Whether this tool is explicitly allowed or denied for this surface.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentInlineSurfaceStorageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_list",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may list (enumerate) this file/folder. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_view",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may read/view the content of this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_edit",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may modify or overwrite this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_delete",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may delete this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DefaultAgentDefinitionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_iter",
                    models.IntegerField(
                        default=None,
                        help_text="Default max reasoning iterations for an AgentDefinition when its own value is null.",
                        null=True,
                    ),
                ),
                (
                    "max_rpm",
                    models.IntegerField(
                        default=None,
                        help_text="Default max LLM requests per minute when AgentDefinition.max_rpm is null.",
                        null=True,
                    ),
                ),
                (
                    "max_execution_time",
                    models.IntegerField(
                        default=None,
                        help_text="Default per-run wall-clock budget in seconds when AgentDefinition.max_execution_time is null.",
                        null=True,
                    ),
                ),
                (
                    "cache",
                    models.BooleanField(
                        default=None,
                        help_text="Default for whether tool-result caching is enabled when AgentDefinition.cache is null.",
                        null=True,
                    ),
                ),
                (
                    "max_retry_limit",
                    models.IntegerField(
                        default=None,
                        help_text="Default max retries on transient failures when AgentDefinition.max_retry_limit is null.",
                        null=True,
                    ),
                ),
                (
                    "default_temperature",
                    models.FloatField(
                        default=None,
                        help_text="Default sampling temperature applied when neither the AgentDefinition nor its LLMConfig specify one.",
                        null=True,
                    ),
                ),
                (
                    "max_tool_calls",
                    models.IntegerField(
                        default=15,
                        help_text="Default max tool calls executed per loop iteration when AgentDefinition.max_tool_calls is null. Null = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "tool_timeout",
                    models.IntegerField(
                        default=300,
                        help_text="Default per-tool-call timeout in seconds when AgentDefinition.tool_timeout is null. Null = no timeout.",
                        null=True,
                    ),
                ),
                (
                    "max_consecutive_failures",
                    models.IntegerField(
                        default=3,
                        help_text="Default consecutive tool-failure limit when AgentDefinition.max_consecutive_failures is null. Null = disabled.",
                        null=True,
                    ),
                ),
                (
                    "schema_max_retries",
                    models.IntegerField(
                        default=None,
                        help_text="Default max schema-enforcement retries when AgentDefinition.schema_max_retries is null.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InlineSurface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form text appended to the agent prompt when this surface is active. Empty string means no extra instructions.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InlineSurfaceGraphBasicSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The basic search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "k",
                    models.IntegerField(
                        default=10,
                        help_text="The number of text units to include in search context.",
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InlineSurfaceGraphLocalSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The local search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "text_unit_prop",
                    models.FloatField(
                        default=0.5, help_text="The text unit proportion."
                    ),
                ),
                (
                    "community_prop",
                    models.FloatField(
                        default=0.15, help_text="The community proportion."
                    ),
                ),
                (
                    "conversation_history_max_turns",
                    models.IntegerField(
                        default=5, help_text="The conversation history maximum turns."
                    ),
                ),
                (
                    "top_k_entities",
                    models.IntegerField(
                        default=10, help_text="The top k mapped entities."
                    ),
                ),
                (
                    "top_k_relationships",
                    models.IntegerField(
                        default=10, help_text="The top k mapped relations."
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InlineSurfaceKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InlineSurfaceMcpTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        help_text="Whether this tool is explicitly allowed or denied for this surface.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InlineSurfaceNaiveSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="Integer between 0 and 1000 for knowledge",
                    ),
                ),
                (
                    "similarity_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.2,
                        help_text="Float between 0.00 and 1.00 for knowledge",
                        max_digits=3,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InlineSurfacePythonTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        help_text="Whether this tool is explicitly allowed or denied for this surface.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InlineSurfaceStorageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_list",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may list (enumerate) this file/folder. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_view",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may read/view the content of this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_edit",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may modify or overwrite this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_delete",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may delete this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Surface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Stable identifier unique within the organization. Used as the user-facing name for this surface.",
                        max_length=255,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form text appended to the agent prompt when this surface is active. Empty string means no extra instructions.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurfaceGraphBasicSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The basic search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "k",
                    models.IntegerField(
                        default=10,
                        help_text="The number of text units to include in search context.",
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurfaceGraphLocalSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The local search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "text_unit_prop",
                    models.FloatField(
                        default=0.5, help_text="The text unit proportion."
                    ),
                ),
                (
                    "community_prop",
                    models.FloatField(
                        default=0.15, help_text="The community proportion."
                    ),
                ),
                (
                    "conversation_history_max_turns",
                    models.IntegerField(
                        default=5, help_text="The conversation history maximum turns."
                    ),
                ),
                (
                    "top_k_entities",
                    models.IntegerField(
                        default=10, help_text="The top k mapped entities."
                    ),
                ),
                (
                    "top_k_relationships",
                    models.IntegerField(
                        default=10, help_text="The top k mapped relations."
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurfaceKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurfaceMcpTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        help_text="Whether this tool is explicitly allowed or denied for this surface.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurfaceNaiveSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=3,
                        help_text="Integer between 0 and 1000 for knowledge",
                    ),
                ),
                (
                    "similarity_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.2,
                        help_text="Float between 0.00 and 1.00 for knowledge",
                        max_digits=3,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SurfacePythonTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        help_text="Whether this tool is explicitly allowed or denied for this surface.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurfaceStorageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_list",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may list (enumerate) this file/folder. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_view",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may read/view the content of this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_edit",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may modify or overwrite this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
                (
                    "can_delete",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("unset", "Unset"),
                            ("deny", "Deny"),
                        ],
                        default="unset",
                        help_text="Whether the agent may delete this file. 'deny' explicitly forbids it.",
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Stable identifier (slug-like) unique within an organization. Used to reference this agent from flows, code, and the UI.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of this agent — its purpose, persona, or capabilities. E.g. 'Senior Researcher focused on market analysis'.",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form prompt for the agent. Put behavior, goals, tone, and constraints here.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form key-value store for arbitrary client/UI data. Not used by execution.",
                    ),
                ),
                (
                    "max_iter",
                    models.IntegerField(
                        default=None,
                        help_text="Max reasoning iterations per task before forcing a final answer. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "max_rpm",
                    models.IntegerField(
                        default=None,
                        help_text="LLM request rate cap (requests per minute). Null falls back to DefaultAgentDefinitionConfig; no cap if both are null.",
                        null=True,
                    ),
                ),
                (
                    "max_execution_time",
                    models.IntegerField(
                        default=None,
                        help_text="Wall-clock budget in seconds for a single agent run. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "cache",
                    models.BooleanField(
                        default=None,
                        help_text="Enable tool-result caching for this agent. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "max_retry_limit",
                    models.IntegerField(
                        default=None,
                        help_text="Max retries on transient LLM/tool failures. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "default_temperature",
                    models.FloatField(
                        default=None,
                        help_text="Sampling temperature applied when the LLMConfig leaves it unset. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "max_tool_calls",
                    models.IntegerField(
                        default=None,
                        help_text="Max tool calls executed per loop iteration. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "tool_timeout",
                    models.IntegerField(
                        default=None,
                        help_text="Per-tool-call timeout in seconds. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "max_consecutive_failures",
                    models.IntegerField(
                        default=None,
                        help_text="Consecutive failed tool calls before graceful stop. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "schema_max_retries",
                    models.IntegerField(
                        default=None,
                        help_text="Max retries when enforcing structured-output schema validation. Null falls back to DefaultAgentDefinitionConfig.",
                        null=True,
                    ),
                ),
                (
                    "fcm_llm_config",
                    models.ForeignKey(
                        default=None,
                        help_text="Optional dedicated LLM for function/tool-call routing. Falls back to llm_config when null.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fcm_agent_definitions",
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "llm_config",
                    models.ForeignKey(
                        default=None,
                        help_text="Primary LLM used for reasoning and tool selection.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_definitions",
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this agent belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_definitions",
                        to="tables.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentDefaultSurface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("all", "All Places"),
                            ("flow", "Flow"),
                            ("chat", "Chat"),
                        ],
                        help_text="Context where this surface is the default: 'all' for any place, 'flow' for flow execution, 'chat' for chat sessions.",
                        max_length=5,
                    ),
                ),
                (
                    "agent_definition",
                    models.ForeignKey(
                        help_text="Agent definition this default surface assignment belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_surfaces",
                        to="agents.agentdefinition",
                    ),
                ),
            ],
        ),
    ]
