# Generated by Django 5.1.3 on 2026-07-13 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("tables", "0191_agentnode_tasknode_agentnodetask"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinlinesurface",
            name="agent_node",
            field=models.OneToOneField(
                help_text="AgentNode that owns this ad-hoc surface. Deleted with the node.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inline_surface",
                to="tables.agentnode",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfaceknowledge",
            name="agent_inline_surface",
            field=models.ForeignKey(
                help_text="AgentInlineSurface this knowledge collection is attached to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge",
                to="agents.agentinlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphlocalsearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="AgentInlineSurfaceKnowledge entry this GraphRAG local search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_local_search_config",
                to="agents.agentinlinesurfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphbasicsearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="AgentInlineSurfaceKnowledge entry this GraphRAG basic search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_basic_search_config",
                to="agents.agentinlinesurfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacemcptool",
            name="agent_inline_surface",
            field=models.ForeignKey(
                help_text="AgentInlineSurface this entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcp_tools",
                to="agents.agentinlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacemcptool",
            name="mcp_tool",
            field=models.ForeignKey(
                help_text="McpTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.mcptool",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacenaivesearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="AgentInlineSurfaceKnowledge entry this naive search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="naive_search_config",
                to="agents.agentinlinesurfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacepythontool",
            name="agent_inline_surface",
            field=models.ForeignKey(
                help_text="AgentInlineSurface this entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="python_tools",
                to="agents.agentinlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.pythoncodetool",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacestorageitem",
            name="agent_inline_surface",
            field=models.ForeignKey(
                help_text="AgentInlineSurface this storage permission entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_items",
                to="agents.agentinlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacestorageitem",
            name="storage_file",
            field=models.ForeignKey(
                help_text="StorageFile whose access is being configured for this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.storagefile",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="task_node",
            field=models.OneToOneField(
                help_text="TaskNode that owns this ad-hoc surface. Deleted with the node.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inline_surface",
                to="tables.tasknode",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfaceknowledge",
            name="inline_surface",
            field=models.ForeignKey(
                help_text="InlineSurface this knowledge collection is attached to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge",
                to="agents.inlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphlocalsearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="InlineSurfaceKnowledge entry this GraphRAG local search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_local_search_config",
                to="agents.inlinesurfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphbasicsearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="InlineSurfaceKnowledge entry this GraphRAG basic search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_basic_search_config",
                to="agents.inlinesurfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacemcptool",
            name="inline_surface",
            field=models.ForeignKey(
                help_text="InlineSurface this entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcp_tools",
                to="agents.inlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacemcptool",
            name="mcp_tool",
            field=models.ForeignKey(
                help_text="McpTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.mcptool",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacenaivesearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="InlineSurfaceKnowledge entry this naive search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="naive_search_config",
                to="agents.inlinesurfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacepythontool",
            name="inline_surface",
            field=models.ForeignKey(
                help_text="InlineSurface this entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="python_tools",
                to="agents.inlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.pythoncodetool",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacestorageitem",
            name="inline_surface",
            field=models.ForeignKey(
                help_text="InlineSurface this storage permission entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_items",
                to="agents.inlinesurface",
            ),
        ),
        migrations.AddField(
            model_name="inlinesurfacestorageitem",
            name="storage_file",
            field=models.ForeignKey(
                help_text="StorageFile whose access is being configured for this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.storagefile",
            ),
        ),
        migrations.AddField(
            model_name="surface",
            name="organization",
            field=models.ForeignKey(
                help_text="Organization this surface belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surfaces",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="surface",
            name="owner_agent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Agent that owns this surface. Null means shared — any agent or place may use it. Set means agent-specific — only that agent.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_surfaces",
                to="agents.agentdefinition",
            ),
        ),
        migrations.AddField(
            model_name="agentdefinition",
            name="default_surface_list",
            field=models.ManyToManyField(
                blank=True,
                help_text="Surfaces applied to this agent by default, per place (flow/chat/all). Managed via AgentDefaultSurface through table.",
                related_name="default_in_agents",
                through="agents.AgentDefaultSurface",
                to="agents.surface",
            ),
        ),
        migrations.AddField(
            model_name="agentdefaultsurface",
            name="surface",
            field=models.ForeignKey(
                help_text="Surface assigned as the default for this agent in the given place.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for",
                to="agents.surface",
            ),
        ),
        migrations.AddField(
            model_name="surfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddField(
            model_name="surfaceknowledge",
            name="surface",
            field=models.ForeignKey(
                help_text="Surface this knowledge collection is attached to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge",
                to="agents.surface",
            ),
        ),
        migrations.AddField(
            model_name="surfacegraphlocalsearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="SurfaceKnowledge entry this GraphRAG local search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_local_search_config",
                to="agents.surfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="surfacegraphbasicsearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="SurfaceKnowledge entry this GraphRAG basic search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graph_basic_search_config",
                to="agents.surfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="surfacemcptool",
            name="mcp_tool",
            field=models.ForeignKey(
                help_text="McpTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.mcptool",
            ),
        ),
        migrations.AddField(
            model_name="surfacemcptool",
            name="surface",
            field=models.ForeignKey(
                help_text="Surface this entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcp_tools",
                to="agents.surface",
            ),
        ),
        migrations.AddField(
            model_name="surfacenaivesearchconfig",
            name="surface_knowledge",
            field=models.OneToOneField(
                help_text="SurfaceKnowledge entry this naive search configuration applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="naive_search_config",
                to="agents.surfaceknowledge",
            ),
        ),
        migrations.AddField(
            model_name="surfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.pythoncodetool",
            ),
        ),
        migrations.AddField(
            model_name="surfacepythontool",
            name="surface",
            field=models.ForeignKey(
                help_text="Surface this entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="python_tools",
                to="agents.surface",
            ),
        ),
        migrations.AddField(
            model_name="surfacestorageitem",
            name="storage_file",
            field=models.ForeignKey(
                help_text="StorageFile whose access is being configured for this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tables.storagefile",
            ),
        ),
        migrations.AddField(
            model_name="surfacestorageitem",
            name="surface",
            field=models.ForeignKey(
                help_text="Surface this storage permission entry belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_items",
                to="agents.surface",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfaceknowledge",
            constraint=models.UniqueConstraint(
                fields=("agent_inline_surface", "collection"),
                name="uniq_agent_inline_surface_knowledge",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacemcptool",
            constraint=models.UniqueConstraint(
                fields=("agent_inline_surface", "mcp_tool"),
                name="uniq_agent_inline_surface_mcp_tool",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacepythontool",
            constraint=models.UniqueConstraint(
                fields=("agent_inline_surface", "python_tool"),
                name="uniq_agent_inline_surface_python_tool",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacestorageitem",
            constraint=models.UniqueConstraint(
                fields=("agent_inline_surface", "storage_file"),
                name="uniq_agent_inline_surface_storage_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfaceknowledge",
            constraint=models.UniqueConstraint(
                fields=("inline_surface", "collection"),
                name="uniq_inline_surface_knowledge",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacemcptool",
            constraint=models.UniqueConstraint(
                fields=("inline_surface", "mcp_tool"),
                name="uniq_inline_surface_mcp_tool",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacepythontool",
            constraint=models.UniqueConstraint(
                fields=("inline_surface", "python_tool"),
                name="uniq_inline_surface_python_tool",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacestorageitem",
            constraint=models.UniqueConstraint(
                fields=("inline_surface", "storage_file"),
                name="uniq_inline_surface_storage_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="surface",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_surface_org_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentdefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_agent_definition_name_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentdefaultsurface",
            constraint=models.UniqueConstraint(
                fields=("agent_definition", "surface", "place"),
                name="uniq_agent_default_surface",
            ),
        ),
        migrations.AddConstraint(
            model_name="surfaceknowledge",
            constraint=models.UniqueConstraint(
                fields=("surface", "collection"), name="uniq_surface_knowledge"
            ),
        ),
        migrations.AddConstraint(
            model_name="surfacemcptool",
            constraint=models.UniqueConstraint(
                fields=("surface", "mcp_tool"), name="uniq_surface_mcp_tool"
            ),
        ),
        migrations.AddConstraint(
            model_name="surfacepythontool",
            constraint=models.UniqueConstraint(
                fields=("surface", "python_tool"), name="uniq_surface_python_tool"
            ),
        ),
        migrations.AddConstraint(
            model_name="surfacestorageitem",
            constraint=models.UniqueConstraint(
                fields=("surface", "storage_file"), name="uniq_surface_storage_item"
            ),
        ),
    ]
