# Generated by Django 5.1.3 on 2026-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentdefaultsurface",
            name="place",
            field=models.CharField(
                choices=[
                    ("all", "All Places"),
                    ("flow", "Flow"),
                    ("chat", "Chat"),
                    ("realtime", "Realtime"),
                ],
                help_text="Context where this surface is the default: 'all' for any place, 'flow' for flow execution, 'chat' for chat sessions, 'realtime' for voice sessions.",
                max_length=16,
            ),
        ),
    ]
