# Generated by Django 5.1.7 on 2026-08-13 16:01

from django.db import migrations, models


DEFAULT_VALUES_BY_FIELD = {
    "max_iter": 25,
    "max_rpm": 10,
    "max_execution_time": 60,
    "cache": False,
    "max_retry_limit": 3,
    "default_temperature": 0.7,
    "schema_max_retries": 2,
}


def backfill_singleton_defaults(apps, schema_editor):
    DefaultAgentDefinitionConfig = apps.get_model(
        "agents", "DefaultAgentDefinitionConfig"
    )
    config, _ = DefaultAgentDefinitionConfig.objects.get_or_create(pk=1)

    fields_to_update = []
    for field_name, default_value in DEFAULT_VALUES_BY_FIELD.items():
        if getattr(config, field_name) is None:
            setattr(config, field_name, default_value)
            fields_to_update.append(field_name)

    if fields_to_update:
        config.save(update_fields=fields_to_update)


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_alter_agentdefaultsurface_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultagentdefinitionconfig",
            name="cache",
            field=models.BooleanField(
                default=False,
                help_text="Default for whether tool-result caching is enabled when AgentDefinition.cache is null.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="defaultagentdefinitionconfig",
            name="default_temperature",
            field=models.FloatField(
                default=0.7,
                help_text="Default sampling temperature applied when neither the AgentDefinition nor its LLMConfig specify one.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="defaultagentdefinitionconfig",
            name="max_execution_time",
            field=models.IntegerField(
                default=60,
                help_text="Default per-run wall-clock budget in seconds when AgentDefinition.max_execution_time is null.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="defaultagentdefinitionconfig",
            name="max_iter",
            field=models.IntegerField(
                default=25,
                help_text="Default max reasoning iterations for an AgentDefinition when its own value is null.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="defaultagentdefinitionconfig",
            name="max_retry_limit",
            field=models.IntegerField(
                default=3,
                help_text="Default max retries on transient failures when AgentDefinition.max_retry_limit is null.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="defaultagentdefinitionconfig",
            name="max_rpm",
            field=models.IntegerField(
                default=10,
                help_text="Default max LLM requests per minute when AgentDefinition.max_rpm is null.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="defaultagentdefinitionconfig",
            name="schema_max_retries",
            field=models.IntegerField(
                default=2,
                help_text="Default max schema-enforcement retries when AgentDefinition.schema_max_retries is null.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_singleton_defaults, migrations.RunPython.noop),
    ]
