# Generated by Django 5.1.7 on 2026-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_alter_defaultagentdefinitionconfig_cache_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentdefinition",
            name="max_tool_calls",
            field=models.IntegerField(
                default=None,
                help_text="Max tool calls executed per agent run. Null falls back to DefaultAgentDefinitionConfig.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="defaultagentdefinitionconfig",
            name="max_tool_calls",
            field=models.IntegerField(
                default=15,
                help_text="Default max tool calls executed per agent run when AgentDefinition.max_tool_calls is null. Null = unlimited.",
                null=True,
            ),
        ),
    ]
