# Generated by Django 5.1.7 on 2026-08-27 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_alter_defaultagentdefinitionconfig_cache_and_more"),
        ("tables", "0230_remove_graph_unique_graph_name_per_org_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinlinesurface",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurface",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphbasicsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphbasicsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphlocalsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphlocalsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfaceknowledge",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfaceknowledge",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacemcptool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacemcptool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacenaivesearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacenaivesearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacepythontool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacepythontool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacestorageitem",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacestorageitem",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphbasicsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphbasicsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphlocalsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphlocalsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfaceknowledge",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfaceknowledge",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacemcptool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacemcptool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacenaivesearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacenaivesearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacepythontool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacepythontool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacestorageitem",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacestorageitem",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="surfacegraphbasicsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="surfacegraphbasicsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="surfacegraphlocalsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="surfacegraphlocalsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="surfaceknowledge",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="surfaceknowledge",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="surfacenaivesearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="surfacenaivesearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="surfacepythontool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="surfacepythontool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentinlinesurfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AlterField(
            model_name="agentinlinesurfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.pythoncodetool",
            ),
        ),
        migrations.AlterField(
            model_name="inlinesurfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AlterField(
            model_name="inlinesurfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.pythoncodetool",
            ),
        ),
        migrations.AlterField(
            model_name="surfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AlterField(
            model_name="surfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.pythoncodetool",
            ),
        ),
    ]
