# Generated by Django 5.1.7 on 2026-09-01 15:22

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_alter_defaultagentdefinitionconfig_cache_and_more"),
        ("tables", "0234_merge_knowledge_node_and_agent_node_migrations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentinlinesurface",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="agentinlinesurfacegraphbasicsearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="agentinlinesurfacegraphlocalsearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="agentinlinesurfaceknowledge",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="agentinlinesurfacemcptool",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="agentinlinesurfacenaivesearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="agentinlinesurfacepythontool",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="agentinlinesurfacestorageitem",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="inlinesurface",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="inlinesurfacegraphbasicsearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="inlinesurfacegraphlocalsearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="inlinesurfaceknowledge",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="inlinesurfacemcptool",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="inlinesurfacenaivesearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="inlinesurfacepythontool",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="inlinesurfacestorageitem",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="surfacegraphbasicsearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="surfacegraphlocalsearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="surfaceknowledge",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="surfacenaivesearchconfig",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelOptions(
            name="surfacepythontool",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelManagers(
            name="agentinlinesurface",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="agentinlinesurfacegraphbasicsearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="agentinlinesurfacegraphlocalsearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="agentinlinesurfaceknowledge",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="agentinlinesurfacemcptool",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="agentinlinesurfacenaivesearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="agentinlinesurfacepythontool",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="agentinlinesurfacestorageitem",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="inlinesurface",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="inlinesurfacegraphbasicsearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="inlinesurfacegraphlocalsearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="inlinesurfaceknowledge",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="inlinesurfacemcptool",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="inlinesurfacenaivesearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="inlinesurfacepythontool",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="inlinesurfacestorageitem",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="surfacegraphbasicsearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="surfacegraphlocalsearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="surfaceknowledge",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="surfacenaivesearchconfig",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="surfacepythontool",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="agentinlinesurface",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurface",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphbasicsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphbasicsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphlocalsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacegraphlocalsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfaceknowledge",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfaceknowledge",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacemcptool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacemcptool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacenaivesearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacenaivesearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacepythontool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacepythontool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacestorageitem",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="agentinlinesurfacestorageitem",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurface",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphbasicsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphbasicsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphlocalsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacegraphlocalsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfaceknowledge",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfaceknowledge",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacemcptool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacemcptool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacenaivesearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacenaivesearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacepythontool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacepythontool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inlinesurfacestorageitem",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="inlinesurfacestorageitem",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surfacegraphbasicsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="surfacegraphbasicsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surfacegraphlocalsearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="surfacegraphlocalsearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surfaceknowledge",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="surfaceknowledge",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surfacenaivesearchconfig",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="surfacenaivesearchconfig",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surfacepythontool",
            name="is_soft_deleted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="surfacepythontool",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentinlinesurfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AlterField(
            model_name="agentinlinesurfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.pythoncodetool",
            ),
        ),
        migrations.AlterField(
            model_name="inlinesurfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AlterField(
            model_name="inlinesurfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.pythoncodetool",
            ),
        ),
        migrations.AlterField(
            model_name="surfaceknowledge",
            name="collection",
            field=models.ForeignKey(
                help_text="SourceCollection available within this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.sourcecollection",
            ),
        ),
        migrations.AlterField(
            model_name="surfacepythontool",
            name="python_tool",
            field=models.ForeignKey(
                help_text="PythonCodeTool being allowed or denied on this surface.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.pythoncodetool",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurface",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_agentinlinesurface_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacegraphbasicsearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_agentinlinesurfacegraphbasicsearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacegraphlocalsearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_agentinlinesurfacegraphlocalsearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfaceknowledge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_agentinlinesurfaceknowledge_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacemcptool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_agentinlinesurfacemcptool_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacenaivesearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_agentinlinesurfacenaivesearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacepythontool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_agentinlinesurfacepythontool_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinlinesurfacestorageitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_agentinlinesurfacestorageitem_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurface",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_inlinesurface_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacegraphbasicsearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_inlinesurfacegraphbasicsearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacegraphlocalsearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_inlinesurfacegraphlocalsearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfaceknowledge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_inlinesurfaceknowledge_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacemcptool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_inlinesurfacemcptool_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacenaivesearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_inlinesurfacenaivesearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacepythontool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_inlinesurfacepythontool_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="inlinesurfacestorageitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_inlinesurfacestorageitem_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="surfacegraphbasicsearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_surfacegraphbasicsearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="surfacegraphlocalsearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_surfacegraphlocalsearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="surfaceknowledge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_surfaceknowledge_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="surfacenaivesearchconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_surfacenaivesearchconfig_soft_delete_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="surfacepythontool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_soft_deleted", False), ("soft_deleted_at__isnull", True)
                    ),
                    models.Q(
                        ("is_soft_deleted", True), ("soft_deleted_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="agents_surfacepythontool_soft_delete_consistency",
            ),
        ),
    ]
