# Generated by Django 5.1.7 on 2026-09-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentinlinesurfacegraphbasicsearchconfig_is_suggested_and_more'),
        ('agents', '0006_alter_agentinlinesurface_options_and_more'),
    ]

    operations = [
    ]
