# Generated by Django 5.1.7 on 2026-09-17 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0007_merge_20260909_1433"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agentinlinesurfaceknowledge",
            name="agents_agentinlinesurfaceknowledge_soft_delete_consistency",
        ),
    ]
