# Generated by Django 5.1.7 on 2026-09-22 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "agents",
            "0008_remove_agentinlinesurfaceknowledge_agents_agentinlinesurfaceknowledge_soft_delete_consistency",
        ),
        ("rbac", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="agentdefinition",
                    name="organization",
                    field=models.ForeignKey(
                        help_text="Organization this agent belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_definitions",
                        to="rbac.organization",
                    ),
                ),
                migrations.AlterField(
                    model_name="surface",
                    name="organization",
                    field=models.ForeignKey(
                        help_text="Organization this surface belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surfaces",
                        to="rbac.organization",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
