# Generated by Django 5.1.14 on 2026-10-02 11:12

from django.db import migrations, models


APP_LABEL = "agents"


def _soft_delete_tables(apps):
    for model in apps.get_app_config(APP_LABEL).get_models():
        field_names = {field.name for field in model._meta.get_fields()}
        if {"active", "is_soft_deleted"} <= field_names:
            yield model._meta.db_table


def copy_is_soft_deleted_to_active(apps, schema_editor):
    # AddField filled every row with the DB default (true) without rewriting the
    # table. Only the binned rows need a write.
    for table in _soft_delete_tables(apps):
        schema_editor.execute(
            f"UPDATE {schema_editor.quote_name(table)} SET active = false WHERE is_soft_deleted"
        )


def copy_active_to_is_soft_deleted(apps, schema_editor):
    for table in _soft_delete_tables(apps):
        schema_editor.execute(
            f"UPDATE {schema_editor.quote_name(table)} SET is_soft_deleted = true WHERE NOT active"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agentdefinition_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinlinesurface',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacegraphbasicsearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacegraphlocalsearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfaceknowledge',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacemcptool',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacenaivesearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacepythontool',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacestorageitem',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='inlinesurface',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacegraphbasicsearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacegraphlocalsearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='inlinesurfaceknowledge',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacemcptool',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacenaivesearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacepythontool',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacestorageitem',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='surfacegraphbasicsearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='surfacegraphlocalsearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='surfaceknowledge',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='surfacenaivesearchconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='surfacepythontool',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.RunPython(copy_is_soft_deleted_to_active, copy_active_to_is_soft_deleted),
    ]
