# Generated by Django 5.1.14 on 2026-09-30 07:43

import django.core.validators
import tables.validators.finite_number_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentdefinition_backfill_exec_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='max_consecutive_failures',
        ),
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='max_execution_time',
        ),
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='max_iter',
        ),
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='max_retry_limit',
        ),
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='max_rpm',
        ),
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='max_tool_calls',
        ),
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='schema_max_retries',
        ),
        migrations.RemoveField(
            model_name='defaultagentdefinitionconfig',
            name='tool_timeout',
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='cache',
            field=models.BooleanField(default=False, help_text='Enable tool-result caching for this agent.'),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='default_temperature',
            field=models.FloatField(default=None, help_text='Sampling temperature applied when the LLMConfig leaves it unset. Null falls back to DefaultAgentDefinitionConfig.', null=True, validators=[tables.validators.finite_number_validator.validate_finite_number, django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='max_consecutive_failures',
            field=models.IntegerField(default=3, help_text='Consecutive failed tool calls before graceful stop.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='max_execution_time',
            field=models.IntegerField(default=600, help_text='Wall-clock budget in seconds for a single agent run.', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='max_iter',
            field=models.IntegerField(default=15, help_text='Max reasoning iterations per task before forcing a final answer.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='max_retry_limit',
            field=models.IntegerField(default=3, help_text='Max retries on transient LLM/tool failures.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='max_rpm',
            field=models.IntegerField(default=30, help_text='LLM request rate cap (requests per minute).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='max_tool_calls',
            field=models.IntegerField(default=15, help_text='Max tool calls executed per agent run.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='schema_max_retries',
            field=models.IntegerField(default=2, help_text='Max retries when enforcing structured-output schema validation.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='tool_timeout',
            field=models.IntegerField(default=300, help_text='Per-tool-call timeout in seconds.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1800)]),
        ),
    ]
