# Generated by Django 5.1.14 on 2026-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentdefinition_surface_org_scoped'),
    ]

    # Adding an auto_now_add column in one AddField fills every existing row with the
    # migration time (the schema editor's effective default for auto_now_add is now()).
    # Existing agents have no known creation time, so the column is added as a plain
    # nullable field first and only then switched to auto_now_add, leaving them NULL.
    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='agentdefinition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this agent definition was created. Null for agents created before creation times were recorded.', null=True),
        ),
    ]
