# Generated by Django 5.1.14 on 2026-10-02 11:17

from django.db import migrations, models


APP_LABEL = "agents"


def _soft_delete_tables(apps):
    for model in apps.get_app_config(APP_LABEL).get_models():
        field_names = {field.name for field in model._meta.local_fields}
        if {"active", "is_soft_deleted"} <= field_names:
            yield model._meta.db_table


def copy_active_to_is_soft_deleted(apps, schema_editor):
    # Backwards only: runs after RemoveField re-adds is_soft_deleted (every row
    # false) and before the old constraints come back, which binned rows would
    # violate until the flag is copied.
    for table in _soft_delete_tables(apps):
        schema_editor.execute(
            f"UPDATE {schema_editor.quote_name(table)} SET is_soft_deleted = true WHERE NOT active"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_soft_delete_active_flag'),
        ('tables', '0258_soft_delete_active_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentinlinesurface',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentinlinesurfacegraphbasicsearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentinlinesurfacegraphlocalsearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentinlinesurfaceknowledge',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentinlinesurfacemcptool',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentinlinesurfacenaivesearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentinlinesurfacepythontool',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentinlinesurfacestorageitem',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='inlinesurface',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='inlinesurfacegraphbasicsearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='inlinesurfacegraphlocalsearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='inlinesurfaceknowledge',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='inlinesurfacemcptool',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='inlinesurfacenaivesearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='inlinesurfacepythontool',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='inlinesurfacestorageitem',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='surfacegraphbasicsearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='surfacegraphlocalsearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='surfaceknowledge',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='surfacenaivesearchconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='surfacepythontool',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='agentinlinesurface',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentinlinesurfacegraphbasicsearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentinlinesurfacegraphlocalsearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentinlinesurfaceknowledge',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentinlinesurfacemcptool',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentinlinesurfacenaivesearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentinlinesurfacepythontool',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentinlinesurfacestorageitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='inlinesurface',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='inlinesurfacegraphbasicsearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='inlinesurfacegraphlocalsearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='inlinesurfaceknowledge',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='inlinesurfacemcptool',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='inlinesurfacenaivesearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='inlinesurfacepythontool',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='inlinesurfacestorageitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='surfacegraphbasicsearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='surfacegraphlocalsearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='surfaceknowledge',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='surfacenaivesearchconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='surfacepythontool',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='agentinlinesurface',
            name='agents_agentinlinesurface_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentinlinesurfacegraphbasicsearchconfig',
            name='agents_agentinlinesurfacegraphbasicsearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentinlinesurfacegraphlocalsearchconfig',
            name='agents_agentinlinesurfacegraphlocalsearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentinlinesurfacemcptool',
            name='agents_agentinlinesurfacemcptool_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentinlinesurfacenaivesearchconfig',
            name='agents_agentinlinesurfacenaivesearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentinlinesurfacepythontool',
            name='agents_agentinlinesurfacepythontool_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentinlinesurfacestorageitem',
            name='agents_agentinlinesurfacestorageitem_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='inlinesurface',
            name='agents_inlinesurface_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='inlinesurfacegraphbasicsearchconfig',
            name='agents_inlinesurfacegraphbasicsearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='inlinesurfacegraphlocalsearchconfig',
            name='agents_inlinesurfacegraphlocalsearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='inlinesurfaceknowledge',
            name='agents_inlinesurfaceknowledge_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='inlinesurfacemcptool',
            name='agents_inlinesurfacemcptool_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='inlinesurfacenaivesearchconfig',
            name='agents_inlinesurfacenaivesearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='inlinesurfacepythontool',
            name='agents_inlinesurfacepythontool_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='inlinesurfacestorageitem',
            name='agents_inlinesurfacestorageitem_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='surfacegraphbasicsearchconfig',
            name='agents_surfacegraphbasicsearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='surfacegraphlocalsearchconfig',
            name='agents_surfacegraphlocalsearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='surfaceknowledge',
            name='agents_surfaceknowledge_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='surfacenaivesearchconfig',
            name='agents_surfacenaivesearchconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='surfacepythontool',
            name='agents_surfacepythontool_soft_delete_consistency',
        ),
        migrations.RunPython(migrations.RunPython.noop, copy_active_to_is_soft_deleted),
        migrations.RemoveField(
            model_name='agentinlinesurface',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentinlinesurfacegraphbasicsearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentinlinesurfacegraphlocalsearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentinlinesurfaceknowledge',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentinlinesurfacemcptool',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentinlinesurfacenaivesearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentinlinesurfacepythontool',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentinlinesurfacestorageitem',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='inlinesurface',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='inlinesurfacegraphbasicsearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='inlinesurfacegraphlocalsearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='inlinesurfaceknowledge',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='inlinesurfacemcptool',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='inlinesurfacenaivesearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='inlinesurfacepythontool',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='inlinesurfacestorageitem',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='surfacegraphbasicsearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='surfacegraphlocalsearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='surfaceknowledge',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='surfacenaivesearchconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='surfacepythontool',
            name='is_soft_deleted',
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurface',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_agentinlinesurface_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacegraphbasicsearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_agentinlinesurfacegraphbasicsearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacegraphlocalsearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_agentinlinesurfacegraphlocalsearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacemcptool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_agentinlinesurfacemcptool_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacenaivesearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_agentinlinesurfacenaivesearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacepythontool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_agentinlinesurfacepythontool_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacestorageitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_agentinlinesurfacestorageitem_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurface',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_inlinesurface_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacegraphbasicsearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_inlinesurfacegraphbasicsearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacegraphlocalsearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_inlinesurfacegraphlocalsearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfaceknowledge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_inlinesurfaceknowledge_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacemcptool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_inlinesurfacemcptool_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacenaivesearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_inlinesurfacenaivesearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacepythontool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_inlinesurfacepythontool_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacestorageitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_inlinesurfacestorageitem_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='surfacegraphbasicsearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_surfacegraphbasicsearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='surfacegraphlocalsearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_surfacegraphlocalsearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='surfaceknowledge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_surfaceknowledge_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='surfacenaivesearchconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_surfacenaivesearchconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='surfacepythontool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_surfacepythontool_soft_delete_consistency'),
        ),
    ]
