# Generated by Django 5.1.14 on 2026-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_alter_agentinlinesurface_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinlinesurface',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacegraphbasicsearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacegraphlocalsearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfaceknowledge',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacemcptool',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacenaivesearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacepythontool',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacestorageitem',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inlinesurface',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacegraphbasicsearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacegraphlocalsearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inlinesurfaceknowledge',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacemcptool',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacenaivesearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacepythontool',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='inlinesurfacestorageitem',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='surfacegraphbasicsearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='surfacegraphlocalsearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='surfaceknowledge',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='surfacenaivesearchconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='surfacepythontool',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
