# Generated by Django 5.1.14 on 2026-10-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agentdefinition_created_at'),
        ('agents', '0013_agentdefinition_instruction_list'),
    ]

    operations = [
    ]
