# Generated by Django 5.1.14 on 2026-10-05 13:46

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_soft_delete_surface'),
        ('rbac', '0003_key_value_tables_resource_type'),
        ('tables', '0264_soft_delete_mcp_tool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentdefinition',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='agentdefinition',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='agentdefinition',
            name='unique_agent_definition_name_per_organization',
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='agents_agentdefinition_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('organization', 'name'), name='unique_agent_definition_name_per_organization'),
        ),
    ]
