# Generated by Django 5.1.14 on 2026-10-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agentdefinition_instruction_list'),
        ('agents', '0016_soft_delete_agent_definition'),
    ]

    operations = [
    ]
