from pathlib import Path

from shared.envtools import Env

BASE_DIR = Path(__file__).resolve().parent

env = Env()
if not env.bool("RUN_IN_DOCKER", False):
    env.read_env(BASE_DIR / "../.env")

LOG_LEVEL = env.str("AGENT_LOG_LEVEL")

REDIS_HOST = env.str("REDIS_HOST")
REDIS_PORT = env.int("REDIS_PORT")
REDIS_USER = env.str("REDIS_USER")
REDIS_PASSWORD = env.str("REDIS_PASSWORD")

AGENT_REQUEST_STREAM = env.str("AGENT_REQUEST_STREAM")
AGENT_RESULT_STREAM = env.str("AGENT_RESULT_STREAM")
AGENT_CONSUMER_GROUP = env.str("AGENT_CONSUMER_GROUP")

AGENT_DEFAULT_MAX_RETRIES = env.int("AGENT_DEFAULT_MAX_RETRIES")
AGENT_DEFAULT_MAX_ITER = env.int("AGENT_DEFAULT_MAX_ITER")
AGENT_SCHEMA_MAX_RETRIES = env.int("AGENT_SCHEMA_MAX_RETRIES")

CODE_EXEC_CHANNEL = env.str("CODE_EXEC_CHANNEL")
CODE_RESULT_CHANNEL = env.str("CODE_RESULT_CHANNEL")

AGENT_DROP_UNSUPPORTED_LLM_PARAMS = env.ыек("AGENT_DROP_UNSUPPORTED_LLM_PARAMS")
AGENT_CONTEXT_WARNING_RATIO = env.float("AGENT_CONTEXT_WARNING_RATIO")

KNOWLEDGE_SEARCH_REQUEST_CHANNEL = env.str("KNOWLEDGE_SEARCH_REQUEST_CHANNEL")
KNOWLEDGE_SEARCH_RESPONSE_CHANNEL = env.str("KNOWLEDGE_SEARCH_RESPONSE_CHANNEL")
NAIVE_RAG_SEARCH_TIMEOUT = env.time("NAIVE_RAG_SEARCH_TIMEOUT")
GRAPH_RAG_SEARCH_TIMEOUT = env.time("GRAPH_RAG_SEARCH_TIMEOUT")
