# Generated by Django 5.1.14 on 2026-10-08 15:11

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.extensions
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


def create_default_llm_model(apps, schema_editor):
    """Seed the OpenAI provider and the gpt-4o model (ported from 0021_create_default_llm_model)."""
    LLMModel = apps.get_model("tables", "LLMModel")
    Provider = apps.get_model("tables", "Provider")

    provider, _ = Provider.objects.get_or_create(name="openai")

    LLMModel.objects.get_or_create(
        name="gpt-4o",
        defaults={
            "llm_provider": provider,
            "is_visible": True,
        },
    )


class Migration(migrations.Migration):

    replaces = [('tables', '0001_initial'), ('tables', '0002_remove_crew_temperature_crew_manager_llm_config_and_more'), ('tables', '0003_alter_session_status'), ('tables', '0004_sessionmessage'), ('tables', '0005_remove_crew_manager_llm_config_alter_agent_tools_and_more'), ('tables', '0006_alter_crew_manager_llm_model_crew_manager_llm_config_and_more'), ('tables', '0007_tool_enabled_delete_enabledtools'), ('tables', '0008_embeddingmodel_base_url_embeddingmodel_deployment'), ('tables', '0009_alter_agent_fcm_llm_config_alter_agent_fcm_llm_model_and_more'), ('tables', '0010_remove_templateagent_agent_and_more'), ('tables', '0011_remove_llmmodel_context_size'), ('tables', '0012_tool_name_alias'), ('tables', '0013_alter_session_options'), ('tables', '0014_rename_comments_llmmodel_description_and_more'), ('tables', '0015_rename_comments_crew_description'), ('tables', '0016_alter_templateagent_memory'), ('tables', '0017_alter_task_order_alter_tool_requires_model'), ('tables', '0018_session_finished_at'), ('tables', '0019_alter_session_crew'), ('tables', '0020_llmmodel_is_visible_alter_crew_embedding_model_and_more'), ('tables', '0021_create_default_llm_model'), ('tables', '0022_create_default_llm_model'), ('tables', '0023_remove_llmdefaultcrewconfig_default_llm_config_and_more'), ('tables', '0024_configllm_is_visible'), ('tables', '0025_defaultllmconfig'), ('tables', '0026_defaultagentconfig_allow_delegation_and_more'), ('tables', '0027_rename_default_llm_config_defaultagentconfig_llm_config'), ('tables', '0028_remove_defaultcrewconfig_default_llm_config_and_more'), ('tables', '0029_defaultagentconfig_fcm_llm_config_and_more'), ('tables', '0030_configllm_custom_name'), ('tables', '0031_session_crew_schema_alter_session_finished_at'), ('tables', '0032_rename_configllm_llmconfig_remove_agent_tools_and_more'), ('tables', '0033_embeddingconfig_is_visible_embeddingmodel_is_visible'), ('tables', '0034_defaultembeddingconfig_api_key_and_more'), ('tables', '0035_remove_duplicated_tools'), ('tables', '0036_alter_toolconfigfield_data_type'), ('tables', '0037_task_human_input'), ('tables', '0038_toolconfigfield_title'), ('tables', '0039_agentsessionmessage_tasksessionmessage_and_more'), ('tables', '0040_pythoncode_pythoncodetool_agentpythoncodetool'), ('tables', '0041_alter_agentpythoncodetool_agent_and_more'), ('tables', '0042_pythoncoderesult'), ('tables', '0043_session_kickoff_inputs'), ('tables', '0044_pythoncode_global_kwargs'), ('tables', '0045_conditionaledge_crewnode_edge_graph_pythonnode_and_more'), ('tables', '0046_rename_crew_id_agentsessionmessage_crew_and_more'), ('tables', '0047_session_status_data_alter_conditionaledge_graph_and_more'), ('tables', '0048_enable_pgvector'), ('tables', '0049_memorydatabase'), ('tables', '0050_graphsessionmessage'), ('tables', '0051_remove_crew_assignment_and_more'), ('tables', '0052_alter_taskcontext_context_taskpythoncodetools'), ('tables', '0053_rename_tool_taskpythoncodetools_python_code_tool_and_more'), ('tables', '0054_remove_graphsessionmessage_tables_grap_session_8a3a6b_idx_and_more'), ('tables', '0055_alter_agentpythoncodetool_agent_alter_crewnode_crew_and_more'), ('tables', '0056_crewnode_position_graph_metadata_llmnode_position_and_more'), ('tables', '0057_graph_description_alter_defaultllmconfig_max_tokens'), ('tables', '0058_remove_crewnode_position_remove_llmnode_position_and_more'), ('tables', '0059_agent_python_code_tools_delete_agentpythoncodetool'), ('tables', '0060_conditionaledge_input_map_crewnode_input_map_and_more'), ('tables', '0061_alter_agent_default_temperature_and_more'), ('tables', '0062_agenttag_crewtag_graphtag_agent_tags_crew_tags_and_more'), ('tables', '0063_alter_agent_tags_alter_crew_tags_alter_graph_tags'), ('tables', '0054_documentmetadata_alter_defaultagentconfig_max_rpm_and_more'), ('tables', '0055_agent_knowledge_collection_crew_knowledge_collection_and_more'), ('tables', '0062_merge_20250307_1455'), ('tables', '0064_merge_20250314_1123'), ('tables', '0065_crew_metadata'), ('tables', '0066_realtimeagent'), ('tables', '0067_realtimeagentmodel_realtimeagent_model'), ('tables', '0068_rename_realtimeagentmodel_realtimemodel'), ('tables', '0069_alter_defaultagentconfig_default_temperature'), ('tables', '0070_rename_rt_model_name_realtimemodel_name_and_more'), ('tables', '0069_realtimeagent_distance_threshold_and_more'), ('tables', '0071_merge_20250325_1531'), ('tables', '0072_realtimesessionitem'), ('tables', '0073_remove_realtimeagent_realtime_config_and_more'), ('tables', '0073_alter_sourcecollection_embedder'), ('tables', '0074_merge_20250329_1039'), ('tables', '0075_realtimemodel_provider'), ('tables', '0076_realtimeconfig_custom_name'), ('tables', '0077_remove_realtimeagent_connection_key_and_more'), ('tables', '0078_realtimetranscriptionconfig_and_more'), ('tables', '0079_rename_realtime_model_realtimetranscriptionconfig_realtime_transcription_model_and_more'), ('tables', '0080_auto_20250417_1302'), ('tables', '0081_alter_realtimeagent_agent_and_more'), ('tables', '0082_remove_documentcontent_document_metadata_and_more'), ('tables', '0083_documentmetadata_additional_params'), ('tables', '0084_alter_documentmetadata_chunk_strategy_and_more'), ('tables', '0080_rename_initial_state_session_variables_and_more'), ('tables', '0085_merge_20250429_1542'), ('tables', '0086_graph_time_to_live_session_status_updated_at_and_more'), ('tables', '0087_alter_session_status_updated_at'), ('tables', '0086_remove_startnode_unique_startnode_per_graph_and_more'), ('tables', '0088_merge_20250526_1337'), ('tables', '0089_alter_session_graph'), ('tables', '0090_alter_llmconfig_model_alter_llmnode_llm_config_and_more'), ('tables', '0087_conditiongroup_condition_decisiontablenode_and_more'), ('tables', '0088_condition_condition_name_alter_condition_condition_and_more'), ('tables', '0091_merge_20250602_1048')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.7)),
                ('num_ctx', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('context_size', models.IntegerField(default=0)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('deployment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('goal', models.TextField()),
                ('backstory', models.TextField()),
                ('allow_delegation', models.BooleanField(default=False)),
                ('memory', models.TextField(blank=True, null=True)),
                ('max_iter', models.IntegerField(default=25)),
                ('fcm_llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_agents_config', to='tables.configllm')),
                ('llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_agents_config', to='tables.configllm')),
                ('fcm_llm_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_agents', to='tables.llmmodel')),
                ('llm_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_agents', to='tables.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerLLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.configllm')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.llmmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('assignment', models.TextField()),
                ('process', models.CharField(choices=[('sequential', 'Sequential'), ('hierarchical', 'Hierarchical')], default='sequential', max_length=255)),
                ('verbose', models.BooleanField(default=False)),
                ('memory', models.BooleanField(default=False)),
                ('agents', models.ManyToManyField(to='tables.agent')),
                ('embedding_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingmodel')),
                ('manager_llm_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.managerllmmodel')),
            ],
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='llm_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.provider'),
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='embedding_provider',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.provider'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('instructions', models.TextField()),
                ('expected_output', models.TextField()),
                ('order', models.IntegerField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.agent')),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.crew')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_delegation', models.BooleanField(default=False)),
                ('backstory', models.TextField()),
                ('fcm_llm_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_template_agents_config', to='tables.configllm')),
                ('fcm_llm_model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_template_agents', to='tables.llmmodel')),
                ('goal', models.TextField()),
                ('llm_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_template_agents_config', to='tables.configllm')),
                ('llm_model', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_template_agents', to='tables.llmmodel')),
                ('max_iter', models.IntegerField(default=25)),
                ('memory', models.TextField(blank=True, null=True)),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('requires_model', models.BooleanField()),
                ('embedding_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingmodel')),
                ('llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.configllm')),
                ('llm_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmmodel')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnabledTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.ManyToManyField(to='tables.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('end', 'End'), ('run', 'Run'), ('wait_for_user', 'Wait For User'), ('error', 'Error')], max_length=255)),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.crew')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_from', models.CharField(choices=[('user', 'User'), ('crew', 'Crew')], max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.session')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='tools',
            field=models.ManyToManyField(blank=True, default=[], to='tables.tool'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='agents',
            field=models.ManyToManyField(blank=True, to='tables.agent'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmmodel'),
        ),
        migrations.AddField(
            model_name='crew',
            name='manager_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_manager_llm_config', to='tables.configllm'),
        ),
        migrations.DeleteModel(
            name='ManagerLLMModel',
        ),
        migrations.DeleteModel(
            name='EnabledTools',
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='base_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='deployment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='fcm_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_agents_config', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='fcm_llm_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_agents', to='tables.llmmodel'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_agents_config', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_agents', to='tables.llmmodel'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='embedding_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingmodel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.agent'),
        ),
        migrations.AlterField(
            model_name='task',
            name='crew',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.crew'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='embedding_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingmodel'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='llm_model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmmodel'),
        ),
        migrations.AddField(
            model_name='templateagent',
            name='tools',
            field=models.ManyToManyField(blank=True, default=[], to='tables.tool'),
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='context_size',
        ),
        migrations.AddField(
            model_name='tool',
            name='name_alias',
            field=models.TextField(default='name_alias'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='llmmodel',
            old_name='comments',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='verbose',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='memory',
        ),
        migrations.AddField(
            model_name='agent',
            name='memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crew',
            name='assignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='crew',
            old_name='comments',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='templateagent',
            name='memory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='requires_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.crew'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_manager_llm_model', to='tables.llmmodel'),
        ),
        migrations.CreateModel(
            name='LLMDefaultAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_agent_llm_config', to='tables.configllm')),
                ('default_llm_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_agent_llm_model', to='tables.llmmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMDefaultCrewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_crew_llm_config', to='tables.configllm')),
                ('default_llm_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_crew_llm_model', to='tables.llmmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            code=create_default_llm_model,
        ),
        migrations.AddField(
            model_name='configllm',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.llmmodel'),
        ),
        migrations.RemoveField(
            model_name='llmdefaultcrewconfig',
            name='default_llm_config',
        ),
        migrations.RemoveField(
            model_name='llmdefaultcrewconfig',
            name='default_llm_model',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='fcm_llm_model',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='manager_llm_model',
        ),
        migrations.RemoveField(
            model_name='templateagent',
            name='fcm_llm_model',
        ),
        migrations.RemoveField(
            model_name='templateagent',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='llm_model',
        ),
        migrations.AlterField(
            model_name='agent',
            name='fcm_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_agents', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_agents', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_crews', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='templateagent',
            name='fcm_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcm_template_agents', to='tables.configllm'),
        ),
        migrations.AlterField(
            model_name='templateagent',
            name='llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_template_agents', to='tables.configllm'),
        ),
        migrations.CreateModel(
            name='DefaultAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_agent_config', to='tables.configllm')),
                ('allow_delegation', models.BooleanField(default=False)),
                ('max_iter', models.IntegerField(default=25)),
                ('memory', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultCrewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.BooleanField(default=False)),
                ('process', models.CharField(choices=[('sequential', 'Sequential'), ('hierarchical', 'Hierarchical')], default='sequential', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LLMDefaultAgentConfig',
        ),
        migrations.AddField(
            model_name='configllm',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configllm',
            name='custom_name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RenameModel(
            old_name='ConfigLLM',
            new_name='LLMConfig',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='templateagent',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='embedding_model',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='llm_config',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='requires_model',
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmbeddingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.TextField(unique=True)),
                ('task_type', models.CharField(choices=[('retrieval_document', 'Retrieval Doc')], default='retrieval_document', max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.embeddingmodel')),
                ('is_visible', models.BooleanField(default=True)),
                ('api_key', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='embedding_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingconfig'),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='embedding_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingconfig'),
        ),
        migrations.CreateModel(
            name='ToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField(default=dict)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.tool')),
                ('name', models.CharField(default='M_tool_config', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='configured_tools',
            field=models.ManyToManyField(blank=True, default=[], to='tables.toolconfig'),
        ),
        migrations.AddField(
            model_name='templateagent',
            name='configured_tools',
            field=models.ManyToManyField(blank=True, default=[], to='tables.toolconfig'),
        ),
        migrations.CreateModel(
            name='ToolConfigField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('llm_config', 'Llm Config'), ('embedding_config', 'Embedding Config'), ('string', 'String'), ('boolean', 'Boolean'), ('any', 'Any'), ('integer', 'Integer'), ('float', 'Float')], default='string', max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_fields', to='tables.tool')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'unique_together': {('tool', 'name')},
            },
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='fcm_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_agent_fcm_config', to='tables.llmconfig'),
        ),
        migrations.AlterField(
            model_name='defaultagentconfig',
            name='llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_agent_config', to='tables.llmconfig'),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='manager_llm_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_crew_config', to='tables.llmconfig'),
        ),
        migrations.CreateModel(
            name='DefaultEmbeddingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('retrieval_document', 'Retrieval Doc')], default='retrieval_document', max_length=255)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingmodel')),
                ('api_key', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmmodel')),
                ('num_ctx', models.IntegerField(default=25)),
                ('temperature', models.FloatField(default=0.7)),
                ('api_key', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='embeddingconfig',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingmodel'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmmodel'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='llm_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.provider'),
        ),
        migrations.DeleteModel(
            name='LLMDefaultCrewConfig',
        ),
        migrations.AddField(
            model_name='task',
            name='human_input',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PythonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('entrypoint', models.TextField(default='main')),
                ('libraries', models.TextField(default='')),
                ('global_kwargs', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PythonCodeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('args_schema', models.JSONField()),
                ('python_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.pythoncode')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPythonCodeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(help_text='The agent using the Python code tool.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_python_code_tools', to='tables.agent')),
                ('python_code_tool', models.ForeignKey(help_text='The Python code tool associated with the agent.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_associations', to='tables.pythoncodetool')),
            ],
            options={
                'verbose_name': 'Agent Python Code Tool Association',
                'verbose_name_plural': 'Agent Python Code Tool Associations',
                'unique_together': {('agent', 'python_code_tool')},
            },
        ),
        migrations.CreateModel(
            name='PythonCodeResult',
            fields=[
                ('execution_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('result_data', models.TextField(default=None, null=True)),
                ('stderr', models.TextField(default='')),
                ('stdout', models.TextField(default='')),
                ('returncode', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='initial_state',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entry_point', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='crew',
        ),
        migrations.CreateModel(
            name='AgentSessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thought', models.TextField(blank=True, default='')),
                ('tool', models.TextField(blank=True, default=None, null=True)),
                ('tool_input', models.TextField(blank=True, default=None, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('result', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.agent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.session')),
                ('crew', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.crew')),
                ('execution_order', models.IntegerField(default=0)),
                ('node_name', models.CharField(default='')),
            ],
            options={
                'abstract': False,
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='graph_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='TaskSessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('raw', models.TextField(blank=True, default='')),
                ('agent', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.session')),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.task')),
                ('crew', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.crew')),
                ('execution_order', models.IntegerField(default=0)),
                ('node_name', models.CharField(default='')),
            ],
            options={
                'abstract': False,
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='UserSessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.session')),
                ('crew', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.crew')),
                ('execution_order', models.IntegerField(default=0)),
                ('node_name', models.CharField(default='')),
            ],
            options={
                'abstract': False,
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_key', models.CharField(max_length=255)),
                ('end_key', models.CharField(max_length=255)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_list', to='tables.graph')),
            ],
        ),
        migrations.CreateModel(
            name='CrewNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.crew')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_node_list', to='tables.graph')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('then', models.CharField(default=None, max_length=255, null=True)),
                ('python_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncode')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_edge_list', to='tables.graph')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.graph'),
        ),
        migrations.CreateModel(
            name='PythonNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='python_node_list', to='tables.graph')),
                ('python_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncode')),
            ],
        ),
        migrations.DeleteModel(
            name='SessionMessage',
        ),
        migrations.AddField(
            model_name='session',
            name='status_data',
            field=models.JSONField(default=dict),
        ),
        pgvector.django.extensions.VectorExtension(
        ),
        migrations.CreateModel(
            name='MemoryDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='vector_index', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.RemoveField(
            model_name='crew',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='defaultcrewconfig',
            name='process',
        ),
        migrations.RemoveField(
            model_name='defaultllmconfig',
            name='num_ctx',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='num_ctx',
        ),
        migrations.AddField(
            model_name='agent',
            name='allow_code_execution',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='cache',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='default_temperature',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_execution_time',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_retry_limit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_rpm',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='respect_context_window',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='cache',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='default_temperature',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='full_output',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crew',
            name='max_rpm',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='planning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crew',
            name='planning_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmconfig'),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='allow_code_execution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='cache',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='default_temperature',
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='max_execution_time',
            field=models.IntegerField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='max_retry_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='respect_context_window',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='cache',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='default_temperature',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='planning_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_planning_crews', to='tables.llmconfig'),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='api_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='frequency_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='logit_bias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='logprobs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='max_completion_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='presence_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='response_format',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='stop',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='timeout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='top_logprobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='top_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='api_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='frequency_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='logit_bias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='logprobs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='max_completion_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='max_tokens',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='presence_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='response_format',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='stop',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='timeout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='top_logprobs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='top_p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='async_execution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='output_model',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='allow_delegation',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_iter',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='memory',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='memory',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='defaultagentconfig',
            name='max_iter',
            field=models.IntegerField(default=20, null=True),
        ),
        migrations.AlterField(
            model_name='defaultcrewconfig',
            name='manager_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_manager_crews', to='tables.llmconfig'),
        ),
        migrations.AlterField(
            model_name='defaultllmconfig',
            name='temperature',
            field=models.FloatField(blank=True, default=0.7, null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='temperature',
            field=models.FloatField(blank=True, default=0.7, null=True),
        ),
        migrations.CreateModel(
            name='TaskTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tool_list', to='tables.task')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.tool')),
            ],
            options={
                'unique_together': {('task', 'tool')},
            },
        ),
        migrations.CreateModel(
            name='TaskContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_task_list', to='tables.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_context_list', to='tables.task')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('task', models.F('context')), _negated=True), name='task_not_equal_context')],
                'unique_together': {('task', 'context')},
            },
        ),
        migrations.CreateModel(
            name='TaskPythonCodeTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_python_code_tool_list', to='tables.task')),
                ('python_code_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncodetool')),
            ],
            options={
                'unique_together': {('task', 'python_code_tool')},
            },
        ),
        migrations.CreateModel(
            name='GraphSessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='')),
                ('execution_order', models.IntegerField(default=0)),
                ('message_data', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.session')),
            ],
            options={
                'abstract': False,
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='max_rpm',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='max_rpm',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.RemoveField(
            model_name='graph',
            name='entry_point',
        ),
        migrations.AlterField(
            model_name='agentpythoncodetool',
            name='agent',
            field=models.ForeignKey(help_text='The agent using the Python code tool.', on_delete=django.db.models.deletion.CASCADE, related_name='python_code_tools', to='tables.agent'),
        ),
        migrations.AlterField(
            model_name='crewnode',
            name='node_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tables.llmmodel'),
        ),
        migrations.AlterField(
            model_name='pythonnode',
            name='node_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pythonnode',
            name='python_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.pythoncode'),
        ),
        migrations.AddField(
            model_name='graph',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='graph',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='max_tokens',
            field=models.IntegerField(blank=True, default=4096, null=True),
        ),
        migrations.CreateModel(
            name='LLMNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_node_list', to='tables.graph')),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.llmconfig')),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='python_code_tools',
            field=models.ManyToManyField(blank=True, default=[], to='tables.pythoncodetool'),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='input_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='crewnode',
            name='input_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='crewnode',
            name='output_variable_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='input_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='output_variable_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AgentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predifined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrewTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predifined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predifined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='tags',
            field=models.ManyToManyField(blank=True, default=[], to='tables.agenttag'),
        ),
        migrations.AddField(
            model_name='crew',
            name='tags',
            field=models.ManyToManyField(blank=True, default=[], to='tables.crewtag'),
        ),
        migrations.AddField(
            model_name='graph',
            name='tags',
            field=models.ManyToManyField(blank=True, default=[], to='tables.graphtag'),
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField(help_text='Binary file content (max 12MB)')),
            ],
        ),
        migrations.CreateModel(
            name='SourceCollection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('user_id', models.CharField(blank=True, default='dummy_user', max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'Pdf'), ('csv', 'Csv'), ('docx', 'Docx'), ('txt', 'Txt'), ('json', 'Json'), ('html', 'Html'), ('md', 'Md')], max_length=10)),
                ('chunk_strategy', models.CharField(choices=[('token', 'Token'), ('character', 'Char'), ('markdown', 'Markdown'), ('json', 'Json'), ('html', 'Html'), ('csv', 'Csv')], default='token', max_length=20)),
                ('chunk_size', models.PositiveIntegerField(blank=True, default=1000)),
                ('chunk_overlap', models.PositiveIntegerField(blank=True, default=150)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='new', max_length=20)),
                ('source_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_metadata', to='tables.sourcecollection')),
                ('document_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_metadata', to='tables.documentcontent')),
                ('additional_params', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('embedding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('vector', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings_doc', to='tables.documentmetadata')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings_coll', to='tables.sourcecollection')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='knowledge_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.sourcecollection'),
        ),
        migrations.AddField(
            model_name='crew',
            name='knowledge_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.sourcecollection'),
        ),
        migrations.AddField(
            model_name='crew',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='RealtimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='gpt-4o-mini-realtime-preview-2024-12-17', max_length=250)),
                ('provider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.provider')),
            ],
        ),
        migrations.CreateModel(
            name='RealtimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
                ('realtime_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.realtimemodel')),
                ('custom_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RealtimeSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_key', models.TextField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'realtime_session_items',
            },
        ),
        migrations.CreateModel(
            name='RealtimeAgent',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables.agent')),
                ('distance_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.65, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3)),
                ('search_limit', models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge')),
                ('language', models.CharField(blank=True, help_text='ISO-639-1 format', max_length=2, null=True)),
                ('stop_prompt', models.CharField(blank=True, default='stop', max_length=255, null=True)),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse')], default='alloy', max_length=20)),
                ('voice_recognition_prompt', models.TextField(blank=True, help_text="The prompt to use for the transcription, to guide the model (e.g. 'Expect words related to technology')", null=True)),
                ('wake_word', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='realtimeagent',
            table='realtime_agent',
        ),
        migrations.CreateModel(
            name='RealtimeTranscriptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=250)),
                ('api_key', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='realtimeagent',
            name='realtime_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeconfig'),
        ),
        migrations.AddField(
            model_name='realtimeagent',
            name='realtime_transcription_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimetranscriptionconfig'),
        ),
        migrations.CreateModel(
            name='RealtimeTranscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='whisper-1', max_length=250)),
                ('provider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.provider')),
            ],
        ),
        migrations.AddField(
            model_name='realtimetranscriptionconfig',
            name='realtime_transcription_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.realtimetranscriptionmodel'),
        ),
        migrations.CreateModel(
            name='RealtimeAgentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_limit', models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge')),
                ('distance_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.65, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3)),
                ('connection_key', models.TextField()),
                ('wake_word', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_prompt', models.CharField(blank=True, default='stop', max_length=255, null=True)),
                ('language', models.CharField(blank=True, help_text='ISO-639-1 format', max_length=2, null=True)),
                ('voice_recognition_prompt', models.TextField(blank=True, help_text="The prompt to use for the transcription, to guide the model (e.g. 'Expect words related to technology')", null=True)),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse')], default='alloy', max_length=20)),
                ('rt_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeagent')),
                ('realtime_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeconfig')),
                ('realtime_transcription_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimetranscriptionconfig')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'realtime_agent_chat',
            },
        ),
        migrations.AlterField(
            model_name='realtimeagent',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='realtime_agent', serialize=False, to='tables.agent'),
        ),
        migrations.RenameField(
            model_name='session',
            old_name='initial_state',
            new_name='variables',
        ),
        migrations.CreateModel(
            name='StartNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.JSONField(default=dict)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.graph')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph',), name='unique_startnode_per_graph')],
            },
        ),
        migrations.AddField(
            model_name='graph',
            name='time_to_live',
            field=models.IntegerField(default=3600, help_text='Session lifitime duration in seconds.'),
        ),
        migrations.AddField(
            model_name='session',
            name='status_updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='session',
            name='time_to_live',
            field=models.IntegerField(default=3600, help_text='Session lifitime duration in seconds.'),
        ),
        migrations.AlterField(
            model_name='crewnode',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.crew'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('run', 'Run'), ('wait_for_user', 'Wait For User'), ('error', 'Error'), ('end', 'End'), ('expired', 'Expired')], max_length=255),
        ),
        migrations.DeleteModel(
            name='AgentPythonCodeTool',
        ),
        migrations.RemoveConstraint(
            model_name='startnode',
            name='unique_startnode_per_graph',
        ),
        migrations.AlterField(
            model_name='startnode',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_node_list', to='tables.graph'),
        ),
        migrations.AlterField(
            model_name='crewnode',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.crew'),
        ),
        migrations.AddConstraint(
            model_name='conditionaledge',
            constraint=models.UniqueConstraint(fields=('graph', 'source'), name='unique_graph_conditional_edge_source'),
        ),
        migrations.AddConstraint(
            model_name='crewnode',
            constraint=models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_crew_node'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('graph', 'start_key', 'end_key'), name='unique_graph_edge'),
        ),
        migrations.AddConstraint(
            model_name='llmnode',
            constraint=models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_llm_node'),
        ),
        migrations.AddConstraint(
            model_name='pythonnode',
            constraint=models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_python_node'),
        ),
        migrations.AddConstraint(
            model_name='startnode',
            constraint=models.UniqueConstraint(fields=('graph',), name='unique_graph_start_node'),
        ),
        migrations.AlterField(
            model_name='session',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.graph'),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.llmmodel'),
        ),
        migrations.AlterField(
            model_name='llmnode',
            name='llm_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.llmconfig'),
        ),
        migrations.AlterField(
            model_name='pythoncodetool',
            name='python_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncode'),
        ),
        migrations.AlterField(
            model_name='pythonnode',
            name='python_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncode'),
        ),
        migrations.CreateModel(
            name='ConditionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_type', models.CharField(max_length=255)),
                ('expression', models.CharField(default=None, max_length=255, null=True)),
                ('manipulation', models.CharField(default=None, max_length=255, null=True)),
                ('next_node', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('condition_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='tables.conditiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTableNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('default_next_node', models.CharField(default=None, max_length=255, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_table_node_list', to='tables.graph')),
            ],
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='decision_table_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_groups', to='tables.decisiontablenode'),
        ),
        migrations.AddConstraint(
            model_name='decisiontablenode',
            constraint=models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_decision_table_node'),
        ),
        migrations.AddConstraint(
            model_name='conditiongroup',
            constraint=models.UniqueConstraint(fields=('decision_table_node', 'group_name'), name='unique_decision_table_node_group_name'),
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_name',
            field=models.CharField(max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(max_length=5000),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(fields=('condition_group', 'condition_name'), name='unique_condition_group_condition_name'),
        ),
    ]
