# Generated by Django 5.1.14 on 2026-10-08 15:12

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import tables.models.base_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tables', '0092_alter_condition_options_alter_conditiongroup_options_and_more'), ('tables', '0093_decisiontablenode_next_error_node'), ('tables', '0094_remove_defaultcrewconfig_planning_llm_config_and_more'), ('tables', '0095_crew_memory_llm_config_and_more'), ('tables', '0096_auto_20250625_1508'), ('tables', '0096_alter_defaulttoolconfig_embedding_config_and_more'), ('tables', '0097_merge_20250627_1333'), ('tables', '0092_graphsessionmessage_uuid'), ('tables', '0093_auto_20250604_1050'), ('tables', '0094_alter_graphsessionmessage_uuid'), ('tables', '0095_merge_20250606_0907'), ('tables', '0096_merge_20250619_1258'), ('tables', '0098_merge_20250630_0911'), ('tables', '0097_graph_persistent_variables'), ('tables', '0099_merge_20250702_1326'), ('tables', '0100_alter_graph_persistent_variables'), ('tables', '0098_taskconfiguredtools_delete_tasktools'), ('tables', '0099_rename_python_code_tool_taskpythoncodetools_tool_and_more'), ('tables', '0101_merge_20250707_1532'), ('tables', '0102_alter_graphsessionmessage_created_at'), ('tables', '0103_alter_documentmetadata_and_sourcecollection_status'), ('tables', '0104_agent_distance_threshold_agent_search_limit_and_more'), ('tables', '0105_add_sourcecollection_unique_name_per_user'), ('tables', '0106_alter_defaultagentconfig_cache_and_more'), ('tables', '0107_remove_agent_distance_threshold_and_more'), ('tables', '0108_alter_session_graph'), ('tables', '0109_endnode'), ('tables', '0110_fileextractornode'), ('tables', '0108_alter_realtimeconfig_api_key_and_more'), ('tables', '0111_merge_20250919_1036'), ('tables', '0111_alter_tool_enabled'), ('tables', '0112_merge_20250922_1355'), ('tables', '0109_mcptool_remove_agent_configured_tools_and_more'), ('tables', '0113_merge_20250924_1501'), ('tables', '0114_mcptool_name_alter_agentconfiguredtools_agent_and_more'), ('tables', '0115_organization_session_organization_organizationuser_and_more'), ('tables', '0116_organization_persistent_variables_and_more'), ('tables', '0115_task_knowledge_query'), ('tables', '0117_merge_20251022_1310'), ('tables', '0115_remove_documentembedding_chunk_text_and_more'), ('tables', '0116_documentembedding_chunk_alter_session_status'), ('tables', '0118_merge_20251027_1034'), ('tables', '0117_embeddingmodel_is_custom_llmmodel_is_custom_and_more'), ('tables', '0119_merge_20251028_1126'), ('tables', '0117_pythoncodetool_built_in'), ('tables', '0120_merge_20251029_1254'), ('tables', '0117_graphorganization_graphorganizationuser_and_more'), ('tables', '0118_graphorganization_user_variables_session_graph_user'), ('tables', '0121_merge_20251029_1556'), ('tables', '0122_alter_organizationuser_name'), ('tables', '0115_remove_decisiontablenode_input_map_and_more'), ('tables', '0123_merge_20251105_1126'), ('tables', '0120_webhooktrigger_session_entrypoint_webhooktriggernode'), ('tables', '0124_merge_20251111_1234'), ('tables', '0125_alter_webhooktriggernode_node_name_and_more'), ('tables', '0126_alter_webhooktriggernode_graph'), ('tables', '0127_fix_graphsessionmessage_cascade'), ('tables', '0128_pythoncodetoolconfig_agentpythoncodetoolconfigs_and_more'), ('tables', '0115_graphfile'), ('tables', '0116_audiotranscriptionnode'), ('tables', '0121_merge_20251029_1725'), ('tables', '0123_merge_20251031_1745'), ('tables', '0129_merge_20251229_1542'), ('tables', '0130_extract_knowledge_data'), ('tables', '0131_prepare_knowledge_refactor'), ('tables', '0132_knowledge_refactor'), ('tables', '0133_restore_knowledge_data'), ('tables', '0128_telegramtriggernode_telegramtriggernodefield_and_more'), ('tables', '0130_merge_20260105_1819'), ('tables', '0134_merge_20260122_1025'), ('tables', '0135_session_token_usage'), ('tables', '0130_realtimeagentchat_input_audio_format_and_more'), ('tables', '0136_merge_20260126_1313'), ('tables', '0130_remove_defaultllmconfig_api_version_and_more'), ('tables', '0137_merge_20260128_1859'), ('tables', '0138_embeddingmodeltag_llmconfigtag_llmmodeltag_and_more'), ('tables', '0139_alter_embeddingmodel_unique_together_and_more'), ('tables', '0135_remove_llmconfig_n'), ('tables', '0136_remove_defaultllmconfig_max_completion_tokens_and_more'), ('tables', '0137_alter_defaultllmconfig_max_tokens'), ('tables', '0140_merge_20260213_1637'), ('tables', '0141_alter_llmconfig_frequency_penalty_and_more'), ('tables', '0137_sessionwarningmessage'), ('tables', '0142_merge_feature_llm_models'), ('tables', '0121_subgraphnode'), ('tables', '0123_merge_20251030_1636'), ('tables', '0129_merge_20251211_1413'), ('tables', '0137_merge_20260202_1622'), ('tables', '0138_merge_20260216_1249'), ('tables', '0143_merge_20260217_1353'), ('tables', '0139_metadata_hash_created_at_updated_at_fields'), ('tables', '0144_merge_add_meta_fields'), ('tables', '0145_add_psql_sequence'), ('tables', '0146_alter_audiotranscriptionnode_id_alter_crewnode_id_and_more'), ('tables', '0137_add_preview_chunk'), ('tables', '0138_add_chunk_overlap_start_end_index'), ('tables', '0139_merge_chunk_preview_migrations'), ('tables', '0147_merge_chunk_preview_migrations_2'), ('tables', '0148_graph_created_at_graph_updated_at'), ('tables', '0149_ngrokwebhookconfig_and_more')]

    dependencies = [
        ('tables', '0091_merge_20250602_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='conditiongroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tool',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DefaultRealtimeAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_limit', models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge')),
                ('distance_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.65, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3)),
                ('wake_word', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_prompt', models.CharField(blank=True, default='stop', max_length=255, null=True)),
                ('language', models.CharField(blank=True, help_text='ISO-639-1 format', max_length=2, null=True)),
                ('voice_recognition_prompt', models.TextField(blank=True, help_text="The prompt to use for the transcription, to guide the model (e.g. 'Expect words related to technology')", null=True)),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('sage', 'Sage'), ('shimmer', 'Shimmer'), ('verse', 'Verse')], default='alloy', max_length=20)),
                ('realtime_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeconfig')),
                ('realtime_transcription_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimetranscriptionconfig')),
            ],
            options={
                'db_table': 'default_realtime_agent_config',
            },
        ),
        migrations.AddField(
            model_name='crew',
            name='memory_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_llm_config', to='tables.llmconfig'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='planning_llm_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_llm_config', to='tables.llmconfig'),
        ),
        migrations.AddField(
            model_name='condition',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='next_error_node',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='defaultcrewconfig',
            name='planning_llm_config',
        ),
        migrations.AddField(
            model_name='defaultcrewconfig',
            name='process',
            field=models.CharField(choices=[('sequential', 'Sequential'), ('hierarchical', 'Hierarchical')], default='sequential', max_length=255),
        ),
        migrations.CreateModel(
            name='DefaultToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_tool_embedding_config', to='tables.embeddingconfig')),
                ('llm_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_tool_llm_config', to='tables.llmconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graphsessionmessage',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='persistent_variables',
            field=models.BooleanField(default=False, help_text="If 'True' -> use variables from last session."),
        ),
        migrations.CreateModel(
            name='TaskConfiguredTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_configured_tool_list', to='tables.task')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.toolconfig')),
            ],
            options={
                'unique_together': {('task', 'tool')},
            },
        ),
        migrations.DeleteModel(
            name='TaskTools',
        ),
        migrations.RenameField(
            model_name='taskpythoncodetools',
            old_name='python_code_tool',
            new_name='tool',
        ),
        migrations.AlterUniqueTogether(
            name='taskpythoncodetools',
            unique_together={('task', 'tool')},
        ),
        migrations.AlterField(
            model_name='graphsessionmessage',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='documentmetadata',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcecollection',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='distance_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.7, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='agent',
            name='search_limit',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge'),
        ),
        migrations.AddField(
            model_name='crew',
            name='distance_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.7, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='crew',
            name='search_limit',
            field=models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge'),
        ),
        migrations.AlterField(
            model_name='session',
            name='graph_schema',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='sourcecollection',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='sourcecollection',
            constraint=models.UniqueConstraint(fields=('user_id', 'collection_name'), name='unique_collection_name_per_user'),
        ),
        migrations.AlterField(
            model_name='defaultcrewconfig',
            name='cache',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='agent',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='defaultrealtimeagentconfig',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='realtimeagent',
            name='distance_threshold',
        ),
        migrations.RemoveField(
            model_name='realtimeagentchat',
            name='distance_threshold',
        ),
        migrations.AddField(
            model_name='agent',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='crew',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='defaultrealtimeagentconfig',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='realtimeagent',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AddField(
            model_name='realtimeagentchat',
            name='similarity_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.graph'),
        ),
        migrations.CreateModel(
            name='EndNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_map', models.JSONField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='tables.graph')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph',), name='unique_graph_end_node')],
            },
        ),
        migrations.CreateModel(
            name='FileExtractorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_extractor_node_list', to='tables.graph')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_file_extractor_node')],
            },
        ),
        migrations.AlterField(
            model_name='realtimeconfig',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtimetranscriptionconfig',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='McpTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(help_text='URL of the remote MCP server (SSE). Required.', max_length=2048)),
                ('tool_name', models.CharField(help_text='Name of the MCP tool.', max_length=255)),
                ('timeout', models.FloatField(default=30, help_text='Request timeout in seconds. Recommended to set.')),
                ('auth', models.TextField(blank=True, help_text='Authorization token or OAuth string, if the server requires it.', null=True)),
                ('init_timeout', models.FloatField(default=10, help_text='Timeout for session initialization. Optional, default is 10 seconds.')),
                ('name', models.CharField(default='Test', help_text='Unique name for mcp configuration', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'MCP Tool Data',
                'verbose_name_plural': 'MCP Tool Data',
            },
        ),
        migrations.CreateModel(
            name='AgentMcpTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tools', to='tables.agent')),
                ('mcptool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.mcptool')),
            ],
            options={
                'db_table': 'tables_agent_mcp_tools_m2m',
                'unique_together': {('agent_id', 'mcptool_id')},
            },
        ),
        migrations.CreateModel(
            name='TaskMcpTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_mcp_tool_list', to='tables.task')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.mcptool')),
            ],
            options={
                'db_table': 'tables_task_mcp_tools',
                'unique_together': {('task', 'tool')},
            },
        ),
        migrations.AlterField(
            model_name='defaultagentconfig',
            name='cache',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='agent',
            name='configured_tools',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='python_code_tools',
        ),
        migrations.CreateModel(
            name='AgentConfiguredTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_tools', to='tables.agent')),
                ('toolconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.toolconfig')),
            ],
            options={
                'db_table': 'tables_agent_configured_tools_m2m',
                'unique_together': {('agent_id', 'toolconfig_id')},
            },
        ),
        migrations.CreateModel(
            name='AgentPythonCodeTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='python_code_tools', to='tables.agent')),
                ('pythoncodetool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncodetool')),
            ],
            options={
                'db_table': 'tables_agent_python_code_tools_m2m',
                'unique_together': {('agent_id', 'pythoncodetool_id')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('secret_key', models.CharField(help_text='A hashed unique key for organization', max_length=512, unique=True)),
                ('variables', models.JSONField(default=dict, help_text='Organization global variables')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('secret_key', models.CharField(help_text='A hashed unique key for user inside an organization', max_length=512, unique=True)),
                ('variables', models.JSONField(default=dict, help_text='User scope variables')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.organization')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='organization_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.organizationuser'),
        ),
        migrations.AddConstraint(
            model_name='organizationuser',
            constraint=models.UniqueConstraint(fields=('username', 'organization'), name='unique_flow_user_for_organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='persistent_variables',
            field=models.BooleanField(default=False, help_text="If 'True' -> variables will be updated after each session."),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='persistent_variables',
            field=models.BooleanField(default=False, help_text="If 'True' -> variables will be updated after each session."),
        ),
        migrations.AddField(
            model_name='task',
            name='knowledge_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='documentembedding',
            name='chunk_text',
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='document_hash',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='documentmetadata',
            name='source_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_metadata', to='tables.sourcecollection'),
        ),
        migrations.AlterField(
            model_name='documentmetadata',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('chunked', 'Chunked'), ('processing', 'Processing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='sourcecollection',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('chunked', 'Chunked'), ('processing', 'Processing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.documentmetadata')),
            ],
        ),
        migrations.AddField(
            model_name='documentembedding',
            name='chunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embeddings_chunk', to='tables.chunk'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('run', 'Run'), ('wait_for_user', 'Wait For User'), ('error', 'Error'), ('end', 'End'), ('stop', 'Stop'), ('expired', 'Expired')], max_length=255),
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realtimemodel',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realtimetranscriptionmodel',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='built_in',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GraphOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persistent_variables', models.JSONField(default=dict, help_text='Variables that persistent for specific entity for specific flow')),
            ],
        ),
        migrations.CreateModel(
            name='GraphOrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persistent_variables', models.JSONField(default=dict, help_text='Variables that persistent for specific entity for specific flow')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='organizationuser',
            name='unique_flow_user_for_organization',
        ),
        migrations.RenameField(
            model_name='organizationuser',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='persistent_variables',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='persistent_variables',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='secret_key',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='variables',
        ),
        migrations.RemoveField(
            model_name='session',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='session',
            name='organization_user',
        ),
        migrations.AddConstraint(
            model_name='organizationuser',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_flow_user_for_organization'),
        ),
        migrations.AddField(
            model_name='graphorganization',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.graph'),
        ),
        migrations.AddField(
            model_name='graphorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='tables.organization'),
        ),
        migrations.AddField(
            model_name='graphorganizationuser',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.graph'),
        ),
        migrations.AddField(
            model_name='graphorganizationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='tables.organizationuser'),
        ),
        migrations.AddConstraint(
            model_name='graphorganization',
            constraint=models.UniqueConstraint(fields=('graph', 'organization'), name='unique_organization_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='graphorganizationuser',
            constraint=models.UniqueConstraint(fields=('graph', 'user'), name='unique_user_per_flow'),
        ),
        migrations.AddField(
            model_name='graphorganization',
            name='user_variables',
            field=models.JSONField(default=dict, help_text='Variables that persistent for all users for specific flow'),
        ),
        migrations.AddField(
            model_name='session',
            name='graph_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.graphorganizationuser'),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.RemoveField(
            model_name='decisiontablenode',
            name='input_map',
        ),
        migrations.RemoveField(
            model_name='decisiontablenode',
            name='output_variable_path',
        ),
        migrations.CreateModel(
            name='WebhookTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Path may only contain letters, numbers, hyphens, and underscores, and must start with a letter or number.', regex='^[a-zA-Z0-9]{1}[a-zA-Z0-9-_]*$')])),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='entrypoint',
            field=models.CharField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='WebhookTriggerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_trigger_node_list', to='tables.graph')),
                ('python_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncode')),
                ('webhook_trigger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_trigger_nodes', to='tables.webhooktrigger')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_webhook_nodes')],
            },
        ),
        migrations.RunSQL(
            sql='\n            ALTER TABLE tables_graphsessionmessage \n            DROP CONSTRAINT IF EXISTS tables_graphsessionm_session_id_f9dff386_fk_tables_se;\n\n            -- Create a new constraint with native ON DELETE CASCADE\n            ALTER TABLE tables_graphsessionmessage \n            ADD CONSTRAINT tables_graphsessionm_session_id_f9dff386_fk_tables_se \n            FOREIGN KEY (session_id) \n            REFERENCES tables_session(id) \n            ON DELETE CASCADE;\n            ',
            reverse_sql='\n            -- Revert to the standard constraint (NO ACTION/RESTRICT) if migration is unapplied\n            ALTER TABLE tables_graphsessionmessage \n            DROP CONSTRAINT IF EXISTS tables_graphsessionm_session_id_f9dff386_fk_tables_se;\n\n            ALTER TABLE tables_graphsessionmessage \n            ADD CONSTRAINT tables_graphsessionm_session_id_f9dff386_fk_tables_se \n            FOREIGN KEY (session_id) \n            REFERENCES tables_session(id) \n            DEFERRABLE INITIALLY DEFERRED;\n            ',
        ),
        migrations.CreateModel(
            name='PythonCodeToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('configuration', models.JSONField(default=dict)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncodetool')),
            ],
            options={
                'unique_together': {('tool', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PythonCodeToolConfigField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('llm_config', 'Llm Config'), ('embedding_config', 'Embedding Config'), ('string', 'String'), ('boolean', 'Boolean'), ('any', 'Any'), ('integer', 'Integer'), ('float', 'Float')], default='string', max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('secret', models.BooleanField(default=False)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_fields', to='tables.pythoncodetool')),
            ],
            options={
                'unique_together': {('tool', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TaskPythonCodeToolConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_python_code_tool_config_list', to='tables.task')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncodetoolconfig')),
            ],
            options={
                'unique_together': {('task', 'tool')},
            },
        ),
        migrations.CreateModel(
            name='GraphFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_key', models.CharField(help_text='Key to access file from domain', max_length=100)),
                ('name', models.CharField(help_text='Original filename', max_length=255)),
                ('content_type', models.CharField(help_text='MIME type', max_length=100)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='tables.graph')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph', 'domain_key'), name='unique_file_key_per_graph')],
            },
        ),
        migrations.CreateModel(
            name='AudioTranscriptionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_transcription_node_list', to='tables.graph')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_audio_transcriotion_node')],
            },
        ),
        migrations.CreateModel(
            name='AgentPythonCodeToolConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='python_code_tool_configs', to='tables.agent')),
                ('pythoncodetoolconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.pythoncodetoolconfig')),
            ],
            options={
                'unique_together': {('agent_id', 'pythoncodetoolconfig_id')},
            },
        ),
        migrations.RemoveField(
            model_name='documentembedding',
            name='chunk',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='document_content',
        ),
        migrations.RemoveField(
            model_name='documentembedding',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='documentembedding',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='source_collection',
        ),
        migrations.RemoveField(
            model_name='sourcecollection',
            name='embedder',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='knowledge_collection',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='knowledge_collection',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='search_limit',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='similarity_threshold',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='search_limit',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='similarity_threshold',
        ),
        migrations.RemoveField(
            model_name='defaultrealtimeagentconfig',
            name='search_limit',
        ),
        migrations.RemoveField(
            model_name='defaultrealtimeagentconfig',
            name='similarity_threshold',
        ),
        migrations.RemoveField(
            model_name='realtimeagent',
            name='search_limit',
        ),
        migrations.RemoveField(
            model_name='realtimeagent',
            name='similarity_threshold',
        ),
        migrations.RemoveField(
            model_name='realtimeagentchat',
            name='search_limit',
        ),
        migrations.RemoveField(
            model_name='realtimeagentchat',
            name='similarity_threshold',
        ),
        migrations.DeleteModel(
            name='Chunk',
        ),
        migrations.DeleteModel(
            name='DocumentContent',
        ),
        migrations.DeleteModel(
            name='DocumentEmbedding',
        ),
        migrations.DeleteModel(
            name='DocumentMetadata',
        ),
        migrations.DeleteModel(
            name='SourceCollection',
        ),
        migrations.CreateModel(
            name='BaseRagType',
            fields=[
                ('rag_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('rag_type', models.CharField(choices=[('naive', 'Naive'), ('graph', 'Graph')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField(help_text='Binary file content (max 12MB)')),
            ],
        ),
        migrations.CreateModel(
            name='AgentNaiveRag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_naive_rags', to='tables.agent', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'Pdf'), ('csv', 'Csv'), ('docx', 'Docx'), ('txt', 'Txt'), ('json', 'Json'), ('html', 'Html'), ('md', 'Md')], max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes', null=True)),
                ('document_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_records', to='tables.documentcontent')),
            ],
        ),
        migrations.CreateModel(
            name='NaiveRag',
            fields=[
                ('naive_rag_id', models.AutoField(primary_key=True, serialize=False)),
                ('rag_status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='new', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('agents', models.ManyToManyField(blank=True, help_text='Agents that have access to this NaiveRag', related_name='naive_rags', through='tables.AgentNaiveRag', to='tables.agent')),
                ('base_rag_type', models.ForeignKey(limit_choices_to={'rag_type': 'naive'}, on_delete=django.db.models.deletion.CASCADE, related_name='naive_rags', to='tables.baseragtype')),
                ('embedder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingconfig')),
            ],
        ),
        migrations.AddField(
            model_name='agentnaiverag',
            name='naive_rag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='tables.naiverag'),
        ),
        migrations.CreateModel(
            name='NaiveRagDocumentConfig',
            fields=[
                ('naive_rag_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_strategy', models.CharField(choices=[('token', 'Token'), ('character', 'Character'), ('markdown', 'Markdown'), ('json', 'Json'), ('html', 'Html'), ('csv', 'Csv')], default='token', max_length=20)),
                ('chunk_size', models.PositiveIntegerField(default=1000, help_text='Size of each chunk (tokens or characters)')),
                ('chunk_overlap', models.PositiveIntegerField(default=150, help_text='Overlap between consecutive chunks')),
                ('additional_params', models.JSONField(default=dict, help_text='Strategy-specific params (e.g., separators, headers)')),
                ('status', models.CharField(choices=[('new', 'New'), ('chunked', 'Chunked'), ('processing', 'Processing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naive_rag_document_config', to='tables.documentmetadata')),
                ('naive_rag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naive_rag_configs', to='tables.naiverag')),
            ],
        ),
        migrations.CreateModel(
            name='NaiveRagChunk',
            fields=[
                ('chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField(help_text='Order of this chunk in the document')),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Chunk-specific metadata (page numbers, sections, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('naive_rag_document_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tables.naiveragdocumentconfig')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='NaiveRagEmbedding',
            fields=[
                ('embedding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='tables.naiveragchunk')),
                ('naive_rag_document_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='tables.naiveragdocumentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='NaiveRagSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_limit', models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge')),
                ('similarity_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3)),
                ('agent', models.OneToOneField(help_text='Agent this search configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='naive_search_config', to='tables.agent')),
            ],
        ),
        migrations.CreateModel(
            name='SourceCollection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('collection_origin', models.CharField(choices=[('user', 'User'), ('node', 'Node'), ('tool', 'Tool')], default='user', max_length=20)),
                ('user_id', models.CharField(blank=True, default='dummy_user', max_length=120)),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('warning', 'Warning')], default='empty', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'collection_name'), name='unique_collection_name_per_user')],
            },
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='source_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tables.sourcecollection'),
        ),
        migrations.AddField(
            model_name='baseragtype',
            name='source_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_types', to='tables.sourcecollection'),
        ),
        migrations.AddField(
            model_name='agent',
            name='knowledge_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.sourcecollection'),
        ),
        migrations.AddIndex(
            model_name='naiveragdocumentconfig',
            index=models.Index(fields=['naive_rag', 'status'], name='tables_naiv_naive_r_f3bcf6_idx'),
        ),
        migrations.AddIndex(
            model_name='naiveragdocumentconfig',
            index=models.Index(fields=['document'], name='tables_naiv_documen_254ff9_idx'),
        ),
        migrations.AddConstraint(
            model_name='naiveragdocumentconfig',
            constraint=models.UniqueConstraint(fields=('naive_rag', 'document'), name='unique_document_per_naive_rag'),
        ),
        migrations.AddIndex(
            model_name='naiveragchunk',
            index=models.Index(fields=['naive_rag_document_config', 'chunk_index'], name='tables_naiv_naive_r_343843_idx'),
        ),
        migrations.AddConstraint(
            model_name='naiveragchunk',
            constraint=models.UniqueConstraint(fields=('naive_rag_document_config', 'chunk_index'), name='unique_chunk_index_per_naive_rag_document_config'),
        ),
        migrations.AddIndex(
            model_name='naiveragembedding',
            index=models.Index(fields=['naive_rag_document_config'], name='tables_naiv_naive_r_e7ad19_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmetadata',
            index=models.Index(fields=['source_collection'], name='tables_docu_source__eec4f1_idx'),
        ),
        migrations.CreateModel(
            name='TelegramTriggerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255)),
                ('telegram_bot_api_key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('url_path', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_trigger_node_list', to='tables.graph')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramTriggerNodeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=255)),
                ('variable_path', models.CharField(max_length=255)),
                ('telegram_trigger_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tables.telegramtriggernode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='telegramtriggernode',
            constraint=models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_telegram_trigger_nodes'),
        ),
        migrations.AddConstraint(
            model_name='telegramtriggernodefield',
            constraint=models.UniqueConstraint(fields=('telegram_trigger_node', 'field_name', 'parent'), name='unique_telegram_trigger_node_field_name_parent'),
        ),
        migrations.AddField(
            model_name='realtimeagentchat',
            name='output_audio_format',
            field=models.CharField(choices=[('pcm16', 'PCM 16-bit'), ('g711_ulaw', 'G.711 u-law'), ('g711_alaw', 'G.711 a-law')], default='pcm16', max_length=20),
        ),
        migrations.RemoveField(
            model_name='defaultllmconfig',
            name='api_version',
        ),
        migrations.RemoveField(
            model_name='defaultllmconfig',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='defaultllmconfig',
            name='logprobs',
        ),
        migrations.RemoveField(
            model_name='defaultllmconfig',
            name='top_logprobs',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='api_version',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='logprobs',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='top_logprobs',
        ),
        migrations.RemoveField(
            model_name='llmmodel',
            name='deployment',
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='extra_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='defaultllmconfig',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='extra_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='api_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmbeddingModelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predefined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMConfigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predefined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LLMModelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predefined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='agenttag',
            old_name='predifined',
            new_name='predefined',
        ),
        migrations.RenameField(
            model_name='crewtag',
            old_name='predifined',
            new_name='predefined',
        ),
        migrations.RenameField(
            model_name='graphtag',
            old_name='predifined',
            new_name='predefined',
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='deployment_id',
            field=models.TextField(blank=True, help_text='Azure Deployment Name or Watsonx ID', null=True),
        ),
        migrations.AddField(
            model_name='embeddingmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='embedding_models', to='tables.embeddingmodeltag'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='llm_models', to='tables.llmmodeltag'),
        ),
        migrations.AddField(
            model_name='session',
            name='token_usage',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='embeddingmodel',
            unique_together={('name', 'embedding_provider')},
        ),
        migrations.AlterUniqueTogether(
            name='llmmodel',
            unique_together={('name', 'llm_provider')},
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='n',
        ),
        migrations.RemoveField(
            model_name='defaultllmconfig',
            name='max_completion_tokens',
        ),
        migrations.RemoveField(
            model_name='defaultllmconfig',
            name='n',
        ),
        migrations.RemoveField(
            model_name='llmconfig',
            name='max_completion_tokens',
        ),
        migrations.AddField(
            model_name='realtimeagentchat',
            name='input_audio_format',
            field=models.CharField(choices=[('pcm16', 'PCM 16-bit'), ('g711_ulaw', 'G.711 u-law'), ('g711_alaw', 'G.711 a-law')], default='pcm16', max_length=20),
        ),
        migrations.AlterField(
            model_name='defaultllmconfig',
            name='max_tokens',
            field=models.IntegerField(blank=True, default=4096, null=True, validators=[django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='frequency_penalty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='max_tokens',
            field=models.IntegerField(blank=True, default=4096, null=True, validators=[django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='presence_penalty',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='seed',
            field=models.IntegerField(blank=True, default=42, null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='temperature',
            field=models.FloatField(blank=True, default=0.5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='timeout',
            field=models.FloatField(blank=True, default=120.0, null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='top_p',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.CreateModel(
            name='SessionWarningMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='tables.session')),
            ],
        ),
        migrations.AddField(
            model_name='audiotranscriptionnode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='audiotranscriptionnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiotranscriptionnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='crewnode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='crewnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crewnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='endnode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='endnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fileextractornode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fileextractornode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileextractornode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='llmnode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='llmnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='startnode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='startnode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telegramtriggernode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='telegramtriggernode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramtriggernode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webhooktriggernode',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='webhooktriggernode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhooktriggernode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='content_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audiotranscriptionnode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='crewnode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='edge',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='endnode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fileextractornode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='llmnode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startnode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SubGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgraph_node_list', to='tables.graph')),
                ('subgraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_subgraph', to='tables.graph')),
                ('content_hash', models.CharField(editable=False, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_subgraph_node')],
            },
        ),
        migrations.AddField(
            model_name='telegramtriggernode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webhooktriggernode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunSQL(
            sql='\n            -- 0) Create the shared sequence\n            CREATE SEQUENCE IF NOT EXISTS tables_global_node_seq;\n\n            DO $$\n            DECLARE\n              t regclass;\n              fk record;\n              mapping_table text;\n              max_id bigint;\n              child_tables text[];\n              ct_name text;\n            BEGIN\n              -- 1) List of tables\n              FOREACH t IN ARRAY ARRAY[\n                \'tables_crewnode\'::regclass,\n                \'tables_pythonnode\'::regclass,\n                \'tables_fileextractornode\'::regclass,\n                \'tables_audiotranscriptionnode\'::regclass,\n                \'tables_llmnode\'::regclass,\n                \'tables_endnode\'::regclass,\n                \'tables_subgraphnode\'::regclass,\n                \'tables_startnode\'::regclass,\n                \'tables_decisiontablenode\'::regclass,\n                \'tables_webhooktriggernode\'::regclass,\n                \'tables_telegramtriggernode\'::regclass\n              ]\n              LOOP\n                child_tables := ARRAY[]::text[];\n\n                -- 2) Lock the table\n                EXECUTE format(\'LOCK TABLE %s IN ACCESS EXCLUSIVE MODE\', t);\n\n                -- [MOVED UP] 3) Clean up table structure BEFORE data updates.\n                -- This prevents "pending trigger events" errors because no updates have happened yet.\n                EXECUTE format(\'ALTER TABLE %s ALTER COLUMN id DROP IDENTITY IF EXISTS\', t);\n                EXECUTE format(\'ALTER TABLE %s ALTER COLUMN id DROP DEFAULT\', t);\n\n                -- 4) Create mapping table\n                mapping_table := format(\'tmp_map_%s\', replace(t::text, \'.\', \'_\'));\n                EXECUTE format(\'DROP TABLE IF EXISTS %I\', mapping_table);\n                EXECUTE format(\n                  \'CREATE TEMP TABLE %I (old_id bigint PRIMARY KEY, new_id bigint UNIQUE) ON COMMIT DROP\',\n                  mapping_table\n                );\n\n                -- Fill mapping\n                EXECUTE format(\n                  \'INSERT INTO %I (old_id, new_id)\n                   SELECT id, nextval(\'\'tables_global_node_seq\'\')\n                   FROM %s\n                   ORDER BY id\',\n                  mapping_table, t\n                );\n\n                -- 5) Update Foreign Keys\n                FOR fk IN\n                  SELECT\n                    con.oid as con_oid,\n                    rel_src.oid as src_relid,\n                    rel_src.relname as src_table,\n                    ns_src.nspname as src_schema,\n                    att_src.attname as src_col\n                  FROM pg_constraint con\n                  JOIN pg_class rel_tgt ON rel_tgt.oid = con.confrelid\n                  JOIN pg_namespace ns_tgt ON ns_tgt.oid = rel_tgt.relnamespace\n                  JOIN pg_class rel_src ON rel_src.oid = con.conrelid\n                  JOIN pg_namespace ns_src ON ns_src.oid = rel_src.relnamespace\n                  JOIN pg_attribute att_src\n                    ON att_src.attrelid = rel_src.oid\n                   AND att_src.attnum = con.conkey[1]\n                  WHERE con.contype = \'f\'\n                    AND con.confrelid = t\n                    AND con.confkey = ARRAY[\n                      (SELECT attnum FROM pg_attribute WHERE attrelid = t AND attname = \'id\' AND NOT attisdropped)\n                    ]\n                LOOP\n                  EXECUTE format(\'LOCK TABLE %I.%I IN ACCESS EXCLUSIVE MODE\', fk.src_schema, fk.src_table);\n                  EXECUTE format(\'ALTER TABLE %I.%I DISABLE TRIGGER ALL\', fk.src_schema, fk.src_table);\n                  child_tables := array_append(child_tables, format(\'%I.%I\', fk.src_schema, fk.src_table));\n\n                  EXECUTE format(\n                    \'UPDATE %I.%I s\n                     SET %I = m.new_id\n                     FROM %I m\n                     WHERE s.%I = m.old_id\',\n                    fk.src_schema, fk.src_table,\n                    fk.src_col,\n                    mapping_table,\n                    fk.src_col\n                  );\n                END LOOP;\n\n                -- 6) Update Primary Key\n                EXECUTE format(\n                  \'UPDATE %s tgt\n                   SET id = m.new_id\n                   FROM %I m\n                   WHERE tgt.id = m.old_id\',\n                  t, mapping_table\n                );\n\n                -- 6b) Re-enable triggers on child tables now that PKs hold the new IDs\n                FOREACH ct_name IN ARRAY child_tables\n                LOOP\n                  EXECUTE format(\'ALTER TABLE %s ENABLE TRIGGER ALL\', ct_name);\n                END LOOP;\n\n                -- [ADDED] 7) Force execution of pending trigger checks (Foreign Keys)\n                -- This clears the queue so we can perform the final ALTER TABLE without error.\n                EXECUTE \'SET CONSTRAINTS ALL IMMEDIATE\';\n\n                -- 8) Set new Default\n                EXECUTE format(\n                  \'ALTER TABLE %s ALTER COLUMN id SET DEFAULT nextval(\'\'tables_global_node_seq\'\')\',\n                  t\n                );\n\n              END LOOP;\n\n              -- 9) Sync sequence\n              EXECUTE \'SELECT GREATEST(\n                (SELECT COALESCE(MAX(id), 0) FROM tables_crewnode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_pythonnode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_fileextractornode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_audiotranscriptionnode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_llmnode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_endnode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_subgraphnode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_startnode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_decisiontablenode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_webhooktriggernode),\n                (SELECT COALESCE(MAX(id), 0) FROM tables_telegramtriggernode)\n              )\' INTO max_id;\n              IF max_id < 1 THEN\n                -- If tables are empty, reset sequence so the NEXT value is 1\n                PERFORM setval(\'tables_global_node_seq\', 1, false);\n              ELSE\n                -- If data exists, set sequence to the max_id\n                PERFORM setval(\'tables_global_node_seq\', max_id, true);\n              END IF;\n\n            END $$;\n            ',
            reverse_sql='\n            ALTER TABLE tables_crewnode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_pythonnode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_fileextractornode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_audiotranscriptionnode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_llmnode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_endnode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_subgraphnode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_startnode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_decisiontablenode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_webhooktriggernode ALTER COLUMN id DROP DEFAULT;\n            ALTER TABLE tables_telegramtriggernode ALTER COLUMN id DROP DEFAULT;\n\n            DROP SEQUENCE IF EXISTS tables_global_node_seq;\n            ',
        ),
        migrations.AlterField(
            model_name='audiotranscriptionnode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crewnode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='decisiontablenode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='endnode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fileextractornode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='llmnode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pythonnode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='startnode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subgraphnode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telegramtriggernode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webhooktriggernode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naiveragdocumentconfig',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('chunking', 'Chunking'), ('chunked', 'Chunked'), ('indexing', 'Indexing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='naiveragchunk',
            name='overlap_end_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragchunk',
            name='overlap_start_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NaiveRagPreviewChunk',
            fields=[
                ('preview_chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField(help_text='Order of this chunk in the document')),
                ('token_count', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Chunk-specific metadata (page numbers, sections, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('naive_rag_document_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_chunks', to='tables.naiveragdocumentconfig')),
                ('overlap_end_index', models.PositiveIntegerField(blank=True, null=True)),
                ('overlap_start_index', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['naive_rag_document_config', 'chunk_index'], name='tables_naiv_naive_r_202e85_idx')],
            },
        ),
        migrations.AddField(
            model_name='graph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='NgrokWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('auth_token', models.CharField(help_text='Token from dashboard.ngrok.com', max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Your domain', max_length=255, null=True)),
                ('region', models.CharField(choices=[('us', 'Us'), ('eu', 'Eu'), ('ap', 'Ap')], default='eu', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='telegramtriggernode',
            name='url_path',
        ),
        migrations.AddField(
            model_name='telegramtriggernode',
            name='webhook_trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_trigger_nodes', to='tables.webhooktrigger'),
        ),
        migrations.AlterField(
            model_name='webhooktrigger',
            name='path',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Path may only contain letters, numbers, hyphens, and underscores, and must start with a letter or number.', regex='^[a-zA-Z0-9]{1}[a-zA-Z0-9-_]*$')]),
        ),
        migrations.AddField(
            model_name='webhooktrigger',
            name='ngrok_webhook_config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tables.ngrokwebhookconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='webhooktrigger',
            unique_together={('path', 'ngrok_webhook_config')},
        ),
    ]
