# Generated by Django 5.1.14 on 2026-10-08 15:13

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import tables.models.base_models
import tables.models.knowledge_models.graphrag_models
import tables.models.user
import uuid
from django.conf import settings
from django.db import migrations, models


BUILTIN_ROLES = [
    # name, description, permissions dict {resource_type: bitmask}
    (
        "Superadmin",
        "Display-only role. Access is granted via User.is_superadmin bypass, "
        "so no RolePermission rows are needed.",
        {},
    ),
    (
        "Org Admin",
        "Full control within an organization.",
        {
            "flows": 31,           # C R U D E
            "agents": 15,          # C R U D
            "tools": 15,
            "knowledge_sources": 15,
            "files": 47,           # C R U D dl
            "projects": 15,
            "llm_configs": 15,
            "secrets": 207,        # C R U D use list
            "users": 15,
            "roles": 15,
        },
    ),
    (
        "Member",
        "CRU on most resources, no delete, no user/role management.",
        {
            "flows": 7,            # C R U
            "agents": 7,
            "tools": 7,
            "knowledge_sources": 2,  # R
            "files": 39,             # C R U dl
            "projects": 7,
            "llm_configs": 2,
            "secrets": 192,          # use list
            "users": 0,
            "roles": 0,
        },
    ),
    (
        "Viewer",
        "Read-only across resources; can run flows and use secrets.",
        {
            "flows": 66,             # R use
            "agents": 2,
            "tools": 2,
            "knowledge_sources": 2,
            "files": 2,
            "projects": 2,
            "llm_configs": 2,
            "secrets": 192,          # use list
            "users": 0,
            "roles": 0,
        },
    ),
]


def seed_builtin_roles(apps, schema_editor):
    """Seed the four built-in roles (ported from 0171_seed_builtin_roles)."""
    Role = apps.get_model("tables", "Role")
    RolePermission = apps.get_model("tables", "RolePermission")

    for name, description, perms in BUILTIN_ROLES:
        role, _created = Role.objects.get_or_create(
            name=name,
            is_built_in=True,
            org=None,
            defaults={"description": description},
        )
        for resource_type, bitmask in perms.items():
            RolePermission.objects.update_or_create(
                role=role,
                resource_type=resource_type,
                defaults={"permissions": bitmask},
            )


def unseed_builtin_roles(apps, schema_editor):
    Role = apps.get_model("tables", "Role")
    Role.objects.filter(
        is_built_in=True,
        org__isnull=True,
        name__in=[name for name, _, _ in BUILTIN_ROLES],
    ).delete()  # cascades RolePermission


class Migration(migrations.Migration):

    replaces = [('tables', '0147_notenode'), ('tables', '0148_merge_20260305_2121'), ('tables', '0149_allow_blank_conditional_edge_source'), ('tables', '0150_merge_est_1999'), ('tables', '0147_edge_keys_and_decision_data'), ('tables', '0148_remove_conditionaledge_unique_graph_conditional_edge_source_and_more'), ('tables', '0149_alter_conditiongroup_expression_and_more'), ('tables', '0150_merge_20260306_1326'), ('tables', '0151_merge_est_2006'), ('tables', '0152_alter_conditionaledge_id'), ('tables', '0153_migrate_note_nodes_from_metadata'), ('tables', '0154_remove_unique_node_names'), ('tables', '0151_pythoncode_content_hash'), ('tables', '0155_merge_est_2004'), ('tables', '0156_remove_audiotranscriptionnode_content_hash_and_more'), ('tables', '0150_graph_name_unique'), ('tables', '0157_merge_20260320_1426'), ('tables', '0148_label_graph_labels_label_unique_label_name_per_level_and_more'), ('tables', '0150_merge_20260310_1215'), ('tables', '0155_merge_20260316_2004'), ('tables', '0158_merge_20260320_1826'), ('tables', '0155_graphnote_delete_notenode'), ('tables', '0158_merge_20260320_1738'), ('tables', '0159_merge_20260323_1646'), ('tables', '0153_codeagentnode_streamconfig_epicchat'), ('tables', '0155_merge_epic_chat'), ('tables', '0160_merge_epic_chat_2'), ('tables', '0161_remove_codeagentnode_unique_graph_node_name_for_code_agent_node_and_more'), ('tables', '0162_session_parent_session'), ('tables', '0149_graph_uuid'), ('tables', '0150_populate_graph_uuid'), ('tables', '0151_alter_graph_uuid'), ('tables', '0152_merge_20260310_1429'), ('tables', '0162_merge_20260326_1203'), ('tables', '0163_merge_20260326_1806'), ('tables', '0155_defaultmodels'), ('tables', '0156_llmconfig_tags'), ('tables', '0157_embeddingconfigtag_embeddingconfig_tags'), ('tables', '0158_realtimeconfigtag_realtimetranscriptionconfigtag_and_more'), ('tables', '0162_merge_make_settings_accord_to_req'), ('tables', '0164_merge_20260403_1226'), ('tables', '0159_alter_voice_no_choices'), ('tables', '0164_merge_20260403_1200'), ('tables', '0165_merge_20260403_1649'), ('tables', '0166_alter_llmconfig_seed'), ('tables', '0156_label_metadata'), ('tables', '0164_merge_0156_label_metadata_0163_merge_20260326_1806'), ('tables', '0167_merge_20260410_1240'), ('tables', '0145_classification_decision_table_node'), ('tables', '0146_classificationdecisiontablenode_post_computation_code'), ('tables', '0147_classificationdecisiontablenode_input_maps'), ('tables', '0148_classificationdecisiontablenode_output_variable_paths'), ('tables', '0149_classificationconditiongroup_field_expressions'), ('tables', '0150_classificationconditiongroup_field_manipulations'), ('tables', '0151_classificationdecisiontablenode_expression_errors_as_false'), ('tables', '0164_merge_20260330_1744'), ('tables', '0168_merge_20260411_1540'), ('tables', '0164_delete_graphfile'), ('tables', '0165_codeagentnode_use_storage_pythonnode_use_storage'), ('tables', '0166_storagefile_graphstoragefile_and_more_squashed_0175_merge_20260427_1053'), ('tables', '0169_merge_20260416_1828'), ('tables', '0170_classificationconditiongroup_created_at_and_more'), ('tables', '0171_merge_20260420_1647'), ('tables', '0172_cdt_python_code_fks'), ('tables', '0173_classificationdecisiontablenode_default_llm_config_and_more'), ('tables', '0174_remove_classificationconditiongroup_route_code_and_more'), ('tables', '0175_merge_20260427_1405'), ('tables', '0176_remove_storagefile_storagefile_name_trgm_idx_and_more'), ('tables', '0170_rbac_and_persistent_models'), ('tables', '0171_seed_builtin_roles'), ('tables', '0172_apikey_created_by'), ('tables', '0173_remove_storagefile_storagefile_name_trgm_idx_and_more'), ('tables', '0171_alter_graphversion_deleted_at'), ('tables', '0174_merge_20260429_1147'), ('tables', '0168_pythonnode_test_input'), ('tables', '0169_merge_20260416_1127'), ('tables', '0170_merge_0169_merge_20260416_1127_0169_merge_imp_auth'), ('tables', '0175_merge_20260504_1000'), ('tables', '0177_merge_20260511_1502'), ('tables', '0178_classificationconditiongroup_section'), ('tables', '0175_alter_organization_name_and_more'), ('tables', '0176_merge_organizations_migrations'), ('tables', '0179_merge_demo_migrations'), ('tables', '0176_pythoncodetool_use_storage'), ('tables', '0180_merge_20260514_1302'), ('tables', '0181_flow_assistant'), ('tables', '0182_flow_assistant_org_scoping'), ('tables', '0183_remove_flowassistant_system_prompt_override'), ('tables', '0184_flow_assistant_message'), ('tables', '0176_user_management_migrations'), ('tables', '0177_merge_user_management_migrations'), ('tables', '0178_user_profile_migration'), ('tables', '0178_merge_user_management_migrations_2'), ('tables', '0179_merge_user_profile_migrations'), ('tables', '0175_alter_subgraphnode_subgraph'), ('tables', '0177_merge_20260515_1407'), ('tables', '0180_merge_user_profile_migrations_2'), ('tables', '0185_merge_main_into_demo_migrations')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tables', '0146_alter_audiotranscriptionnode_id_alter_crewnode_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(editable=False, max_length=64, null=True)),
                ('id', models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_node_list', to='tables.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='conditionaledge',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RemoveConstraint(
            model_name='conditionaledge',
            name='unique_graph_conditional_edge_source',
        ),
        migrations.AddConstraint(
            model_name='conditionaledge',
            constraint=models.UniqueConstraint(condition=models.Q(('source', ''), _negated=True), fields=('graph', 'source'), name='unique_graph_conditional_edge_source'),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='default_next_node_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='next_error_node_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='next_node_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='conditionaledge',
            name='then',
        ),
        migrations.AddField(
            model_name='edge',
            name='start_node_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edge',
            name='end_node_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='source_node_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.RemoveConstraint(
            model_name='conditionaledge',
            name='unique_graph_conditional_edge_source',
        ),
        migrations.RemoveConstraint(
            model_name='edge',
            name='unique_graph_edge',
        ),
        migrations.RemoveField(
            model_name='conditionaledge',
            name='source',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='end_key',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='start_key',
        ),
        migrations.RemoveField(
            model_name='decisiontablenode',
            name='default_next_node',
        ),
        migrations.RemoveField(
            model_name='decisiontablenode',
            name='next_error_node',
        ),
        migrations.RemoveField(
            model_name='conditiongroup',
            name='next_node',
        ),
        migrations.AddConstraint(
            model_name='conditionaledge',
            constraint=models.UniqueConstraint(fields=('graph', 'source_node_id'), name='unique_graph_conditional_edge_source'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('graph', 'start_node_id', 'end_node_id'), name='unique_graph_edge'),
        ),
        migrations.AlterField(
            model_name='conditiongroup',
            name='expression',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conditiongroup',
            name='manipulation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.RunSQL(
            sql="\n            DO $$\n            DECLARE\n              t regclass := 'tables_conditionaledge'::regclass;\n              fk record;\n              mapping_table text;\n              max_id bigint;\n            BEGIN\n              -- 1) Lock the table\n              EXECUTE format('LOCK TABLE %s IN ACCESS EXCLUSIVE MODE', t);\n\n              -- 2) Clean up table structure BEFORE data updates.\n              EXECUTE format('ALTER TABLE %s ALTER COLUMN id DROP IDENTITY IF EXISTS', t);\n              EXECUTE format('ALTER TABLE %s ALTER COLUMN id DROP DEFAULT', t);\n\n              -- 3) Create mapping table\n              mapping_table := 'tmp_map_tables_conditionaledge';\n              EXECUTE format('DROP TABLE IF EXISTS %I', mapping_table);\n              EXECUTE format(\n                'CREATE TEMP TABLE %I (old_id bigint PRIMARY KEY, new_id bigint UNIQUE) ON COMMIT DROP',\n                mapping_table\n              );\n\n              -- Fill mapping\n              EXECUTE format(\n                'INSERT INTO %I (old_id, new_id)\n                 SELECT id, nextval(''tables_global_node_seq'')\n                 FROM %s\n                 ORDER BY id',\n                mapping_table, t\n              );\n\n              -- 4) Update Foreign Keys referencing this table\n              FOR fk IN\n                SELECT\n                  con.oid as con_oid,\n                  rel_src.oid as src_relid,\n                  rel_src.relname as src_table,\n                  ns_src.nspname as src_schema,\n                  att_src.attname as src_col\n                FROM pg_constraint con\n                JOIN pg_class rel_tgt ON rel_tgt.oid = con.confrelid\n                JOIN pg_namespace ns_tgt ON ns_tgt.oid = rel_tgt.relnamespace\n                JOIN pg_class rel_src ON rel_src.oid = con.conrelid\n                JOIN pg_namespace ns_src ON ns_src.oid = rel_src.relnamespace\n                JOIN pg_attribute att_src\n                  ON att_src.attrelid = rel_src.oid\n                 AND att_src.attnum = con.conkey[1]\n                WHERE con.contype = 'f'\n                  AND con.confrelid = t\n                  AND con.confkey = ARRAY[\n                    (SELECT attnum FROM pg_attribute WHERE attrelid = t AND attname = 'id' AND NOT attisdropped)\n                  ]\n              LOOP\n                EXECUTE format('LOCK TABLE %I.%I IN ACCESS EXCLUSIVE MODE', fk.src_schema, fk.src_table);\n\n                EXECUTE format(\n                  'UPDATE %I.%I s\n                   SET %I = m.new_id\n                   FROM %I m\n                   WHERE s.%I = m.old_id',\n                  fk.src_schema, fk.src_table,\n                  fk.src_col,\n                  mapping_table,\n                  fk.src_col\n                );\n              END LOOP;\n\n              -- 5) Update Primary Key\n              EXECUTE format(\n                'UPDATE %s tgt\n                 SET id = m.new_id\n                 FROM %I m\n                 WHERE tgt.id = m.old_id',\n                t, mapping_table\n              );\n\n              -- 6) Force execution of pending trigger checks\n              EXECUTE 'SET CONSTRAINTS ALL IMMEDIATE';\n\n              -- 7) Set new Default\n              EXECUTE format(\n                'ALTER TABLE %s ALTER COLUMN id SET DEFAULT nextval(''tables_global_node_seq'')',\n                t\n              );\n\n              -- 8) Sync sequence\n              SELECT COALESCE(MAX(id), 0) INTO max_id FROM tables_conditionaledge;\n              IF max_id >= 1 THEN\n                PERFORM setval('tables_global_node_seq', max_id, true);\n              END IF;\n\n            END $$;\n            ",
            reverse_sql='\n            ALTER TABLE tables_conditionaledge ALTER COLUMN id DROP DEFAULT;\n            ',
        ),
        migrations.AlterField(
            model_name='conditionaledge',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveConstraint(
            model_name='crewnode',
            name='unique_graph_node_name_for_crew_node',
        ),
        migrations.RemoveConstraint(
            model_name='pythonnode',
            name='unique_graph_node_name_for_python_node',
        ),
        migrations.RemoveConstraint(
            model_name='fileextractornode',
            name='unique_graph_node_name_for_file_extractor_node',
        ),
        migrations.RemoveConstraint(
            model_name='audiotranscriptionnode',
            name='unique_graph_node_name_for_audio_transcriotion_node',
        ),
        migrations.RemoveConstraint(
            model_name='llmnode',
            name='unique_graph_node_name_for_llm_node',
        ),
        migrations.RemoveConstraint(
            model_name='subgraphnode',
            name='unique_graph_node_name_for_subgraph_node',
        ),
        migrations.RemoveConstraint(
            model_name='decisiontablenode',
            name='unique_graph_node_name_for_decision_table_node',
        ),
        migrations.RemoveConstraint(
            model_name='webhooktriggernode',
            name='unique_graph_node_name_for_webhook_nodes',
        ),
        migrations.RemoveConstraint(
            model_name='telegramtriggernode',
            name='unique_graph_node_name_for_telegram_trigger_nodes',
        ),
        migrations.RemoveField(
            model_name='conditionaledge',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='crewnode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='decisiontablenode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='endnode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='fileextractornode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='llmnode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='notenode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='pythonnode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='startnode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='subgraphnode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='telegramtriggernode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='webhooktriggernode',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='audiotranscriptionnode',
            name='content_hash',
        ),
        migrations.AlterField(
            model_name='graph',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tables.label')),
            ],
        ),
        migrations.AddField(
            model_name='graph',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='flows', to='tables.label'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_label_name_per_level'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_top_level_label_name'),
        ),
        migrations.RenameModel(
            old_name='NoteNode',
            new_name='GraphNote',
        ),
        migrations.AddField(
            model_name='crewnode',
            name='stream_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='stream_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='graph',
            name='epicchat_enabled',
            field=models.BooleanField(default=False, help_text="If 'True' -> flow is connected to EpicChat widget."),
        ),
        migrations.CreateModel(
            name='CodeAgentNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('agent_mode', models.CharField(default='build', max_length=10)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('stream_handler_code', models.TextField(blank=True, default='')),
                ('libraries', models.JSONField(blank=True, default=list)),
                ('polling_interval_ms', models.IntegerField(default=1000)),
                ('silence_indicator_s', models.IntegerField(default=3)),
                ('indicator_repeat_s', models.IntegerField(default=5)),
                ('chunk_timeout_s', models.IntegerField(default=30)),
                ('inactivity_timeout_s', models.IntegerField(default=120)),
                ('max_wait_s', models.IntegerField(default=300)),
                ('stream_config', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_agent_node_list', to='tables.graph')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmconfig')),
                ('use_storage', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='parent_session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgraph_sessions', to='tables.session'),
        ),
        migrations.AddField(
            model_name='graph',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='graphnote',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_note_list', to='tables.graph'),
        ),
        migrations.CreateModel(
            name='DefaultModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_fcm_llm_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_models_agent_fcm_llm', to='tables.llmconfig')),
                ('agent_llm_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_models_agent_llm', to='tables.llmconfig')),
                ('memory_embedding_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_models_memory_embedding', to='tables.embeddingconfig')),
                ('memory_llm_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_models_memory_llm', to='tables.llmconfig')),
                ('project_manager_llm_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_models_manager_llm', to='tables.llmconfig')),
                ('transcription_llm_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_models_transcription_llm', to='tables.realtimetranscriptionconfig')),
                ('voice_llm_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_models_voice_llm', to='tables.realtimeconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='llm_configs', to='tables.llmconfigtag'),
        ),
        migrations.CreateModel(
            name='EmbeddingConfigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predefined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='embeddingconfig',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='embedding_configs', to='tables.embeddingconfigtag'),
        ),
        migrations.CreateModel(
            name='RealtimeConfigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predefined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RealtimeTranscriptionConfigTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('predefined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='realtimeconfig',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='realtime_configs', to='tables.realtimeconfigtag'),
        ),
        migrations.AddField(
            model_name='realtimetranscriptionconfig',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='realtime_transcription_configs', to='tables.realtimetranscriptionconfigtag'),
        ),
        migrations.AlterField(
            model_name='realtimeagent',
            name='voice',
            field=models.CharField(default='alloy', max_length=100),
        ),
        migrations.AlterField(
            model_name='realtimeagentchat',
            name='voice',
            field=models.CharField(default='alloy', max_length=100),
        ),
        migrations.AlterField(
            model_name='defaultrealtimeagentconfig',
            name='voice',
            field=models.CharField(default='alloy', max_length=100),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='seed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(blank=True, default='', max_length=255)),
                ('twilio_auth_token', models.CharField(blank=True, default='', max_length=255)),
                ('voice_agent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeagent')),
                ('ngrok_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.ngrokwebhookconfig')),
            ],
            options={
                'db_table': 'voice_settings',
            },
        ),
        migrations.AddField(
            model_name='label',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ClassificationDecisionTableNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('pre_computation_code', models.TextField(blank=True, default=None, null=True)),
                ('prompts', models.JSONField(blank=True, default=dict)),
                ('route_variable_name', models.CharField(default='route_code', max_length=255)),
                ('default_next_node', models.CharField(default=None, max_length=255, null=True)),
                ('next_error_node', models.CharField(default=None, max_length=255, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_decision_table_node_list', to='tables.graph')),
                ('post_computation_code', models.TextField(blank=True, default=None, null=True)),
                ('pre_input_map', models.JSONField(blank=True, default=dict)),
                ('post_input_map', models.JSONField(blank=True, default=dict)),
                ('pre_output_variable_path', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('post_output_variable_path', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('expression_errors_as_false', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('graph', 'node_name'), name='unique_graph_node_name_for_classification_dt_node')],
            },
        ),
        migrations.CreateModel(
            name='ClassificationConditionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('expression', models.TextField(blank=True, default=None, null=True)),
                ('prompt_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('manipulation', models.TextField(blank=True, default=None, null=True)),
                ('continue_flag', models.BooleanField(default=False)),
                ('route_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dock_visible', models.BooleanField(default=True)),
                ('classification_decision_table_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_groups', to='tables.classificationdecisiontablenode')),
                ('field_expressions', models.JSONField(blank=True, default=dict)),
                ('field_manipulations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='GraphFile',
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='use_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Org-relative path, never starts with '/'", max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='tables.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GraphStorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='tables.graph')),
                ('storage_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_storage_files', to='tables.storagefile')),
            ],
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['org', 'path'], name='tables_stor_org_id_f9ae19_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagefile',
            constraint=models.UniqueConstraint(fields=('org', 'path'), name='unique_storage_file_per_org'),
        ),
        migrations.AddConstraint(
            model_name='graphstoragefile',
            constraint=models.UniqueConstraint(fields=('graph', 'storage_file'), name='unique_graph_storage_file'),
        ),
        migrations.CreateModel(
            name='SessionStorageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='tables.session')),
                ('storage_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_storage_files', to='tables.storagefile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'storage_file'), name='unique_session_storage_file')],
            },
        ),
        migrations.CreateModel(
            name='GraphRagIndexConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('text', 'Text'), ('json', 'JSON')], default='text', help_text='Input file type to use (csv, text, json).', max_length=10)),
                ('chunk_size', models.PositiveIntegerField(default=1200, help_text='The chunk size to use.')),
                ('chunk_overlap', models.PositiveIntegerField(default=100, help_text='The chunk overlap to use.')),
                ('chunk_strategy', models.CharField(choices=[('tokens', 'Tokens'), ('sentence', 'Sentence')], default='tokens', help_text='The chunking strategy to use (tokens or sentence).', max_length=20)),
                ('entity_types', models.JSONField(default=tables.models.knowledge_models.graphrag_models.GraphRagIndexConfig.default_entity_types, help_text="The entity extraction types to use. Defaults to ['organization', 'person', 'geo', 'event']")),
                ('max_gleanings', models.PositiveIntegerField(default=1, help_text='The maximum number of entity gleanings to use.')),
                ('max_cluster_size', models.PositiveIntegerField(default=10, help_text='The maximum cluster size to use.')),
            ],
            options={
                'db_table': 'graph_rag_index_config',
            },
        ),
        migrations.CreateModel(
            name='AgentGraphRag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_graph_rags', to='tables.agent', unique=True)),
            ],
            options={
                'db_table': 'agent_graph_rag',
            },
        ),
        migrations.CreateModel(
            name='GraphRag',
            fields=[
                ('graph_rag_id', models.AutoField(primary_key=True, serialize=False)),
                ('rag_status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='new', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('agents', models.ManyToManyField(blank=True, help_text='Agents that have access to this GraphRag', related_name='graph_rags', through='tables.AgentGraphRag', to='tables.agent')),
                ('base_rag_type', models.ForeignKey(limit_choices_to={'rag_type': 'graph'}, on_delete=django.db.models.deletion.CASCADE, related_name='graph_rags', to='tables.baseragtype')),
                ('embedder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.embeddingconfig')),
                ('llm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmconfig')),
                ('index_config', models.OneToOneField(blank=True, help_text='Index configuration for this GraphRag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_rag', to='tables.graphragindexconfig')),
            ],
            options={
                'db_table': 'graph_rag',
            },
        ),
        migrations.AddField(
            model_name='agentgraphrag',
            name='graph_rag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='tables.graphrag'),
        ),
        migrations.CreateModel(
            name='GraphRagDocument',
            fields=[
                ('graph_rag_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_rag_links', to='tables.documentmetadata')),
                ('graph_rag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_rag_documents', to='tables.graphrag')),
            ],
            options={
                'db_table': 'graph_rag_document',
                'constraints': [models.UniqueConstraint(fields=('graph_rag', 'document'), name='unique_graph_rag_document')],
            },
        ),
        migrations.AddField(
            model_name='agentgraphrag',
            name='search_method',
            field=models.CharField(choices=[('basic', 'Basic Search'), ('local', 'Local Search')], default='basic', help_text='Active search method: basic or local', max_length=10),
        ),
        migrations.CreateModel(
            name='GraphRagBasicSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The basic search prompt to use.', null=True)),
                ('k', models.IntegerField(default=10, help_text='The number of text units to include in search context.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
                ('agent', models.OneToOneField(help_text='Agent this basic search configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='graph_basic_search_config', to='tables.agent')),
            ],
            options={
                'db_table': 'graph_rag_basic_search_config',
            },
        ),
        migrations.CreateModel(
            name='GraphRagLocalSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The local search prompt to use.', null=True)),
                ('text_unit_prop', models.FloatField(default=0.5, help_text='The text unit proportion.')),
                ('community_prop', models.FloatField(default=0.15, help_text='The community proportion.')),
                ('conversation_history_max_turns', models.IntegerField(default=5, help_text='The conversation history maximum turns.')),
                ('top_k_entities', models.IntegerField(default=10, help_text='The top k mapped entities.')),
                ('top_k_relationships', models.IntegerField(default=10, help_text='The top k mapped relations.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
                ('agent', models.OneToOneField(help_text='Agent this local search configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='graph_local_search_config', to='tables.agent')),
            ],
            options={
                'db_table': 'graph_rag_local_search_config',
            },
        ),
        migrations.AlterField(
            model_name='storagefile',
            name='path',
            field=models.CharField(help_text="Org-relative path, never starts with '/'", max_length=1000),
        ),
        django.contrib.postgres.operations.TrigramExtension(
        ),
        migrations.AddField(
            model_name='storagefile',
            name='name',
            field=models.CharField(help_text='Last path segment, denormalized for search', max_length=255),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='storagefile_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(db_index=True, max_length=12)),
                ('key_hash', models.CharField(max_length=64)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                # Created under its final name: the index DDL of a CreateModel is deferred to the end of
                # the migration, so the RenameIndex that 0138 did would not find it inside this squash.
                'indexes': [models.Index(fields=['prefix'], name='tables_apik_prefix_fbdead_idx')],
            },
        ),
        migrations.CreateModel(
            name='GraphVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(help_text='Serialized graph state: nodes, edges, conditional edges, metadata.')),
                ('dependencies', models.JSONField(default=dict, help_text='Lightweight manifest of external dependency IDs referenced at snapshot time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tables.graph')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classificationdecisiontablenode',
            name='id',
            field=models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='classificationdecisiontablenode',
            name='pre_computation_code',
        ),
        migrations.RemoveField(
            model_name='classificationdecisiontablenode',
            name='post_computation_code',
        ),
        migrations.RemoveField(
            model_name='classificationdecisiontablenode',
            name='route_variable_name',
        ),
        migrations.RemoveField(
            model_name='classificationdecisiontablenode',
            name='expression_errors_as_false',
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='pre_python_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdt_pre_nodes', to='tables.pythoncode'),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='post_python_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdt_post_nodes', to='tables.pythoncode'),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='default_llm_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdt_nodes_as_default', to='tables.llmconfig'),
        ),
        migrations.CreateModel(
            name='ClassificationDecisionTablePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_key', models.CharField(max_length=255)),
                ('prompt_text', models.TextField(blank=True, default='')),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('result_variable', models.CharField(default='prompt_result', max_length=255)),
                ('variable_mappings', models.JSONField(blank=True, default=dict)),
                ('cdt_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_configs', to='tables.classificationdecisiontablenode')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdt_prompts', to='tables.llmconfig')),
            ],
            options={
                'unique_together': {('cdt_node', 'prompt_key')},
            },
        ),
        migrations.RemoveField(
            model_name='classificationconditiongroup',
            name='route_code',
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='next_node_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='classificationdecisiontablenode',
            name='default_next_node',
        ),
        migrations.RemoveField(
            model_name='classificationdecisiontablenode',
            name='next_error_node',
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='route_code',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='default_next_node_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='next_error_node_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='classificationconditiongroup',
            constraint=models.UniqueConstraint(condition=models.Q(('route_code__isnull', False)), fields=('classification_decision_table_node', 'route_code'), name='unique_route_code_per_cdt_node'),
        ),
        migrations.RunSQL(
            sql='DELETE FROM tables_graphorganizationuser;DELETE FROM tables_graphorganization;DELETE FROM tables_organizationuser;DELETE FROM tables_organization;SET CONSTRAINTS ALL IMMEDIATE;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS auth_user_user_permissions CASCADE;DROP TABLE IF EXISTS auth_user_groups CASCADE;DROP TABLE IF EXISTS auth_user CASCADE;',
            reverse_sql='',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_user',
            },
            managers=[
                ('objects', tables.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rbac_password_reset_token',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_built_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rbac_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('flows', 'Flows'), ('agents', 'Agents'), ('tools', 'Tools'), ('knowledge_sources', 'Knowledge Sources'), ('files', 'Files'), ('projects', 'Projects'), ('llm_configs', 'LLM Configs'), ('secrets', 'Secrets'), ('users', 'Users'), ('roles', 'Roles')], max_length=32)),
                ('permissions', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rbac_role_permission',
            },
        ),
        migrations.RemoveConstraint(
            model_name='graphorganizationuser',
            name='unique_user_per_flow',
        ),
        migrations.RemoveConstraint(
            model_name='organizationuser',
            name='unique_flow_user_for_organization',
        ),
        migrations.RemoveField(
            model_name='graphorganizationuser',
            name='user',
        ),
        migrations.AddField(
            model_name='graphorganizationuser',
            name='organization_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='graph_persistent_states', to='tables.organizationuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tables.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graphorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_persistent_states', to='tables.organization'),
        ),
        migrations.AlterField(
            model_name='graphorganization',
            name='user_variables',
            field=models.JSONField(default=dict, help_text="Seed template of variables copied into each user's GraphOrganizationUser row"),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='graphorganizationuser',
            constraint=models.UniqueConstraint(fields=('graph', 'organization_user'), name='unique_user_per_flow'),
        ),
        migrations.AlterModelTable(
            name='organization',
            table='rbac_organization',
        ),
        migrations.AlterModelTable(
            name='organizationuser',
            table='rbac_organization_user',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('user', 'org')},
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tables.organization'),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='tables.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_set', to='tables.role'),
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'resource_type')},
        ),
        migrations.RunPython(
            code=seed_builtin_roles,
            reverse_code=unseed_builtin_roles,
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveIndex(
            model_name='storagefile',
            name='storagefile_name_trgm_idx',
        ),
        migrations.AlterField(
            model_name='graphversion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='test_input',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='rbac_organization_name_ci_uniq'),
        ),
        migrations.CreateModel(
            name='FlowAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_assistant', to='tables.graph')),
                ('llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.llmconfig')),
            ],
            options={
                'db_table': 'tables_flowassistant',
            },
        ),
        migrations.CreateModel(
            name='FlowAssistantConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_messages_legacy', models.JSONField(db_column='messages', default=list, editable=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('flow_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tables.flowassistant')),
                ('organization_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_assistant_conversations', to='tables.organizationuser')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'tables_flowassistantconversation',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowAssistantMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_rows', to='tables.flowassistantconversation')),
                ('message_index', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant'), ('tool', 'tool')], max_length=16)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ef_tables', models.JSONField(blank=True, null=True)),
                ('action_message', models.JSONField(blank=True, null=True)),
                ('interrupted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tables_flowassistantmessage',
                'ordering': ['message_index'],
                'indexes': [models.Index(fields=['conversation', 'message_index'], name='tables_flow_convers_a77e03_idx')],
                'unique_together': {('conversation', 'message_index')},
            },
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='use_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='organizationuser',
            constraint=models.UniqueConstraint(fields=('user', 'org'), name='rbac_organization_user_user_org_uniq'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=tables.models.user._avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='subgraphnode',
            name='subgraph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_subgraph', to='tables.graph'),
        ),
    ]
