# Generated by Django 5.1.3 on 2026-04-27 14:16

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import tables.models.knowledge_models.graphrag_models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0165_codeagentnode_use_storage_pythonnode_use_storage"),
        ("tables", "0167_merge_20260410_1240"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Org-relative path, never starts with '/'",
                        max_length=2048,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_files",
                        to="tables.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GraphStorageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_files",
                        to="tables.graph",
                    ),
                ),
                (
                    "storage_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_storage_files",
                        to="tables.storagefile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="storagefile",
            index=models.Index(
                fields=["org", "path"], name="tables_stor_org_id_f9ae19_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storagefile",
            constraint=models.UniqueConstraint(
                fields=("org", "path"), name="unique_storage_file_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="graphstoragefile",
            constraint=models.UniqueConstraint(
                fields=("graph", "storage_file"), name="unique_graph_storage_file"
            ),
        ),
        migrations.CreateModel(
            name="SessionStorageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_files",
                        to="tables.session",
                    ),
                ),
                (
                    "storage_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_storage_files",
                        to="tables.storagefile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "storage_file"),
                        name="unique_session_storage_file",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GraphRagIndexConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("text", "Text"), ("json", "JSON")],
                        default="text",
                        help_text="Input file type to use (csv, text, json).",
                        max_length=10,
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        default=1200, help_text="The chunk size to use."
                    ),
                ),
                (
                    "chunk_overlap",
                    models.PositiveIntegerField(
                        default=100, help_text="The chunk overlap to use."
                    ),
                ),
                (
                    "chunk_strategy",
                    models.CharField(
                        choices=[("tokens", "Tokens"), ("sentence", "Sentence")],
                        default="tokens",
                        help_text="The chunking strategy to use (tokens or sentence).",
                        max_length=20,
                    ),
                ),
                (
                    "entity_types",
                    models.JSONField(
                        default=tables.models.knowledge_models.graphrag_models.GraphRagIndexConfig.default_entity_types,
                        help_text="The entity extraction types to use. Defaults to ['organization', 'person', 'geo', 'event']",
                    ),
                ),
                (
                    "max_gleanings",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The maximum number of entity gleanings to use.",
                    ),
                ),
                (
                    "max_cluster_size",
                    models.PositiveIntegerField(
                        default=10, help_text="The maximum cluster size to use."
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_index_config",
            },
        ),
        migrations.CreateModel(
            name="AgentGraphRag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_graph_rags",
                        to="tables.agent",
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "agent_graph_rag",
            },
        ),
        migrations.CreateModel(
            name="GraphRag",
            fields=[
                ("graph_rag_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rag_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("warning", "Warning"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Agents that have access to this GraphRag",
                        related_name="graph_rags",
                        through="tables.AgentGraphRag",
                        to="tables.agent",
                    ),
                ),
                (
                    "base_rag_type",
                    models.ForeignKey(
                        limit_choices_to={"rag_type": "graph"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_rags",
                        to="tables.baseragtype",
                    ),
                ),
                (
                    "embedder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.embeddingconfig",
                    ),
                ),
                (
                    "llm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.llmconfig",
                    ),
                ),
                (
                    "index_config",
                    models.OneToOneField(
                        blank=True,
                        help_text="Index configuration for this GraphRag",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graph_rag",
                        to="tables.graphragindexconfig",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag",
            },
        ),
        migrations.AddField(
            model_name="agentgraphrag",
            name="graph_rag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_links",
                to="tables.graphrag",
            ),
        ),
        migrations.CreateModel(
            name="GraphRagDocument",
            fields=[
                (
                    "graph_rag_document_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_rag_links",
                        to="tables.documentmetadata",
                    ),
                ),
                (
                    "graph_rag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_rag_documents",
                        to="tables.graphrag",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_document",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("graph_rag", "document"),
                        name="unique_graph_rag_document",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="agentgraphrag",
            name="search_method",
            field=models.CharField(
                choices=[("basic", "Basic Search"), ("local", "Local Search")],
                default="basic",
                help_text="Active search method: basic or local",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="GraphRagBasicSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The basic search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "k",
                    models.IntegerField(
                        default=10,
                        help_text="The number of text units to include in search context.",
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this basic search configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_basic_search_config",
                        to="tables.agent",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_basic_search_config",
            },
        ),
        migrations.CreateModel(
            name="GraphRagLocalSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The local search prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "text_unit_prop",
                    models.FloatField(
                        default=0.5, help_text="The text unit proportion."
                    ),
                ),
                (
                    "community_prop",
                    models.FloatField(
                        default=0.15, help_text="The community proportion."
                    ),
                ),
                (
                    "conversation_history_max_turns",
                    models.IntegerField(
                        default=5, help_text="The conversation history maximum turns."
                    ),
                ),
                (
                    "top_k_entities",
                    models.IntegerField(
                        default=10, help_text="The top k mapped entities."
                    ),
                ),
                (
                    "top_k_relationships",
                    models.IntegerField(
                        default=10, help_text="The top k mapped relations."
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(default=12000, help_text="The maximum tokens."),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this local search configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_local_search_config",
                        to="tables.agent",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_local_search_config",
            },
        ),
        migrations.AlterField(
            model_name="storagefile",
            name="path",
            field=models.CharField(
                help_text="Org-relative path, never starts with '/'", max_length=1000
            ),
        ),
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddField(
            model_name="storagefile",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="storagefile",
            name="name",
            field=models.CharField(
                help_text="Last path segment, denormalized for search", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="storagefile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="storagefile_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("prefix", models.CharField(db_index=True, max_length=12)),
                ("key_hash", models.CharField(max_length=64)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prefix"], name="tables_apik_prefix_3f7e47_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GraphVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Serialized graph state: nodes, edges, conditional edges, metadata."
                    ),
                ),
                (
                    "dependencies",
                    models.JSONField(
                        default=dict,
                        help_text="Lightweight manifest of external dependency IDs referenced at snapshot time.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="tables.graph",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
