# Generated by Django 5.1.3 on 2026-04-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0166_storagefile_graphstoragefile_and_more_squashed_0175_merge_20260427_1053"),
        ("tables", "0168_pythonnode_test_input"),
    ]

    operations = []
