# Generated by Django 5.1.3 on 2026-04-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0168_realtime_provider_configs_and_channels"),
        ("tables", "0169_merge_imp_auth"),
    ]

    operations = []
