# Generated by Django 5.1.3 on 2026-04-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0166_storagefile_graphstoragefile_and_more_squashed_0175_merge_20260427_1053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graphversion",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, default=None, editable=False, null=True
            ),
        ),
    ]
