# Generated by Django 5.1.3 on 2026-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0171_remove_openai_audio_format_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationrecording",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="elevenlabsrealtimeconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="geminirealtimeconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="openairealtimeconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="realtimeagentchat",
            name="voice_recognition_prompt",
            field=models.TextField(
                blank=True, help_text="OpenAI / Gemini: transcription hint", null=True
            ),
        ),
        migrations.AlterField(
            model_name="realtimechannel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
