# Generated by Django 5.1.3 on 2026-04-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0166_storagefile_graphstoragefile_and_more_squashed_0175_merge_20260427_1053"),
        ("tables", "0174_remove_classificationconditiongroup_route_code_and_more"),
    ]

    operations = []
