# Generated by Django 5.1.3 on 2026-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0174_merge_20260429_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geminirealtimeconfig",
            name="model_name",
            field=models.CharField(
                default="gemini-3.1-flash-live-preview", max_length=250
            ),
        ),
    ]
