# Generated by Django 5.1.14 on 2026-10-08 15:13

import django.db.models.deletion
import tables.models.base_models
from django.db import migrations, models


_BITMASKS = {
    "Org Admin": {
        "flows": 31,             # C R U D E
        "agents": 31,            # C R U D E
        "tools": 15,
        "knowledge_sources": 15,
        "files": 31,             # C R U D E
        "projects": 31,          # C R U D E
        "llm_configs": 15,
        "secrets": 207,          # C R U D use list
        "users": 15,
        "roles": 15,
        "organizations": 0,      # Org Admin does not manage orgs
    },
    "Member": {
        "flows": 7,              # C R U
        "agents": 7,
        "tools": 7,
        "knowledge_sources": 2,  # R
        "files": 23,             # C R U E
        "projects": 7,
        "llm_configs": 2,
        "secrets": 192,          # use list
        "users": 0,
        "roles": 0,
        "organizations": 0,
    },
    "Viewer": {
        "flows": 66,             # R use
        "agents": 2,
        "tools": 2,
        "knowledge_sources": 2,
        "files": 2,
        "projects": 2,
        "llm_configs": 2,
        "secrets": 192,          # use list
        "users": 0,
        "roles": 0,
        "organizations": 0,
    },
}


def seed_role_permissions(apps, schema_editor):
    """Set the built-in role bitmasks, adding the organizations resource (ported from 0183_seed_builtin_role_permissions)."""
    Role = apps.get_model("tables", "Role")
    RolePermission = apps.get_model("tables", "RolePermission")

    for role_name, by_resource in _BITMASKS.items():
        try:
            role = Role.objects.get(
                name=role_name, is_built_in=True, org__isnull=True
            )
        except Role.DoesNotExist:
            continue
        for resource_type, bitmask in by_resource.items():
            RolePermission.objects.update_or_create(
                role=role,
                resource_type=resource_type,
                defaults={"permissions": bitmask},
            )
    # Superadmin role: intentionally no RolePermission rows. Authority
    # flows from User.is_superadmin.


def remove_role_permissions(apps, schema_editor):
    RolePermission = apps.get_model("tables", "RolePermission")
    RolePermission.objects.filter(role__is_built_in=True).delete()


class Migration(migrations.Migration):

    replaces = [('tables', '0176_create_schedule_trigger_node'), ('tables', '0181_merge_schedule_trigger_node'), ('tables', '0182_drop_llmnode'), ('tables', '0181_graphsessionmessage_parent_subgraph_execution_id_and_more'), ('tables', '0183_merge_20260604_1425'), ('tables', '0182_graph_save_version'), ('tables', '0183_merge_0182_drop_llmnode_0182_graph_save_version'), ('tables', '0184_merge_20260604_1512'), ('tables', '0186_merge_20260608_1013'), ('tables', '0182_resource_type_add_organizations'), ('tables', '0183_seed_builtin_role_permissions'), ('tables', '0184_merge_rbac_roles_and_permissions'), ('tables', '0185_merge_rbac_roles_and_permissions_2'), ('tables', '0187_merge_demo_migrations'), ('tables', '0170_pythoncodetool_variables_drop_args_schema'), ('tables', '0171_merge_tools_configuration'), ('tables', '0176_merge_20260501_1015'), ('tables', '0178_merge_20260521_0947'), ('tables', '0182_merge_20260526_1446'), ('tables', '0186_tool_configuration_for_0182_and_0185'), ('tables', '0188_merge_20260618_1643'), ('tables', '0189_alter_flowassistant_id_and_more')]

    dependencies = [
        ('tables', '0174_merge_20260429_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTriggerNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('run_mode', models.CharField(blank=True, choices=[('once', 'Once'), ('repeat', 'Repeat')], max_length=10, null=True)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('every', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=10, null=True)),
                ('weekdays', models.JSONField(blank=True, null=True)),
                ('end_type', models.CharField(blank=True, choices=[('never', 'Never'), ('on_date', 'On Date'), ('after_n_runs', 'After N Runs')], max_length=15, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('max_runs', models.IntegerField(blank=True, null=True)),
                ('current_runs', models.IntegerField(default=0)),
                ('next_run_date_time', models.DateTimeField(blank=True, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_trigger_node_list', to='tables.graph')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LLMNode',
        ),
        migrations.AddField(
            model_name='graphsessionmessage',
            name='parent_subgraph_execution_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='graphsessionmessage',
            index=models.Index(fields=['session', 'parent_subgraph_execution_id', 'id'], name='gsm_session_parent_id_idx'),
        ),
        migrations.AddField(
            model_name='graph',
            name='save_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='resource_type',
            field=models.CharField(choices=[('organizations', 'Organizations'), ('flows', 'Flows'), ('agents', 'Agents'), ('tools', 'Tools'), ('knowledge_sources', 'Knowledge Sources'), ('files', 'Files'), ('projects', 'Projects'), ('llm_configs', 'LLM Configs'), ('secrets', 'Secrets'), ('users', 'Users'), ('roles', 'Roles')], max_length=32),
        ),
        migrations.RunPython(
            code=seed_role_permissions,
            reverse_code=remove_role_permissions,
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='variables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='pythoncodetool',
            name='args_schema',
        ),
        migrations.DeleteModel(
            name='PythonCodeToolConfigField',
        ),
        migrations.AlterField(
            model_name='flowassistant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flowassistantconversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flowassistantconversation',
            name='last_message_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
