# Generated by Django 5.1.3 on 2026-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0186_tool_configuration_for_0182_and_0185"),
    ]

    operations = [
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="error_code",
            field=models.CharField(
                choices=[
                    ("chunking_failed", "Chunking Failed"),
                    ("no_chunks_produced", "No Chunks Produced"),
                    ("embedding_failed", "Embedding Failed"),
                    ("embedder_auth", "Embedder Auth"),
                    ("embedder_rate_limit", "Embedder Rate Limit"),
                    ("unknown", "Unknown"),
                    ("none", "None"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="indexed_additional_params",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="indexed_chunk_overlap",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="indexed_chunk_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="naiveragdocumentconfig",
            name="indexed_chunk_strategy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("token", "Token"),
                    ("character", "Character"),
                    ("markdown", "Markdown"),
                    ("json", "Json"),
                    ("html", "Html"),
                    ("csv", "Csv"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
