# Generated by Django 5.1.3 on 2026-07-03 07:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0187_naiveragdocumentconfig_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="naiverag",
            name="indexing_document_config_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
