# Generated by Django 5.1.3 on 2026-07-14 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0188_naiverag_indexing_document_config_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphrag",
            name="indexing_document_config_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
