# Generated by Django 5.1.3 on 2026-06-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0188_merge_20260618_1643"),
        (
            "tables",
            "0188_merge_change_classificationconditiongroup_prompt_id_field_type_2",
        ),
    ]

    operations = []
