# Generated by Django 5.1.3 on 2026-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0188_naiverag_indexing_document_config_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphrag",
            name="error_code",
            field=models.CharField(
                choices=[
                    ("chunking_failed", "Chunking Failed"),
                    ("no_chunks_produced", "No Chunks Produced"),
                    ("embedding_failed", "Embedding Failed"),
                    ("embedder_auth", "Embedder Auth"),
                    ("embedder_rate_limit", "Embedder Rate Limit"),
                    ("unknown", "Unknown"),
                    ("none", "None"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="naiverag",
            name="error_code",
            field=models.CharField(
                choices=[
                    ("chunking_failed", "Chunking Failed"),
                    ("no_chunks_produced", "No Chunks Produced"),
                    ("embedding_failed", "Embedding Failed"),
                    ("embedder_auth", "Embedder Auth"),
                    ("embedder_rate_limit", "Embedder Rate Limit"),
                    ("unknown", "Unknown"),
                    ("none", "None"),
                ],
                default="none",
                max_length=32,
            ),
        ),
    ]
