# Generated by Django 5.1.7 on 2026-07-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0189_alter_flowassistant_id_and_more"),
        (
            "tables",
            "0189_merge_change_classificationconditiongroup_prompt_id_field_type_3",
        ),
    ]

    operations = []
