# Generated by Django 5.1.3 on 2026-06-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0185_backfill_storagefile_metadata"),
        ("tables", "0189_alter_flowassistant_id_and_more"),
    ]

    operations = []
