# Generated by Django 5.1.3 on 2026-06-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0189_alter_flowassistant_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="response_format",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="response_format",
        ),
    ]
