# Generated by Django 5.1.7 on 2026-06-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0187_merge_20260612_1256"),
        ("tables", "0189_alter_flowassistant_id_and_more"),
    ]

    operations = []
