# Generated by Django 5.1.3 on 2026-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0189_graphrag_indexing_document_config_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphrag",
            name="reindex_reason",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="graphragdocument",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("indexed", "Indexed")], default="new", max_length=20
            ),
        ),
    ]
