# Generated by Django 5.1.7 on 2026-07-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0189_alter_flowassistant_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="defaultllmconfig",
            name="api_version",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="base_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="logprobs",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="defaultllmconfig",
            name="top_logprobs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="api_version",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="base_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="logprobs",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="top_logprobs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="embeddingmodel",
            name="base_url",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="base_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
