# Generated by Django 5.1.7 on 2026-07-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0189_graphrag_indexing_document_config_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentgraphrag',
            name='search_method',
            field=models.CharField(choices=[('basic', 'Basic Search'), ('local', 'Local Search'), ('global', 'Global Search'), ('drift', 'Drift Search')], default='basic', help_text='Active search method: basic or local', max_length=10),
        ),
        migrations.CreateModel(
            name='GraphRagDriftSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The primer prompt used to seed the initial answer and follow-up questions.', null=True)),
                ('reduce_prompt', models.TextField(blank=True, default=None, help_text='The reduce-step prompt used to aggregate traversal results into the final answer.', null=True)),
                ('data_max_tokens', models.IntegerField(default=12000, help_text='The maximum tokens of context data passed into the search.')),
                ('reduce_max_tokens', models.IntegerField(blank=True, default=None, help_text='The maximum context tokens for the reduce step (None uses the model default).', null=True)),
                ('reduce_temperature', models.FloatField(default=0.0, help_text='The sampling temperature for the reduce-step LLM call.')),
                ('reduce_max_completion_tokens', models.IntegerField(blank=True, default=None, help_text='The maximum completion tokens the reduce step may generate (None uses the model default).', null=True)),
                ('concurrency', models.IntegerField(default=32, help_text='The number of concurrent LLM requests during traversal.')),
                ('drift_k_followups', models.IntegerField(default=20, help_text='The number of follow-up questions to keep and explore at each step.')),
                ('primer_folds', models.IntegerField(default=5, help_text='The number of folds the community reports are split into for the primer step.')),
                ('primer_llm_max_tokens', models.IntegerField(default=12000, help_text='The maximum tokens for each primer LLM call.')),
                ('n_depth', models.IntegerField(default=3, help_text='The number of traversal iterations (depth) of follow-up exploration.')),
                ('community_level', models.IntegerField(default=2, help_text='The community hierarchy level whose reports are used for the primer.')),
                ('local_search_text_unit_prop', models.FloatField(default=0.9, help_text='The text unit proportion for the local searches spawned during traversal.')),
                ('local_search_community_prop', models.FloatField(default=0.1, help_text='The community proportion for the local searches spawned during traversal.')),
                ('local_search_top_k_mapped_entities', models.IntegerField(default=10, help_text='The top k mapped entities for the local searches spawned during traversal.')),
                ('local_search_top_k_relationships', models.IntegerField(default=10, help_text='The top k mapped relations for the local searches spawned during traversal.')),
                ('local_search_max_data_tokens', models.IntegerField(default=12000, help_text='The maximum context tokens for the local searches spawned during traversal.')),
                ('local_search_temperature', models.FloatField(default=0.0, help_text='The sampling temperature for the local-search LLM calls.')),
                ('local_search_top_p', models.FloatField(default=1.0, help_text='The nucleus sampling top-p for the local-search LLM calls.')),
                ('local_search_n', models.IntegerField(default=1, help_text='The number of completions to generate per local-search LLM call.')),
                ('local_search_llm_max_gen_tokens', models.IntegerField(blank=True, default=None, help_text='The maximum tokens a local-search call may generate (None uses the model default).', null=True)),
                ('local_search_llm_max_gen_completion_tokens', models.IntegerField(blank=True, default=None, help_text='The maximum completion tokens a local-search call may generate (None uses the model default).', null=True)),
                ('agent', models.OneToOneField(help_text='Agent this drift search configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='graph_drift_search_config', to='tables.agent')),
            ],
            options={
                'db_table': 'graph_rag_drift_search_config',
            },
        ),
        migrations.CreateModel(
            name='GraphRagGlobalSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_prompt', models.TextField(blank=True, default=None, help_text='The map-step prompt used to answer the query against each community report batch.', null=True)),
                ('reduce_prompt', models.TextField(blank=True, default=None, help_text='The reduce-step prompt used to aggregate map answers into the final response.', null=True)),
                ('knowledge_prompt', models.TextField(blank=True, default=None, help_text='The general-knowledge prompt supplying background context to the search.', null=True)),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens for the overall search context window.')),
                ('data_max_tokens', models.IntegerField(default=12000, help_text='The maximum tokens of community-report data passed into the map step.')),
                ('map_max_length', models.IntegerField(default=1000, help_text='The maximum length (in words) of each map-step response.')),
                ('reduce_max_length', models.IntegerField(default=2000, help_text='The maximum length (in words) of the reduce-step response.')),
                ('dynamic_community_selection', models.BooleanField(default=False, help_text='Whether to let an LLM rate and dynamically select relevant communities instead of using all of them.')),
                ('dynamic_search_threshold', models.IntegerField(default=1, help_text='The minimum LLM relevance rating a community must reach to be included in dynamic selection.')),
                ('dynamic_search_keep_parent', models.BooleanField(default=False, help_text='Whether to keep a parent community when any of its child communities are rated relevant.')),
                ('dynamic_search_num_repeats', models.IntegerField(default=1, help_text='The number of times each community is rated during dynamic selection (ratings are averaged).')),
                ('dynamic_search_use_summary', models.BooleanField(default=False, help_text='Whether to rate communities using their summary instead of the full report content.')),
                ('dynamic_search_max_level', models.IntegerField(default=2, help_text='The maximum community hierarchy level to consider during dynamic selection.')),
                ('agent', models.OneToOneField(help_text='Agent this global search configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='graph_global_search_config', to='tables.agent')),
            ],
            options={
                'db_table': 'graph_rag_global_search_config',
            },
        ),
    ]
