# Generated by Django 5.1.7 on 2026-07-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0189_graphrag_indexing_document_config_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentgraphrag',
            name='search_method',
            field=models.CharField(choices=[('basic', 'Basic Search'), ('local', 'Local Search'), ('global', 'Global Search'), ('drift', 'Drift Search')], default='basic', help_text='Active search method: basic or local', max_length=10),
        ),
        migrations.CreateModel(
            name='GraphRagDriftSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, null=True)),
                ('reduce_prompt', models.TextField(blank=True, default=None, null=True)),
                ('data_max_tokens', models.IntegerField(default=12000)),
                ('reduce_max_tokens', models.IntegerField(blank=True, default=None, null=True)),
                ('reduce_temperature', models.FloatField(default=0.0)),
                ('reduce_max_completion_tokens', models.IntegerField(blank=True, default=None, null=True)),
                ('concurrency', models.IntegerField(default=32)),
                ('drift_k_followups', models.IntegerField(default=20)),
                ('primer_folds', models.IntegerField(default=5)),
                ('primer_llm_max_tokens', models.IntegerField(default=12000)),
                ('n_depth', models.IntegerField(default=3)),
                ('community_level', models.IntegerField(default=2)),
                ('local_search_text_unit_prop', models.FloatField(default=0.9)),
                ('local_search_community_prop', models.FloatField(default=0.1)),
                ('local_search_top_k_mapped_entities', models.IntegerField(default=10)),
                ('local_search_top_k_relationships', models.IntegerField(default=10)),
                ('local_search_max_data_tokens', models.IntegerField(default=12000)),
                ('local_search_temperature', models.FloatField(default=0.0)),
                ('local_search_top_p', models.FloatField(default=1.0)),
                ('local_search_n', models.IntegerField(default=1)),
                ('local_search_llm_max_gen_tokens', models.IntegerField(blank=True, default=None, null=True)),
                ('local_search_llm_max_gen_completion_tokens', models.IntegerField(blank=True, default=None, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_drift_search_config', to='tables.agent')),
            ],
            options={
                'db_table': 'graph_rag_drift_search_config',
            },
        ),
        migrations.CreateModel(
            name='GraphRagGlobalSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_prompt', models.TextField(blank=True, default=None, null=True)),
                ('reduce_prompt', models.TextField(blank=True, default=None, null=True)),
                ('knowledge_prompt', models.TextField(blank=True, default=None, null=True)),
                ('max_context_tokens', models.IntegerField(default=12000)),
                ('data_max_tokens', models.IntegerField(default=12000)),
                ('map_max_length', models.IntegerField(default=1000)),
                ('reduce_max_length', models.IntegerField(default=2000)),
                ('dynamic_community_selection', models.BooleanField(default=False)),
                ('dynamic_search_threshold', models.IntegerField(default=1)),
                ('dynamic_search_keep_parent', models.BooleanField(default=False)),
                ('dynamic_search_num_repeats', models.IntegerField(default=1)),
                ('dynamic_search_use_summary', models.BooleanField(default=False)),
                ('dynamic_search_max_level', models.IntegerField(default=2)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_global_search_config', to='tables.agent')),
            ],
            options={
                'db_table': 'graph_rag_global_search_config',
            },
        ),
    ]
