# Generated by Django 5.1.3 on 2026-06-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0190_merge_20260624_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefaultSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('all', 'All Places'), ('flow', 'Flow'), ('chat', 'Chat')], help_text="Context where this surface is the default: 'all' for any place, 'flow' for flow execution, 'chat' for chat sessions.", max_length=5)),
                ('agent_definition', models.ForeignKey(help_text='Agent definition this default surface assignment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='default_surfaces', to='tables.agentdefinition')),
                ('surface', models.ForeignKey(help_text='Surface assigned as the default for this agent in the given place.', on_delete=django.db.models.deletion.CASCADE, related_name='default_for', to='tables.surface')),
            ],
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='default_surface_list',
            field=models.ManyToManyField(blank=True, help_text='Surfaces applied to this agent by default, per place (flow/chat/all). Managed via AgentDefaultSurface through table.', related_name='default_in_agents', through='tables.AgentDefaultSurface', to='tables.surface'),
        ),
        migrations.CreateModel(
            name='SurfaceKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(help_text='SourceCollection available within this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.sourcecollection')),
                ('surface', models.ForeignKey(help_text='Surface this knowledge collection is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='tables.surface')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceGraphLocalSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The local search prompt to use.', null=True)),
                ('text_unit_prop', models.FloatField(default=0.5, help_text='The text unit proportion.')),
                ('community_prop', models.FloatField(default=0.15, help_text='The community proportion.')),
                ('conversation_history_max_turns', models.IntegerField(default=5, help_text='The conversation history maximum turns.')),
                ('top_k_entities', models.IntegerField(default=10, help_text='The top k mapped entities.')),
                ('top_k_relationships', models.IntegerField(default=10, help_text='The top k mapped relations.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
                ('surface_knowledge', models.OneToOneField(help_text='SurfaceKnowledge entry this GraphRAG local search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='graph_local_search_config', to='tables.surfaceknowledge')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceGraphBasicSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The basic search prompt to use.', null=True)),
                ('k', models.IntegerField(default=10, help_text='The number of text units to include in search context.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
                ('surface_knowledge', models.OneToOneField(help_text='SurfaceKnowledge entry this GraphRAG basic search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='graph_basic_search_config', to='tables.surfaceknowledge')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceMcpTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], help_text='Whether this tool is explicitly allowed or denied for this surface.', max_length=5)),
                ('mcp_tool', models.ForeignKey(help_text='McpTool being allowed or denied on this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.mcptool')),
                ('surface', models.ForeignKey(help_text='Surface this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tools', to='tables.surface')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceNaiveSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_limit', models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge')),
                ('similarity_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3)),
                ('surface_knowledge', models.OneToOneField(help_text='SurfaceKnowledge entry this naive search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='naive_search_config', to='tables.surfaceknowledge')),
            ],
        ),
        migrations.CreateModel(
            name='SurfacePythonTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], help_text='Whether this tool is explicitly allowed or denied for this surface.', max_length=5)),
                ('python_tool', models.ForeignKey(help_text='PythonCodeTool being allowed or denied on this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.pythoncodetool')),
                ('surface', models.ForeignKey(help_text='Surface this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='python_tools', to='tables.surface')),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_list', models.BooleanField(default=False, help_text='Agent may list (enumerate) this file or folder within the surface.')),
                ('can_view', models.BooleanField(default=False, help_text='Agent may read/view the content of this file within the surface.')),
                ('can_edit', models.BooleanField(default=False, help_text='Agent may modify or overwrite this file within the surface.')),
                ('can_delete', models.BooleanField(default=False, help_text='Agent may delete this file within the surface.')),
                ('storage_file', models.ForeignKey(help_text='StorageFile whose access is being configured for this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.storagefile')),
                ('surface', models.ForeignKey(help_text='Surface this storage permission entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='tables.surface')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agentdefaultsurface',
            constraint=models.UniqueConstraint(fields=('agent_definition', 'surface', 'place'), name='uniq_agent_default_surface'),
        ),
        migrations.AddConstraint(
            model_name='surfaceknowledge',
            constraint=models.UniqueConstraint(fields=('surface', 'collection'), name='uniq_surface_knowledge'),
        ),
        migrations.AddConstraint(
            model_name='surfacemcptool',
            constraint=models.UniqueConstraint(fields=('surface', 'mcp_tool'), name='uniq_surface_mcp_tool'),
        ),
        migrations.AddConstraint(
            model_name='surfacepythontool',
            constraint=models.UniqueConstraint(fields=('surface', 'python_tool'), name='uniq_surface_python_tool'),
        ),
        migrations.AddConstraint(
            model_name='surfacestorageitem',
            constraint=models.UniqueConstraint(fields=('surface', 'storage_file'), name='uniq_surface_storage_item'),
        ),
    ]
