# Generated by Django 5.1.7 on 2026-06-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0190_merge_20260605"),
        ("tables", "0190_merge_20260624_1519"),
    ]

    operations = []
