# Generated by Django 5.1.7 on 2026-07-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0190_alter_agentgraphrag_search_method_and_more'),
        ('tables', '0190_graphrag_reindex_reason_graphragdocument_status'),
    ]

    operations = [
    ]
