# Generated by Django 5.1.3 on 2026-07-14 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentdefaultsurface_place'),
        ('tables', '0191_agentnode_tasknode_agentnodetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeAgentDefinition',
            fields=[
                ('agent_definition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='realtime_agent', serialize=False, to='agents.agentdefinition')),
                ('wake_word', models.CharField(blank=True, max_length=255, null=True)),
                ('stop_prompt', models.CharField(blank=True, default='stop', max_length=255, null=True)),
                ('language', models.CharField(blank=True, help_text='ISO-639-1 format', max_length=2, null=True)),
                ('voice_recognition_prompt', models.TextField(blank=True, help_text="The prompt to use for the transcription, to guide the model (e.g. 'Expect words related to technology')", null=True)),
                ('voice', models.CharField(default='alloy', max_length=100)),
                ('realtime_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeconfig')),
                ('realtime_transcription_config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimetranscriptionconfig')),
            ],
            options={
                'db_table': 'realtime_agent_definition',
            },
        ),
        migrations.AddField(
            model_name='realtimeagentchat',
            name='rt_agent_definition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeagentdefinition'),
        ),
    ]
