# Generated by Django 5.1.7 on 2026-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0191_naiverag_outdated_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphrag',
            name='reindex_reason',
        ),
        migrations.AddField(
            model_name='graphrag',
            name='outdated_reasons',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='graphrag',
            name='rag_status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('outdated', 'Outdated')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='graphragdocument',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed'), ('failed', 'Failed'), ('outdated', 'Outdated')], default='new', max_length=20),
        ),
    ]
