# Generated by Django 5.1.3 on 2026-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0191_agentdefaultsurface_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentdefinition",
            name="instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-form prompt for the agent. Put behavior, goals, tone, and constraints here.",
            ),
        ),
    ]
