# Generated by Django 5.1.7 on 2026-07-29 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0191_merge_20260729_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='context_window',
            field=models.IntegerField(default=16000, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
