# Generated by Django 5.1.3 on 2026-07-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0192_realtimeagentdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicesettings',
            name='voice_agent_definition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.realtimeagentdefinition'),
        ),
    ]
