# Generated by Django 5.1.3 on 2026-07-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0192_alter_agentdefinition_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdefinition",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-form key-value store for arbitrary client/UI data. Not used by execution.",
            ),
        ),
    ]
