# Generated by Django 5.1.7 on 2026-08-10 00:00

from django.db import migrations, models


# Generated by Django 5.1.7

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    NaiveRag = apps.get_model("tables", "NaiveRag")
    NaiveRag.objects.filter(rag_status="warning").update(rag_status="partial")

    NaiveRagDocumentConfig = apps.get_model("tables", "NaiveRagDocumentConfig")
    NaiveRagDocumentConfig.objects.filter(status="warning").update(status="outdated")
    NaiveRagDocumentConfig.objects.filter(status__in=("chunking", "chunked", "indexing")).update(status="new")

    GraphRag = apps.get_model("tables", "GraphRag")
    GraphRag.objects.filter(rag_status="warning").update(rag_status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0192_remove_graphrag_reindex_reason_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='graphrag',
            name='rag_status',
            field=models.CharField(
                choices=[
                    ('new', 'New'),
                    ('processing', 'Processing'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('cancelled', 'Cancelled'),
                    ('outdated', 'Outdated'),
                ],
                default='new',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='naiverag',
            name='rag_status',
            field=models.CharField(
                choices=[
                    ('new', 'New'),
                    ('processing', 'Processing'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('cancelled', 'Cancelled'),
                    ('partial', 'Partial'),
                    ('outdated', 'Outdated'),
                ],
                default='new',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='naiveragdocumentconfig',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'New'),
                    ('processing', 'Processing'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('outdated', 'Outdated'),
                ],
                default='new',
                max_length=20,
            ),
        ),
    ]
