# Generated by Django 5.1.3 on 2026-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0193_agentdefinition_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknode',
            name='surface_list',
            field=models.ManyToManyField(blank=True, help_text='Surfaces attached to this task node.', related_name='task_nodes', to='tables.surface'),
        ),
    ]
