# Generated by Django 5.1.7 on 2026-08-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0193_remove_deprecated_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphrag",
            name="slot",
            field=models.CharField(
                choices=[("a", "A"), ("b", "B")],
                default="a",
                max_length=1,
            ),
        ),
    ]
