# Generated by Django 5.1.3 on 2026-07-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0194_tasknode_surface_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(blank=True, default='', help_text='Free-form text appended to the agent prompt when this surface is active. Empty string means no extra instructions.')),
                ('allow_creation', models.BooleanField(default=False, help_text='Surface-wide permission: when True, the agent may create new storage files within this surface.')),
                ('task_node', models.OneToOneField(help_text='TaskNode that owns this ad-hoc surface. Deleted with the node.', on_delete=django.db.models.deletion.CASCADE, related_name='inline_surface', to='tables.tasknode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InlineSurfaceKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(help_text='SourceCollection available within this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.sourcecollection')),
                ('inline_surface', models.ForeignKey(help_text='InlineSurface this knowledge collection is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='tables.inlinesurface')),
            ],
        ),
        migrations.CreateModel(
            name='InlineSurfaceGraphLocalSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The local search prompt to use.', null=True)),
                ('text_unit_prop', models.FloatField(default=0.5, help_text='The text unit proportion.')),
                ('community_prop', models.FloatField(default=0.15, help_text='The community proportion.')),
                ('conversation_history_max_turns', models.IntegerField(default=5, help_text='The conversation history maximum turns.')),
                ('top_k_entities', models.IntegerField(default=10, help_text='The top k mapped entities.')),
                ('top_k_relationships', models.IntegerField(default=10, help_text='The top k mapped relations.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
                ('surface_knowledge', models.OneToOneField(help_text='InlineSurfaceKnowledge entry this GraphRAG local search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='graph_local_search_config', to='tables.inlinesurfaceknowledge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InlineSurfaceGraphBasicSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The basic search prompt to use.', null=True)),
                ('k', models.IntegerField(default=10, help_text='The number of text units to include in search context.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
                ('surface_knowledge', models.OneToOneField(help_text='InlineSurfaceKnowledge entry this GraphRAG basic search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='graph_basic_search_config', to='tables.inlinesurfaceknowledge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InlineSurfaceMcpTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], help_text='Whether this tool is explicitly allowed or denied for this surface.', max_length=5)),
                ('inline_surface', models.ForeignKey(help_text='InlineSurface this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tools', to='tables.inlinesurface')),
                ('mcp_tool', models.ForeignKey(help_text='McpTool being allowed or denied on this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.mcptool')),
            ],
        ),
        migrations.CreateModel(
            name='InlineSurfaceNaiveSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_limit', models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge')),
                ('similarity_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3)),
                ('surface_knowledge', models.OneToOneField(help_text='InlineSurfaceKnowledge entry this naive search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='naive_search_config', to='tables.inlinesurfaceknowledge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InlineSurfacePythonTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], help_text='Whether this tool is explicitly allowed or denied for this surface.', max_length=5)),
                ('inline_surface', models.ForeignKey(help_text='InlineSurface this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='python_tools', to='tables.inlinesurface')),
                ('python_tool', models.ForeignKey(help_text='PythonCodeTool being allowed or denied on this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.pythoncodetool')),
            ],
        ),
        migrations.CreateModel(
            name='InlineSurfaceStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_list', models.CharField(choices=[('allow', 'Allow'), ('unset', 'Unset'), ('deny', 'Deny')], default='unset', help_text="Whether the agent may list (enumerate) this file/folder. 'deny' explicitly forbids it.", max_length=5)),
                ('can_view', models.CharField(choices=[('allow', 'Allow'), ('unset', 'Unset'), ('deny', 'Deny')], default='unset', help_text="Whether the agent may read/view the content of this file. 'deny' explicitly forbids it.", max_length=5)),
                ('can_edit', models.CharField(choices=[('allow', 'Allow'), ('unset', 'Unset'), ('deny', 'Deny')], default='unset', help_text="Whether the agent may modify or overwrite this file. 'deny' explicitly forbids it.", max_length=5)),
                ('can_delete', models.CharField(choices=[('allow', 'Allow'), ('unset', 'Unset'), ('deny', 'Deny')], default='unset', help_text="Whether the agent may delete this file. 'deny' explicitly forbids it.", max_length=5)),
                ('inline_surface', models.ForeignKey(help_text='InlineSurface this storage permission entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='tables.inlinesurface')),
                ('storage_file', models.ForeignKey(help_text='StorageFile whose access is being configured for this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.storagefile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='inlinesurfaceknowledge',
            constraint=models.UniqueConstraint(fields=('inline_surface', 'collection'), name='uniq_inline_surface_knowledge'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacemcptool',
            constraint=models.UniqueConstraint(fields=('inline_surface', 'mcp_tool'), name='uniq_inline_surface_mcp_tool'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacepythontool',
            constraint=models.UniqueConstraint(fields=('inline_surface', 'python_tool'), name='uniq_inline_surface_python_tool'),
        ),
        migrations.AddConstraint(
            model_name='inlinesurfacestorageitem',
            constraint=models.UniqueConstraint(fields=('inline_surface', 'storage_file'), name='uniq_inline_surface_storage_item'),
        ),
    ]
