# Generated by Django 5.1.3 on 2026-06-18 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0194_tools_org_not_null"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sourcecollection",
            name="unique_collection_name_per_user",
        ),
        migrations.AddField(
            model_name="sourcecollection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sourcecollection",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcecollection",
            index=models.Index(fields=["org"], name="tables_sour_org_id_3a2e10_idx"),
        ),
        migrations.AddConstraint(
            model_name="sourcecollection",
            constraint=models.UniqueConstraint(
                fields=("org", "collection_name"), name="unique_collection_name_per_org"
            ),
        ),
    ]
