# Generated by Django 5.1.3 on 2026-07-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0195_inlinesurface_inlinesurfaceknowledge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlinesurface',
            name='allow_creation',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='allow_creation',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='description',
        ),
    ]
