# Generated by Django 5.1.3 on 2026-07-06 14:01

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0196_remove_inlinesurface_allow_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInlineSurface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(blank=True, default='', help_text='Free-form text appended to the agent prompt when this surface is active. Empty string means no extra instructions.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentInlineSurfaceGraphBasicSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The basic search prompt to use.', null=True)),
                ('k', models.IntegerField(default=10, help_text='The number of text units to include in search context.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentInlineSurfaceGraphLocalSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The local search prompt to use.', null=True)),
                ('text_unit_prop', models.FloatField(default=0.5, help_text='The text unit proportion.')),
                ('community_prop', models.FloatField(default=0.15, help_text='The community proportion.')),
                ('conversation_history_max_turns', models.IntegerField(default=5, help_text='The conversation history maximum turns.')),
                ('top_k_entities', models.IntegerField(default=10, help_text='The top k mapped entities.')),
                ('top_k_relationships', models.IntegerField(default=10, help_text='The top k mapped relations.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentInlineSurfaceKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AgentInlineSurfaceMcpTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], help_text='Whether this tool is explicitly allowed or denied for this surface.', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AgentInlineSurfaceNaiveSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_limit', models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge')),
                ('similarity_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentInlineSurfacePythonTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], help_text='Whether this tool is explicitly allowed or denied for this surface.', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='AgentInlineSurfaceStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_list', models.CharField(choices=[('allow', 'Allow'), ('unset', 'Unset'), ('deny', 'Deny')], default='unset', help_text="Whether the agent may list (enumerate) this file/folder. 'deny' explicitly forbids it.", max_length=5)),
                ('can_view', models.CharField(choices=[('allow', 'Allow'), ('unset', 'Unset'), ('deny', 'Deny')], default='unset', help_text="Whether the agent may read/view the content of this file. 'deny' explicitly forbids it.", max_length=5)),
                ('can_edit', models.CharField(choices=[('allow', 'Allow'), ('unset', 'Unset'), ('deny', 'Deny')], default='unset', help_text="Whether the agent may modify or overwrite this file. 'deny' explicitly forbids it.", max_length=5)),
                ('can_delete', models.CharField(choices=[('allow', 'Allow'), ('unset', 'Unset'), ('deny', 'Deny')], default='unset', help_text="Whether the agent may delete this file. 'deny' explicitly forbids it.", max_length=5)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='agentnodetask',
            name='uniq_agentnodetask_node_order',
        ),
        migrations.AddField(
            model_name='agentnode',
            name='surface_list',
            field=models.ManyToManyField(blank=True, help_text='Surfaces attached to this agent node.', related_name='agent_nodes', to='tables.surface'),
        ),
        migrations.AddField(
            model_name='agentnodetask',
            name='name',
            field=models.CharField(default='', help_text='Name of this sub-task, unique within the parent agent node.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='agentnodetask',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('agent_node', 'order'), name='uniq_agentnodetask_node_order'),
        ),
        migrations.AddConstraint(
            model_name='agentnodetask',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('agent_node', 'name'), name='uniq_agentnodetask_node_name'),
        ),
        migrations.AddField(
            model_name='agentinlinesurface',
            name='agent_node',
            field=models.OneToOneField(help_text='AgentNode that owns this ad-hoc surface. Deleted with the node.', on_delete=django.db.models.deletion.CASCADE, related_name='inline_surface', to='tables.agentnode'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfaceknowledge',
            name='agent_inline_surface',
            field=models.ForeignKey(help_text='AgentInlineSurface this knowledge collection is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='tables.agentinlinesurface'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfaceknowledge',
            name='collection',
            field=models.ForeignKey(help_text='SourceCollection available within this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.sourcecollection'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacegraphlocalsearchconfig',
            name='surface_knowledge',
            field=models.OneToOneField(help_text='AgentInlineSurfaceKnowledge entry this GraphRAG local search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='graph_local_search_config', to='tables.agentinlinesurfaceknowledge'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacegraphbasicsearchconfig',
            name='surface_knowledge',
            field=models.OneToOneField(help_text='AgentInlineSurfaceKnowledge entry this GraphRAG basic search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='graph_basic_search_config', to='tables.agentinlinesurfaceknowledge'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacemcptool',
            name='agent_inline_surface',
            field=models.ForeignKey(help_text='AgentInlineSurface this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tools', to='tables.agentinlinesurface'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacemcptool',
            name='mcp_tool',
            field=models.ForeignKey(help_text='McpTool being allowed or denied on this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.mcptool'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacenaivesearchconfig',
            name='surface_knowledge',
            field=models.OneToOneField(help_text='AgentInlineSurfaceKnowledge entry this naive search configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='naive_search_config', to='tables.agentinlinesurfaceknowledge'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacepythontool',
            name='agent_inline_surface',
            field=models.ForeignKey(help_text='AgentInlineSurface this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='python_tools', to='tables.agentinlinesurface'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacepythontool',
            name='python_tool',
            field=models.ForeignKey(help_text='PythonCodeTool being allowed or denied on this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.pythoncodetool'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacestorageitem',
            name='agent_inline_surface',
            field=models.ForeignKey(help_text='AgentInlineSurface this storage permission entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='tables.agentinlinesurface'),
        ),
        migrations.AddField(
            model_name='agentinlinesurfacestorageitem',
            name='storage_file',
            field=models.ForeignKey(help_text='StorageFile whose access is being configured for this surface.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tables.storagefile'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfaceknowledge',
            constraint=models.UniqueConstraint(fields=('agent_inline_surface', 'collection'), name='uniq_agent_inline_surface_knowledge'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacemcptool',
            constraint=models.UniqueConstraint(fields=('agent_inline_surface', 'mcp_tool'), name='uniq_agent_inline_surface_mcp_tool'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacepythontool',
            constraint=models.UniqueConstraint(fields=('agent_inline_surface', 'python_tool'), name='uniq_agent_inline_surface_python_tool'),
        ),
        migrations.AddConstraint(
            model_name='agentinlinesurfacestorageitem',
            constraint=models.UniqueConstraint(fields=('agent_inline_surface', 'storage_file'), name='uniq_agent_inline_surface_storage_item'),
        ),
    ]
