# Generated by Django 5.1.3 on 2026-07-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0197_agentinlinesurface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknode',
            name='remember_output',
            field=models.BooleanField(default=False, help_text="If True, this task's output is remembered for the current run and injected as context into subsequently executed task nodes in the same session."),
        ),
    ]
