# Generated by Django 5.1.3 on 2026-06-19 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0197_collections_org_not_null"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="label",
            name="unique_label_name_per_level",
        ),
        migrations.RemoveConstraint(
            model_name="label",
            name="unique_top_level_label_name",
        ),
        migrations.AddField(
            model_name="label",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="label",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["org"], name="tables_labe_org_id_6074ba_idx"),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("org", "name", "parent"), name="unique_label_name_per_org_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("org", "name"),
                name="unique_top_level_label_name_per_org",
            ),
        ),
    ]
