# Generated by Django 5.1.3 on 2026-07-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0198_alter_tasknode_remember_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='max_consecutive_failures',
            field=models.IntegerField(default=None, help_text='Consecutive failed tool calls before graceful stop. Null falls back to DefaultAgentDefinitionConfig.', null=True),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='max_tool_calls',
            field=models.IntegerField(default=None, help_text='Max tool calls executed per loop iteration. Null falls back to DefaultAgentDefinitionConfig.', null=True),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='tool_timeout',
            field=models.IntegerField(default=None, help_text='Per-tool-call timeout in seconds. Null falls back to DefaultAgentDefinitionConfig.', null=True),
        ),
        migrations.AddField(
            model_name='defaultagentdefinitionconfig',
            name='max_consecutive_failures',
            field=models.IntegerField(default=3, help_text='Default consecutive tool-failure limit when AgentDefinition.max_consecutive_failures is null. Null = disabled.', null=True),
        ),
        migrations.AddField(
            model_name='defaultagentdefinitionconfig',
            name='max_tool_calls',
            field=models.IntegerField(default=15, help_text='Default max tool calls executed per loop iteration when AgentDefinition.max_tool_calls is null. Null = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='defaultagentdefinitionconfig',
            name='tool_timeout',
            field=models.IntegerField(default=300, help_text='Default per-tool-call timeout in seconds when AgentDefinition.tool_timeout is null. Null = no timeout.', null=True),
        ),
    ]
