# Generated by Django 5.1.3 on 2026-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0199_agentdefinition_max_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='schema_max_retries',
            field=models.IntegerField(default=None, help_text='Max retries when enforcing structured-output schema validation. Null falls back to DefaultAgentDefinitionConfig.', null=True),
        ),
        migrations.AddField(
            model_name='defaultagentdefinitionconfig',
            name='schema_max_retries',
            field=models.IntegerField(default=None, help_text='Default max schema-enforcement retries when AgentDefinition.schema_max_retries is null.', null=True),
        ),
    ]
