# Generated by Django 5.1.7 on 2026-07-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0199_agentdefinition_max_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecollection',
            name='status',
            field=models.CharField(choices=[('empty', 'Empty'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('warning', 'Warning'), ('failed', 'Failed')], default='empty', max_length=20),
        ),
    ]
