# Generated by Django 5.1.7 on 2026-07-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0189_alter_flowassistant_id_and_more"),
        ("tables", "0200_labels_org_not_null"),
    ]

    operations = []
