# Generated by Django 5.1.7 on 2026-07-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0190_merge_change_classificationconditiongroup_prompt_id_field_type_3",
        ),
        ("tables", "0201_merge_rbac_org_scoped_migrations_2"),
    ]

    operations = []
