# Generated by Django 5.1.7 on 2026-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0202_merge_rbac_org_scoped_migrations_3"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="graphorganization",
            name="unique_organization_per_flow",
        ),
        migrations.RenameField(
            model_name="graph",
            old_name="persistent_variables",
            new_name="enable_persistent_variables",
        ),
        migrations.RemoveField(
            model_name="graphorganization",
            name="organization",
        ),
        migrations.AddConstraint(
            model_name="graphorganization",
            constraint=models.UniqueConstraint(
                fields=("graph",), name="unique_persistent_state_per_flow"
            ),
        ),
    ]
