# Generated by Django 5.1.7 on 2026-07-15 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def truncate_api_keys(apps, schema_editor):
    # Pre-GA reset: old rows carry HMAC-SECRET_KEY hashes that can never
    # match the new SHA-256 lookup, and NULL-owner user-type rows violate
    # api_key_type_invariants. The system key re-seeds on next startup.
    apps.get_model("tables", "ApiKey").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0202_merge_rbac_org_scoped_migrations_3"),
    ]

    operations = [
        migrations.RunPython(truncate_api_keys, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="apikey",
            name="tables_apik_prefix_fbdead_idx",
        ),
        migrations.RemoveField(
            model_name="apikey",
            name="scopes",
        ),
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="key_type",
            field=models.CharField(
                choices=[("system", "System"), ("user", "User")],
                default="user",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("created_by__isnull", False), ("key_type", "user")),
                    models.Q(
                        ("created_by__isnull", True),
                        ("expires_at__isnull", True),
                        ("key_type", "system"),
                    ),
                    _connector="OR",
                ),
                name="api_key_type_invariants",
            ),
        ),
    ]
