# Generated by Django 5.1.7 on 2026-07-16 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0202_merge_rbac_org_scoped_migrations_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythoncoderesult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pythoncoderesult",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pythoncoderesult",
            name="finished_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="pythoncoderesult",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddField(
            model_name="pythoncoderesult",
            name="python_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="tables.pythoncode",
            ),
        ),
        migrations.AddField(
            model_name="pythoncoderesult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="pythoncoderesult",
            name="returncode",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name="pythoncoderesult",
            index=models.Index(fields=["org"], name="tables_pyth_org_id_18d84b_idx"),
        ),
    ]
