# Generated by Django 5.1.7 on 2026-07-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0191_merge_0190_merge_20260605_0190_merge_20260624_1519"),
        ("tables", "0202_merge_rbac_org_scoped_migrations_3"),
    ]

    operations = []
