# Generated by Django 5.1.7 on 2026-07-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0193_voicesettings_voice_agent_definition"),
        ("tables", "0202_merge_rbac_org_scoped_migrations_3"),
    ]

    operations = []
