# Generated by Django 5.1.7 on 2026-07-19 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0203_merge_20260717_1529"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooktrigger",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webhooktrigger",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="tables.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="webhooktrigger",
            index=models.Index(fields=["org"], name="tables_webh_org_id_1fb918_idx"),
        ),
    ]
