# Generated by Django 5.1.7 on 2026-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0203_merge_20260721_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='resource_type',
            field=models.CharField(choices=[('organizations', 'Organizations'), ('flows', 'Flows'), ('agents', 'Agents'), ('tools', 'Tools'), ('knowledge_sources', 'Knowledge Sources'), ('files', 'Files'), ('projects', 'Projects'), ('llm_configs', 'LLM Configs'), ('secrets', 'Secrets'), ('users', 'Users'), ('roles', 'Roles'), ('surfaces', 'Surfaces')], max_length=32),
        ),
    ]
