# Generated by Django 5.1.7 on 2026-07-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0190_remove_defaultllmconfig_response_format_and_more"),
        ("tables", "0203_rbac_api_key_migration"),
    ]

    operations = []
