# Generated by Django 5.1.7 on 2026-07-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0203_remove_graphorganization_unique_organization_per_flow_and_more",
        ),
        ("tables", "0204_merge_api_key_migrations"),
    ]

    operations = []
