# Generated by Django 5.1.7 on 2026-07-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0203_pythoncoderesult_created_at_and_more'),
        ('tables', '0205_merge_persistent_variables_migrations'),
    ]

    operations = [
    ]
