# Generated by Django 5.1.7 on 2026-07-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0205_merge_persistent_variables_migrations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_label_name_per_org_level',
        ),
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_top_level_label_name_per_org',
        ),
        migrations.AddField(
            model_name='label',
            name='scope',
            field=models.CharField(choices=[('flow', 'Flow'), ('tool', 'Tool')], default='flow', help_text='Which independent label tree this label belongs to (Flow labels and Tool labels never share instances, even with the same name/parent).', max_length=10),
        ),
        migrations.AddField(
            model_name='mcptool',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='mcp_tools', to='tables.label'),
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='python_code_tools', to='tables.label'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('org', 'scope', 'name', 'parent'), name='unique_label_name_per_org_level'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('org', 'scope', 'name'), name='unique_top_level_label_name_per_org'),
        ),
    ]
