# Generated by Django 5.1.7 on 2026-07-20 14:23
#
# Migration A of 3 (schema -> backfill -> NOT NULL), same pattern as
# 0204_webhook_trigger_org_scoped.py / 0205 / 0206 for WebhookTrigger.
#
# Org scoping belongs on the generic parent `RealtimeChannel`, not on the
# `TwilioChannel` detail row: a bare RealtimeChannel (created before any
# detail row is attached — a real, tested two-step creation flow) must be
# visible to its own org from the moment it exists, and future channel
# types (WhatsApp, Telegram) should inherit org visibility uniformly from
# this one place instead of each duplicating it on their own detail model.
# This closes that drift by adding org + created_by to `realtime_channel`.
# Also folds in the `voice` choice added to ResourceType (RolePermission.
# resource_type is choices-only metadata; no DB-level change).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0206_webhook_trigger_org_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimechannel',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='realtimechannel',
            name='org',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='%(app_label)s_%(class)s_set',
                to='tables.organization',
            ),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='resource_type',
            field=models.CharField(
                choices=[
                    ('organizations', 'Organizations'),
                    ('flows', 'Flows'),
                    ('agents', 'Agents'),
                    ('tools', 'Tools'),
                    ('knowledge_sources', 'Knowledge Sources'),
                    ('files', 'Files'),
                    ('projects', 'Projects'),
                    ('llm_configs', 'LLM Configs'),
                    ('secrets', 'Secrets'),
                    ('users', 'Users'),
                    ('roles', 'Roles'),
                    ('voice', 'Voice'),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name='realtimechannel',
            index=models.Index(fields=['org'], name='realtime_ch_org_id_14c79a_idx'),
        ),
    ]
