# Generated by Django 5.1.7 on 2026-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0206_remove_label_unique_label_name_per_org_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='scope',
            field=models.CharField(choices=[('flow', 'Flow'), ('tool', 'Tool')], db_index=True, default='flow', help_text='Which independent label tree this label belongs to (Flow labels and Tool labels never share instances, even with the same name/parent).', max_length=10),
        ),
    ]
