# Generated by Django 5.1.7 on 2026-07-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0190_defaultllmconfig_api_version_and_more"),
        ("tables", "0206_merge_python_code_result_migrations"),
    ]

    operations = []
