# Generated by Django 5.1.7 on 2026-07-30 08:53

import django.db.models.deletion
from django.db import migrations, models


def _parse_entrypoint(entrypoint: str) -> tuple[str, int | None]:
    """Split `f"{node_name} #{id}"` from the trailing ` #<digits>` suffix.

    `node_name` may itself contain `#`, so only the LAST ` #` is treated as the
    id separator, and only when what follows it is all digits.
    """
    separator = " #"
    split_index = entrypoint.rfind(separator)
    if split_index == -1:
        return entrypoint, None
    node_name = entrypoint[:split_index]
    id_part = entrypoint[split_index + len(separator) :]
    if not id_part.isdigit():
        return entrypoint, None
    return node_name, int(id_part)


def backfill_session_triggers(apps, schema_editor):
    Session = apps.get_model("tables", "Session")
    SessionTrigger = apps.get_model("tables", "SessionTrigger")
    ScheduleTriggerNode = apps.get_model("tables", "ScheduleTriggerNode")
    WebhookTriggerNode = apps.get_model("tables", "WebhookTriggerNode")
    TelegramTriggerNode = apps.get_model("tables", "TelegramTriggerNode")

    schedule_node_ids = set(ScheduleTriggerNode.objects.values_list("id", flat=True))
    webhook_node_ids = set(WebhookTriggerNode.objects.values_list("id", flat=True))
    telegram_node_ids = set(TelegramTriggerNode.objects.values_list("id", flat=True))

    MANUAL = "manual"
    SCHEDULE = "schedule"
    WEBHOOK = "webhook"
    TELEGRAM = "telegram"
    PARENT_FLOW = "parent_flow"

    sessions = Session.objects.filter(trigger__isnull=True).iterator()

    batch = []
    for session in sessions:
        if session.parent_session_id is not None:
            trigger = SessionTrigger(
                session=session,
                trigger_type=PARENT_FLOW,
                triggered_by_session_id=session.parent_session_id,
            )
        elif session.entrypoint is not None:
            node_name, node_id = _parse_entrypoint(session.entrypoint)
            if node_id in schedule_node_ids:
                trigger = SessionTrigger(
                    session=session,
                    trigger_type=SCHEDULE,
                    node_name=node_name,
                    schedule_trigger_node_id=node_id,
                )
            elif node_id in webhook_node_ids:
                trigger = SessionTrigger(
                    session=session,
                    trigger_type=WEBHOOK,
                    node_name=node_name,
                    webhook_trigger_node_id=node_id,
                )
            elif node_id in telegram_node_ids:
                trigger = SessionTrigger(
                    session=session,
                    trigger_type=TELEGRAM,
                    node_name=node_name,
                    telegram_trigger_node_id=node_id,
                )
            else:
                # Node deleted (or entrypoint wasn't an id-suffixed name) — keep
                # the parsed name but fall back to MANUAL, matching the model's
                # documented behaviour for nodes that no longer exist.
                trigger = SessionTrigger(
                    session=session,
                    trigger_type=MANUAL,
                    node_name=node_name,
                )
        else:
            trigger = SessionTrigger(
                session=session,
                trigger_type=MANUAL,
                triggered_by_user_id=session.graph_user_id,
            )

        batch.append(trigger)
        if len(batch) >= 1000:
            SessionTrigger.objects.bulk_create(batch, batch_size=1000)
            batch = []

    if batch:
        SessionTrigger.objects.bulk_create(batch, batch_size=1000)


def delete_all_session_triggers(apps, schema_editor):
    SessionTrigger = apps.get_model("tables", "SessionTrigger")
    SessionTrigger.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0207_merge_20260724_1426"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("schedule", "Schedule"),
                            ("webhook", "Webhook"),
                            ("telegram", "Telegram"),
                            ("parent_flow", "Parent Flow"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "node_name",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("extra", models.JSONField(default=dict)),
                (
                    "schedule_trigger_node",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tables.scheduletriggernode",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger",
                        to="tables.session",
                    ),
                ),
                (
                    "telegram_trigger_node",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tables.telegramtriggernode",
                    ),
                ),
                (
                    "triggered_by_session",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tables.session",
                    ),
                ),
                (
                    "triggered_by_user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tables.graphorganizationuser",
                    ),
                ),
                (
                    "webhook_trigger_node",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tables.webhooktriggernode",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            backfill_session_triggers, reverse_code=delete_all_session_triggers
        ),
    ]
