# Generated by Django 5.1.7 on 2026-07-28 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0207_merge_20260724_1426"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=128)),
                ("value", models.CharField(editable=False, max_length=12000)),
                (
                    "tail",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=4
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tables.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(fields=["org"], name="tables_secr_org_id_794b5d_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("org", "name"), name="unique_secret_name_per_org"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value", ""), _negated=True),
                        name="secret_value_not_empty",
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tables_secret ALTER COLUMN org_id SET NOT NULL;",
            reverse_sql="ALTER TABLE tables_secret ALTER COLUMN org_id DROP NOT NULL;",
        ),
    ]
