# Generated by Django 5.1.7 on 2026-07-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0207_label_scope_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulttoolconfig',
            name='embedding_config',
        ),
        migrations.RemoveField(
            model_name='defaulttoolconfig',
            name='llm_config',
        ),
        migrations.AlterUniqueTogether(
            name='taskconfiguredtools',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskconfiguredtools',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskconfiguredtools',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='toolconfig',
            name='tool',
        ),
        migrations.AlterUniqueTogether(
            name='toolconfigfield',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='toolconfigfield',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='templateagent',
            name='configured_tools',
        ),
        migrations.DeleteModel(
            name='AgentConfiguredTools',
        ),
        migrations.DeleteModel(
            name='DefaultToolConfig',
        ),
        migrations.DeleteModel(
            name='TaskConfiguredTools',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='ToolConfigField',
        ),
        migrations.DeleteModel(
            name='ToolConfig',
        ),
    ]
