# Generated by Django 5.1.7 on 2026-08-12 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0208_sessiontrigger_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='use_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClassificationConditionGroupSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('classification_decision_table_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tables.classificationdecisiontablenode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='classificationconditiongroup',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_groups', to='tables.classificationconditiongroupsection'),
        ),
    ]
