# Generated by Django 5.1.7 on 2026-08-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0205_seed_surface_permissions"),
        ("tables", "0208_sessiontrigger_and_backfill"),
    ]

    operations = []
