# Generated by Django 5.1.7 on 2026-08-12 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0208_remove_legacy_tool_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythoncodetool',
            name='favorite',
        ),
        migrations.CreateModel(
            name='McpToolFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tables.mcptool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_mcp_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'tool'), name='unique_mcp_tool_favorite')],
            },
        ),
        migrations.CreateModel(
            name='PythonCodeToolFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tables.pythoncodetool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_python_code_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'tool'), name='unique_python_tool_favorite')],
            },
        ),
    ]
