# Generated by Django 5.1.7 on 2026-08-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tables",
            "0208_knowledgenode_knowledgenodegraphragbasicsearchconfig_and_more",
        ),
        ("tables", "0208_sessiontrigger_and_backfill"),
    ]

    operations = []
