# Generated by Django 5.1.7 on 2026-07-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0208_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultembeddingconfig",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="api_key",
        ),
    ]
