# Generated by Django 5.1.7 on 2026-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0208_sessiontrigger_and_backfill'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='graph',
            name='unique_graph_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='pythoncodetool',
            name='unique_pythoncodetool_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='sourcecollection',
            name='unique_collection_name_per_org',
        ),
        migrations.AddField(
            model_name='graph',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sourcecollection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sourcecollection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('org', 'name'), name='unique_graph_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='pythoncodetool',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('org', 'name'), name='unique_pythoncodetool_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='sourcecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('org', 'collection_name'), name='unique_collection_name_per_org'),
        ),
    ]
