# Generated by Django 5.1.7 on 2026-08-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0209_merge_20260807_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecollection',
            name='description',
            field=models.TextField(blank=True, default='', help_text="LLM-facing context describing this collection's contents. Appended to the description of every knowledge tool generated for this collection so agents know when to use it. Blank means no extra context is added."),
        ),
    ]
