# Generated by Django 5.1.7 on 2026-08-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0209_classificationdecisiontablenode_use_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationdecisiontablenode',
            name='use_storage',
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='post_use_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='pre_use_storage',
            field=models.BooleanField(default=False),
        ),
    ]
