# Generated by Django 5.1.7 on 2026-08-11 15:26
# EST-3341: OrganizationConfig split from Organization to keep the core
# identity model lean as more settings accumulate over time.

import django.db.models.deletion
from django.db import migrations, models


def backfill_organization_config(apps, schema_editor):
    """Every Organization created before this migration needs a config
    row too - the model default (0) only applies to NEW rows, it doesn't
    retroactively create one for existing organizations."""
    Organization = apps.get_model("tables", "Organization")
    OrganizationConfig = apps.get_model("tables", "OrganizationConfig")

    OrganizationConfig.objects.bulk_create(
        [
            OrganizationConfig(org=org, audit_retention_days=0)
            for org in Organization.objects.exclude(config__isnull=False)
        ]
    )


def noop_reverse(apps, schema_editor):
    # No-op: CreateModel's own reverse (DropModel) already removes the
    # table and every row in it - nothing extra to undo here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0209_seed_audit_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationConfig',
            fields=[
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='tables.organization')),
                ('audit_retention_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'rbac_organization_config',
            },
        ),
        migrations.RunPython(backfill_organization_config, noop_reverse),
        migrations.AlterField(
            model_name='rolepermission',
            name='resource_type',
            field=models.CharField(choices=[('organizations', 'Organizations'), ('flows', 'Flows'), ('agents', 'Agents'), ('tools', 'Tools'), ('knowledge_sources', 'Knowledge Sources'), ('files', 'Files'), ('projects', 'Projects'), ('llm_configs', 'LLM Configs'), ('secrets', 'Secrets'), ('users', 'Users'), ('roles', 'Roles'), ('audit', 'Audit')], max_length=32),
        ),
    ]
