# Generated by Django 5.1.7 on 2026-07-29 12:36
# Hand-edited: inserted migrate_sensitive_fields_to_secrets (RunPython) between
# the AddField and RemoveField operations, and folded in the RemoveField
# operations originally generated as a separate migration
# (0211_remove_embeddingconfig_api_key_and_more.py, deleted — never applied).
# See docs/superpowers/plans/2026-07-29-secret-management-sensitive-field-fk-wiring.md
# Task 2.

import django.db.models.deletion
from django.db import migrations, models
from loguru import logger
from tables.services.secrets import secret_encryption


def migrate_sensitive_fields_to_secrets(apps, schema_editor):
    Secret = apps.get_model("tables", "Secret")
    Graph = apps.get_model("tables", "Graph")

    def _migrate(
        queryset,
        model_label,
        field_name,
        fk_name,
        org_id_getter,
        created_by_id_getter=lambda o: o.created_by_id,
    ):
        base_name = f"{model_label}-{field_name.replace('_', '-')}"
        counts_by_org = {}
        for instance in queryset.order_by("pk"):
            raw_value = getattr(instance, field_name)
            if not raw_value:
                continue
            org_id = org_id_getter(instance)
            if org_id is None:
                logger.warning(
                    f"Skipping {model_label} pk={instance.pk}: no resolvable "
                    f"org for {field_name}"
                )
                continue
            count = counts_by_org.get(org_id, 0) + 1
            counts_by_org[org_id] = count
            name = base_name if count == 1 else f"{base_name}-{count}"
            secret = Secret(
                org_id=org_id,
                name=name,
                created_by_id=created_by_id_getter(instance),
            )
            secret_encryption.encrypt(text=raw_value).write_to(secret)
            secret.save()
            setattr(instance, fk_name, secret)
            instance.save(update_fields=[fk_name])

    LLMConfig = apps.get_model("tables", "LLMConfig")
    _migrate(
        LLMConfig.objects.all(),
        "llmconfig",
        "api_key",
        "api_key_secret",
        lambda o: o.org_id,
    )

    EmbeddingConfig = apps.get_model("tables", "EmbeddingConfig")
    _migrate(
        EmbeddingConfig.objects.all(),
        "embeddingconfig",
        "api_key",
        "api_key_secret",
        lambda o: o.org_id,
    )

    RealtimeConfig = apps.get_model("tables", "RealtimeConfig")
    _migrate(
        RealtimeConfig.objects.all(),
        "realtimeconfig",
        "api_key",
        "api_key_secret",
        lambda o: o.org_id,
    )

    RealtimeTranscriptionConfig = apps.get_model(
        "tables", "RealtimeTranscriptionConfig"
    )
    _migrate(
        RealtimeTranscriptionConfig.objects.all(),
        "realtimetranscriptionconfig",
        "api_key",
        "api_key_secret",
        lambda o: o.org_id,
    )

    TelegramTriggerNode = apps.get_model("tables", "TelegramTriggerNode")

    def _telegram_org_id(instance):
        graph = Graph.objects.filter(pk=instance.graph_id).first()
        return graph.org_id if graph else None

    def _telegram_created_by_id(instance):
        graph = Graph.objects.filter(pk=instance.graph_id).first()
        return graph.created_by_id if graph else None

    _migrate(
        TelegramTriggerNode.objects.all(),
        "telegramtriggernode",
        "telegram_bot_api_key",
        "telegram_bot_api_key_secret",
        _telegram_org_id,
        _telegram_created_by_id,
    )

    McpTool = apps.get_model("tables", "McpTool")
    _migrate(
        McpTool.objects.all(),
        "mcptool",
        "auth",
        "auth_secret",
        lambda o: o.org_id,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0209_remove_defaultembeddingconfig_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingconfig",
            name="api_key_secret",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="embedding_configs",
                to="tables.secret",
            ),
        ),
        migrations.AddField(
            model_name="llmconfig",
            name="api_key_secret",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="llm_configs",
                to="tables.secret",
            ),
        ),
        migrations.AddField(
            model_name="mcptool",
            name="auth_secret",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mcp_tools",
                to="tables.secret",
            ),
        ),
        migrations.AddField(
            model_name="realtimeconfig",
            name="api_key_secret",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="realtime_configs",
                to="tables.secret",
            ),
        ),
        migrations.AddField(
            model_name="realtimetranscriptionconfig",
            name="api_key_secret",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="realtime_transcription_configs",
                to="tables.secret",
            ),
        ),
        migrations.AddField(
            model_name="telegramtriggernode",
            name="telegram_bot_api_key_secret",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_trigger_nodes",
                to="tables.secret",
            ),
        ),
        migrations.RunPython(
            migrate_sensitive_fields_to_secrets,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="embeddingconfig",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="mcptool",
            name="auth",
        ),
        migrations.RemoveField(
            model_name="realtimeconfig",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="realtimetranscriptionconfig",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="telegramtriggernode",
            name="telegram_bot_api_key",
        ),
    ]
