# Generated by Django 5.1.7 on 2026-08-18 11:15

from django.db import migrations, models


def rename_users_to_memberships(apps, schema_editor):
    """Rename the `users` permission resource_type to `memberships` — the bits
    have always governed org membership, not the user account entity."""
    RolePermission = apps.get_model("tables", "RolePermission")
    RolePermission.objects.filter(resource_type="users").update(
        resource_type="memberships"
    )


def rename_memberships_to_users(apps, schema_editor):
    RolePermission = apps.get_model("tables", "RolePermission")
    RolePermission.objects.filter(resource_type="memberships").update(
        resource_type="users"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0209_seed_org_admin_organizations_perm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("organizations", "Organizations"),
                    ("flows", "Flows"),
                    ("agents", "Agents"),
                    ("tools", "Tools"),
                    ("knowledge_sources", "Knowledge Sources"),
                    ("files", "Files"),
                    ("projects", "Projects"),
                    ("llm_configs", "LLM Configs"),
                    ("secrets", "Secrets"),
                    ("memberships", "Members"),
                    ("roles", "Roles"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            rename_users_to_memberships, rename_memberships_to_users
        ),
    ]
