# Generated by Django 5.1.7 on 2026-07-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0207_merge_20260724_1426'),
        ('tables', '0210_seed_voice_role_permissions'),
    ]

    operations = [
    ]
