# Generated by Django 5.1.7 on 2026-08-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0208_sessiontrigger_and_backfill'),
        ('tables', '0210_seed_tools_export_permission'),
    ]

    operations = [
    ]
