# Generated by Django 5.1.7 on 2026-08-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0210_sourcecollection_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeAgentNode',
        ),
    ]
