# Generated by Django 5.1.7 on 2026-08-31 09:13

from django.db import migrations


def purge_superadmin_memberships(apps, schema_editor):
    """Superadmins reach every organization through the permission bypass, so a
    membership row grants nothing. Rows created before that became enforced are
    removed. The bootstrap row is kept: it carries the built-in Superadmin role
    rather than describing a superadmin holding a lesser one."""
    OrganizationUser = apps.get_model("tables", "OrganizationUser")
    OrganizationUser.objects.filter(user__is_superadmin=True).exclude(
        role__name="Superadmin", role__is_built_in=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0210_alter_rolepermission_resource_type"),
    ]

    operations = [
        migrations.RunPython(purge_superadmin_memberships, migrations.RunPython.noop),
    ]
