# Generated by Django 5.1.7 on 2026-08-17 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0211_grant_org_admin_organizations_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('filter_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tables.organization')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['org'], name='tables_audi_org_id_dd7995_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'created_by', 'name'), name='unique_audit_filter_preset_name_per_user')],
            },
        ),
    ]
