# Generated by Django 5.1.7 on 2026-08-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0210_sourcecollection_description'),
        ('tables', '0211_merge_20260818_1204'),
    ]

    operations = [
    ]
