# Generated by Django 5.1.7 on 2026-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0211_scrub_plaintext_from_graph_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="pythoncode",
            name="secrets",
            field=models.ManyToManyField(
                blank=True, related_name="python_codes", to="tables.secret"
            ),
        ),
    ]
