# Generated by Django 5.1.7 on 2026-08-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0211_merge_20260729_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevenlabsrealtimeconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elevenlabsrealtimeconfig',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tables.organization'),
        ),
        migrations.AddField(
            model_name='geminirealtimeconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geminirealtimeconfig',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tables.organization'),
        ),
        migrations.AddField(
            model_name='openairealtimeconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openairealtimeconfig',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tables.organization'),
        ),
        migrations.AddIndex(
            model_name='elevenlabsrealtimeconfig',
            index=models.Index(fields=['org'], name='elevenlabs__org_id_b9db62_idx'),
        ),
        migrations.AddIndex(
            model_name='geminirealtimeconfig',
            index=models.Index(fields=['org'], name='gemini_real_org_id_72f6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='openairealtimeconfig',
            index=models.Index(fields=['org'], name='openai_real_org_id_55b18e_idx'),
        ),
    ]
