# Generated by Django 5.1.7 on 2026-09-02 14:38

from django.db import migrations, models

from tables.models.rbac_models.rbac_enums import BuiltInRole

# Permission.READ | Permission.DELETE — view a key's record and retire it.
API_KEYS_READ_DELETE = 10


def seed_org_admin_api_keys_perm(apps, schema_editor):
    Role = apps.get_model("tables", "Role")
    RolePermission = apps.get_model("tables", "RolePermission")
    role = Role.objects.filter(
        name=BuiltInRole.ORG_ADMIN, is_built_in=True, org__isnull=True
    ).first()
    if role is None:
        return
    RolePermission.objects.update_or_create(
        role=role,
        resource_type="api_keys",
        defaults={"permissions": API_KEYS_READ_DELETE},
    )


def unseed_org_admin_api_keys_perm(apps, schema_editor):
    Role = apps.get_model("tables", "Role")
    RolePermission = apps.get_model("tables", "RolePermission")
    role = Role.objects.filter(
        name=BuiltInRole.ORG_ADMIN, is_built_in=True, org__isnull=True
    ).first()
    if role is None:
        return
    RolePermission.objects.filter(role=role, resource_type="api_keys").update(
        permissions=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0211_purge_superadmin_memberships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("organizations", "Organizations"),
                    ("flows", "Flows"),
                    ("agents", "Agents"),
                    ("tools", "Tools"),
                    ("knowledge_sources", "Knowledge Sources"),
                    ("files", "Files"),
                    ("projects", "Projects"),
                    ("llm_configs", "LLM Configs"),
                    ("secrets", "Secrets"),
                    ("memberships", "Members"),
                    ("roles", "Roles"),
                    ("api_keys", "API Keys"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            seed_org_admin_api_keys_perm,
            unseed_org_admin_api_keys_perm,
        ),
    ]
