# Generated by Django 5.1.7 on 2026-08-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0208_sessiontrigger_and_backfill'),
        ('tables', '0212_pythoncode_secrets'),
    ]

    operations = [
    ]
