# Generated by Django 5.1.7 on 2026-08-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0210_sourcecollection_description'),
        ('tables', '0213_merge_secrets'),
    ]

    operations = [
    ]
