# Generated by Django 5.1.7 on 2026-08-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0211_delete_codeagentnode'),
        ('tables', '0214_merge_secrets_2'),
    ]

    operations = [
    ]
