# Generated by Django 5.1.7 on 2026-08-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0210_sourcecollection_description'),
        ('tables', '0214_realtime_provider_configs_org_not_null'),
    ]

    operations = [
    ]
