# Generated by Django 5.1.7 on 2026-08-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0214_merge_secrets_2'),
        ('tables', '0194_graphrag_slot'),
    ]

    operations = [
    ]
