# Generated by Django 5.1.7 on 2026-08-24 12:13

import django.db.models.deletion
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0214_merge_secrets_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('rag_type', models.CharField(blank=True, choices=[('naive', 'Naive'), ('graph', 'Graph')], default=None, max_length=30, null=True)),
                ('rag_id', models.IntegerField(blank=True, default=None, null=True)),
                ('query', models.TextField(blank=True, default='')),
                ('search_method', models.CharField(blank=True, choices=[('basic', 'Basic Search'), ('local', 'Local Search')], default=None, max_length=10, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_node_list', to='tables.graph')),
                ('source_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.sourcecollection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNodeGraphRagBasicSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The basic search prompt to use.', null=True)),
                ('k', models.IntegerField(default=10, help_text='The number of text units to include in search context.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
                ('knowledge_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_basic_search_config', to='tables.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_node_graph_basic_search_config',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNodeGraphRagLocalSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, default=None, help_text='The local search prompt to use.', null=True)),
                ('text_unit_prop', models.FloatField(default=0.5, help_text='The text unit proportion.')),
                ('community_prop', models.FloatField(default=0.15, help_text='The community proportion.')),
                ('conversation_history_max_turns', models.IntegerField(default=5, help_text='The conversation history maximum turns.')),
                ('top_k_entities', models.IntegerField(default=10, help_text='The top k mapped entities.')),
                ('top_k_relationships', models.IntegerField(default=10, help_text='The top k mapped relations.')),
                ('max_context_tokens', models.IntegerField(default=12000, help_text='The maximum tokens.')),
                ('knowledge_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph_local_search_config', to='tables.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_node_graph_local_search_config',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNodeNaiveRagSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_limit', models.PositiveIntegerField(blank=True, default=3, help_text='Integer between 0 and 1000 for knowledge')),
                ('similarity_threshold', models.DecimalField(blank=True, decimal_places=2, default=0.2, help_text='Float between 0.00 and 1.00 for knowledge', max_digits=3)),
                ('knowledge_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='naive_search_config', to='tables.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_node_naive_search_config',
            },
        ),
    ]
