# Generated by Django 5.1.7 on 2026-08-21 08:56

from django.db import migrations, models


def drop_stale_tokens(apps, schema_editor):
    """Empty the table before `token_hash` is added.

    Existing rows hold plaintext tokens that cannot be converted: the hash
    cannot be derived without re-issuing, and reusing the UUID as the raw
    value would preserve the weakness this migration exists to fix.
    """
    apps.get_model("tables", "PasswordResetToken").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0214_merge_secrets_2"),
    ]

    operations = [
        migrations.RunPython(drop_stale_tokens, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="is_used",
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="token",
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="token_hash",
            field=models.CharField(default="", max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
