# Generated by Django 5.1.7 on 2026-08-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0215_merge_20260818_1723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhooktrigger',
            unique_together={('org', 'path', 'provider_type')},
        ),
    ]
