# Generated by Django 5.1.7 on 2026-08-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0215_knowledgenode_knowledgenodegraphragbasicsearchconfig_and_more'),
        ('tables', '0215_password_reset_token_hash'),
    ]

    operations = [
    ]
