# Generated by Django 5.1.7 on 2026-08-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0215_merge_0211_delete_codeagentnode_0214_merge_secrets_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewnode',
            name='stream_config',
        ),
        migrations.RemoveField(
            model_name='pythonnode',
            name='stream_config',
        ),
    ]
