# Generated by Django 5.1.7 on 2026-08-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0193_llmconfig_context_window_and_more"),
        ("tables", "0215_merge_graphrag_slot"),
    ]

    operations = []
