# Generated by Django 5.1.7 on 2026-08-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0216_merge_20260824_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphragbasicsearchconfig',
            name='is_suggested',
            field=models.BooleanField(default=False, help_text='Whether these values came from parameter suggestion.'),
        ),
        migrations.AddField(
            model_name='graphragdriftsearchconfig',
            name='is_suggested',
            field=models.BooleanField(default=False, help_text='Whether these values came from parameter suggestion.'),
        ),
        migrations.AddField(
            model_name='graphragglobalsearchconfig',
            name='is_suggested',
            field=models.BooleanField(default=False, help_text='Whether these values came from parameter suggestion.'),
        ),
        migrations.AddField(
            model_name='graphraglocalsearchconfig',
            name='is_suggested',
            field=models.BooleanField(default=False, help_text='Whether these values came from parameter suggestion.'),
        ),
        migrations.AddField(
            model_name='naiveragsearchconfig',
            name='is_suggested',
            field=models.BooleanField(default=False, help_text='Whether these values came from parameter suggestion.'),
        ),
    ]
