# Generated by Django 5.1.7 on 2026-08-19 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0217_realtimeagentdefinition_provider_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesessionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realtimesessionitem',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tables.organization'),
        ),
        migrations.AddIndex(
            model_name='realtimesessionitem',
            index=models.Index(fields=['org'], name='realtime_se_org_id_d1da6a_idx'),
        ),
    ]
