# Generated by Django 5.1.7 on 2026-08-21 10:40
# Split out from the auto-generated 0222 (which bundled this unrelated
# RBAC ResourceType.choices drift together with the new WebhookNodeAuth
# model) so each migration has a single, reviewable concern. This one is
# metadata-only (choices validation lives in Django, not the DB), pre-dates
# the webhook-auth work, and reflects a ResourceType choice (voice/surfaces)
# added earlier in this branch without a migration.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0221_voice_settings_twilio_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='resource_type',
            field=models.CharField(choices=[('organizations', 'Organizations'), ('flows', 'Flows'), ('agents', 'Agents'), ('tools', 'Tools'), ('knowledge_sources', 'Knowledge Sources'), ('files', 'Files'), ('projects', 'Projects'), ('llm_configs', 'LLM Configs'), ('secrets', 'Secrets'), ('users', 'Users'), ('roles', 'Roles'), ('voice', 'Voice'), ('surfaces', 'Surfaces')], max_length=32),
        ),
    ]
