# Generated by Django 5.1.7 on 2026-08-21 10:40
# Split out from the auto-generated 0222 -- this is the actual webhook-auth
# feature migration (EST-1869): adds WebhookNodeAuth, one row per
# TelegramTriggerNode/WebhookTriggerNode, holding the inbound-request
# credential for that node (PBKDF2 hash for Telegram's static secret_token,
# raw signing secret for the generic HMAC-SHA256 scheme).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0222_alter_rolepermission_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookNodeAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('scheme', models.CharField(choices=[('static_header', 'Static Header'), ('hmac_sha256', 'Hmac Sha256')], max_length=32)),
                ('header_name', models.CharField(max_length=128)),
                ('timestamp_header_name', models.CharField(blank=True, default='X-Webhook-Timestamp', max_length=128)),
                ('tolerance_seconds', models.PositiveIntegerField(default=300)),
                ('secret_hash', models.CharField(blank=True, help_text='One-way hash of the token. Never exposed.', max_length=128, null=True)),
                ('signing_secret', models.CharField(blank=True, help_text='Plaintext or symmetrically encrypted secret required to compute HMAC signatures.', max_length=255, null=True)),
                ('telegram_trigger_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_node_auth', to='tables.telegramtriggernode')),
                ('webhook_trigger_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_node_auth', to='tables.webhooktriggernode')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('telegram_trigger_node__isnull', False), ('webhook_trigger_node__isnull', True)), models.Q(('telegram_trigger_node__isnull', True), ('webhook_trigger_node__isnull', False)), _connector='OR'), name='webhook_node_auth_exactly_one_node')],
            },
        ),
    ]
