# Generated by Django 5.1.7 on 2026-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0223_webhooknodeauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooknodeauth',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
