# Generated by Django 5.1.7 on 2026-08-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0224_webhooknodeauth_enabled_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooknodeauth',
            name='registered_webhook_trigger_id',
            field=models.PositiveBigIntegerField(blank=True, help_text="The WebhookTrigger id this credential's outbound setWebhook call (Telegram only) last targeted. Lets a resync detect a genuine path/tunnel change vs. an unrelated node resave, so ordinary resaves don't re-hit Telegram's setWebhook endpoint and rotate the secret needlessly.", null=True),
        ),
    ]
