# Generated by Django 5.1.7 on 2026-08-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0225_webhooknodeauth_registered_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooknodeauth',
            name='registered_webhook_trigger_id',
        ),
        migrations.AddField(
            model_name='webhooknodeauth',
            name='registered_webhook_url',
            field=models.CharField(blank=True, help_text="The full callback URL this credential's outbound setWebhook call (Telegram only) last targeted. Lets a resync detect a genuine tunnel URL change -- even one where the underlying WebhookTrigger row is unchanged (e.g. the tunnel's domain rotated) -- vs. an unrelated node resave, so ordinary resaves don't re-hit Telegram's setWebhook endpoint and rotate the secret needlessly.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webhooknodeauth',
            name='registered_bot_api_key_secret_id',
            field=models.PositiveBigIntegerField(blank=True, help_text="The Secret id of the `telegram_bot_api_key` this credential's outbound setWebhook call (Telegram only) last targeted. Lets a resync detect the node being repointed at a different Telegram bot even when the URL/tunnel is unchanged, so the new bot still gets a real setWebhook call instead of being skipped as 'already registered'.", null=True),
        ),
    ]
