# Generated by Django 5.1.7 on 2026-08-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0215_password_reset_token_hash'),
        ('tables', '0226_webhooknodeauth_registered_url'),
    ]

    operations = [
    ]
