# Generated by Django 5.1.7 on 2026-08-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0217_graphragbasicsearchconfig_is_suggested_and_more'),
        ('tables', '0228_realtime_provider_config_api_key_secret'),
    ]

    operations = [
    ]
