# Generated by Django 5.1.7 on 2026-08-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0212_merge_20260818_1744'),
        ('tables', '0228_realtime_provider_config_api_key_secret'),
    ]

    operations = [
    ]
