# Generated by Django 5.1.7 on 2026-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0229_merge_20260826_1341'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='graph',
            name='unique_graph_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='pythoncodetool',
            name='unique_pythoncodetool_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='sourcecollection',
            name='unique_collection_name_per_org',
        ),
        migrations.RemoveField(
            model_name='graphversion',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='graphversion',
            name='is_active',
        ),
        migrations.AddField(
            model_name='agentgraphrag',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agentgraphrag',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentnaiverag',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agentnaiverag',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentnode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agentnode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentnodetask',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agentnodetask',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentpythoncodetoolconfigs',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agentpythoncodetoolconfigs',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentpythoncodetools',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agentpythoncodetools',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='audiotranscriptionnode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='audiotranscriptionnode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='baseragtype',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='baseragtype',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='classificationdecisiontableprompt',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='classificationdecisiontableprompt',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='codeagentnode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='codeagentnode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='condition',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='crewnode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='crewnode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='edge',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='endnode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='endnode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='fileextractornode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='fileextractornode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='flowassistant',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='flowassistant',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='flowassistantconversation',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='flowassistantconversation',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='flowassistantmessage',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='flowassistantmessage',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='graph',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='graphnote',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='graphnote',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='graphorganization',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='graphorganization',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='graphorganizationuser',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='graphorganizationuser',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='graphrag',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='graphrag',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='graphragdocument',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='graphragdocument',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='graphstoragefile',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='graphstoragefile',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='graphversion',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='graphversion',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='naiverag',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='naiverag',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragchunk',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='naiveragchunk',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragembedding',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='naiveragembedding',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='naiveragpreviewchunk',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='naiveragpreviewchunk',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pythoncodetoolconfig',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pythoncodetoolconfig',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduletriggernode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='scheduletriggernode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sourcecollection',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sourcecollection',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='startnode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='startnode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='subgraphnode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='subgraphnode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tasknode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tasknode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskpythoncodetoolconfigs',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='taskpythoncodetoolconfigs',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='taskpythoncodetools',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='taskpythoncodetools',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramtriggernode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='telegramtriggernode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramtriggernodefield',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='telegramtriggernodefield',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='webhooktriggernode',
            name='is_soft_deleted',
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webhooktriggernode',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.UniqueConstraint(condition=models.Q(('is_soft_deleted', False)), fields=('org', 'name'), name='unique_graph_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='pythoncodetool',
            constraint=models.UniqueConstraint(condition=models.Q(('is_soft_deleted', False)), fields=('org', 'name'), name='unique_pythoncodetool_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='sourcecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_soft_deleted', False)), fields=('org', 'collection_name'), name='unique_collection_name_per_org'),
        ),
    ]
