# Generated by Django 5.1.7 on 2026-08-27 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0229_merge_20260826_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimechannel',
            name='realtime_agent_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='tables.realtimeagentdefinition'),
        ),
    ]
