# Generated by Django 5.1.7 on 2026-08-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0229_merge_20260826_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='openairealtimeconfig',
            name='base_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
