# Generated by Django 5.1.7 on 2026-08-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0230_realtimechannel_realtime_agent_definition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceSettings',
        ),
    ]
