# Generated by Django 5.1.7 on 2026-08-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0230_merge_20260826_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='system',
            field=models.BooleanField(default=False, editable=False, help_text='Infrastructure secret (e.g. org-level MinIO credentials) managed internally by storage_credentials. Never exposed through the user-facing Secret API.'),
        ),
    ]
