# Generated by Django 5.1.7 on 2026-08-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0212_create_audit_filter_preset'),
        ('tables', '0230_merge_20260826_1600'),
    ]

    operations = [
    ]
