# Generated by Django 5.1.7 on 2026-08-31 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0230_merge_20260826_1600'),
        ('tables', '0231_delete_voicesettings'),
    ]

    operations = [
    ]
