# Generated by Django 5.1.7 on 2026-08-31 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # No RunPython backfill from the old WebhookNodeAuth rows into the new
    # WebhookTriggerAuth table -- accepted loss, not an oversight: at the time this ran,
    # no install had webhooks in real use, so there was no pre-existing trigger auth
    # data worth migrating. An install upgrading past this point with a PRE-EXISTING
    # webhook trigger gets 401 on inbound calls until set_trigger_auth_secret is called
    # again for that trigger (see converter_service.py's auth resolution and
    # webhook_routes.py's 401 branch). Known, accepted at filing time (Vinik Pooh,
    # 2026-09-30) -- do not re-open as a missed backfill without new information (e.g.
    # evidence that installs upgrading now do carry real pre-existing trigger auth).

    dependencies = [
        ('tables', '0232_merge_20260828_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTriggerAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('webhook', 'Webhook'), ('telegram', 'Telegram'), ('twilio', 'Twilio')], max_length=16)),
                ('registered_webhook_url', models.CharField(blank=True, max_length=500, null=True)),
                ('registered_bot_api_key_secret_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('registered_secret_id', models.PositiveBigIntegerField(blank=True, help_text="The `secret_id` this credential's outbound setWebhook call (Telegram only) last targeted. The user can change `secret` at any time via the trigger API -- comparing against this lets a resync detect that change and re-push to Telegram, even when the URL and bot key are both unchanged.", null=True)),
                ('secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_trigger_auths', to='tables.secret')),
                ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='tables.webhooktrigger')),
            ],
        ),
        migrations.DeleteModel(
            name='WebhookNodeAuth',
        ),
    ]
