# Generated by Django 5.1.7 on 2026-09-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0229_merge_20260827_1117'),
        ('tables', '0232_merge_20260828_1754'),
    ]

    operations = [
    ]
