# Generated by Django 5.1.7 on 2026-09-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0232_merge_20260828_1754'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='secret',
            name='unique_secret_name_per_org',
        ),
        migrations.AddField(
            model_name='secret',
            name='system',
            field=models.BooleanField(default=False, editable=False, help_text='Infrastructure secret (e.g. org-level MinIO credentials) managed internally by storage_credentials. Never exposed through the user-facing Secret API.'),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(condition=models.Q(('system', False)), fields=('org', 'name'), name='unique_secret_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(condition=models.Q(('system', True)), fields=('org', 'name'), name='unique_system_secret_name_per_org'),
        ),
    ]
