# Generated by Django 5.1.7 on 2026-09-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0230_openai_realtime_config_base_url'),
        ('tables', '0232_merge_20260828_1754'),
    ]

    operations = [
    ]
