# Generated by Django 5.1.7 on 2026-08-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0215_knowledgenode_knowledgenodegraphragbasicsearchconfig_and_more'),
        ('tables', '0232_merge_20260828_1754'),
    ]

    operations = [
    ]
