# Generated by Django 5.1.7 on 2026-09-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0233_knowledge_node"),
        ("tables", "0233_merge_20260901_1022"),
    ]

    operations = []
