# Generated by Django 5.1.7 on 2026-09-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0232_alter_rolepermission_resource_type'),
        ('tables', '0234_merge_knowledge_node_and_agent_node_migrations'),
    ]

    operations = [
    ]
