# Generated by Django 5.1.7 on 2026-09-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0233_webhook_trigger_auth'),
        ('tables', '0234_merge_knowledge_node_and_agent_node_migrations'),
    ]

    operations = [
    ]
