# Generated by Django 5.1.7 on 2026-09-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0211_purge_superadmin_memberships"),
        ("tables", "0234_merge_knowledge_node_and_agent_node_migrations"),
    ]

    operations = []
