# Generated by Django 5.1.7 on 2026-09-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0209_classificationdecisiontablenode_post_use_storage_and_more'),
        ('tables', '0234_merge_knowledge_node_and_agent_node_migrations'),
    ]

    operations = [
    ]
