# Generated by Django 5.1.7 on 2026-09-02 13:17
# Pure DDL. Every data fixup this depends on lives in
# 0235_adopt_orphan_provider_models: Postgres refuses to ALTER TABLE a table
# that has pending trigger events from DML earlier in the same transaction.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0235_adopt_orphan_provider_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="embeddingmodel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="llmmodel",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="embeddingmodel",
            constraint=models.UniqueConstraint(
                fields=("org", "name", "embedding_provider"),
                name="unique_embeddingmodel_name_provider_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="embeddingmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("org__isnull", True)),
                fields=("name", "embedding_provider"),
                name="unique_embeddingmodel_name_provider_builtin",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmmodel",
            constraint=models.UniqueConstraint(
                fields=("org", "name", "llm_provider"),
                name="unique_llmmodel_name_provider_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="llmmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("org__isnull", True)),
                fields=("name", "llm_provider"),
                name="unique_llmmodel_name_provider_builtin",
            ),
        ),
        migrations.AddConstraint(
            model_name="realtimemodel",
            constraint=models.UniqueConstraint(
                fields=("org", "name", "provider"),
                name="unique_realtimemodel_name_provider_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="realtimemodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("org__isnull", True)),
                fields=("name", "provider"),
                name="unique_realtimemodel_name_provider_builtin",
            ),
        ),
        migrations.AddConstraint(
            model_name="realtimetranscriptionmodel",
            constraint=models.UniqueConstraint(
                fields=("org", "name", "provider"),
                name="unique_realtimetranscriptionmodel_name_prov_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="realtimetranscriptionmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("org__isnull", True)),
                fields=("name", "provider"),
                name="unique_realtimetranscriptionmodel_name_prov_builtin",
            ),
        ),
    ]
