# Generated by Django 5.1.7 on 2026-09-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0235_merge_20260902_1904'),
        ('tables', '0235_merge_20260904_1022'),
    ]

    operations = [
    ]
