# Generated by Django 5.1.7 on 2026-09-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0235_merge_20260904_1022'),
        ('tables', '0236_per_org_provider_model_uniqueness'),
    ]

    operations = [
    ]
