# Generated by Django 5.1.7 on 2026-09-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0212_alter_rolepermission_resource_type"),
        ("tables", "0237_merge_rbac_cross_org_admin_panel_migrations_3"),
    ]

    operations = []
