# Generated by Django 5.1.14 on 2026-09-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0236_pythoncodetool_mcptool_timestamps'),
        ('tables', '0238_alter_agentgraphrag_options_and_more'),
    ]

    operations = [
    ]
