# Generated by Django 5.1.7 on 2026-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0238_merge_rbac_admin_api_keys_migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("organizations", "Organizations"),
                    ("roles", "Roles"),
                    ("memberships", "Members"),
                    ("api_keys", "API Keys"),
                    ("flows", "Flows"),
                    ("agents", "Agents"),
                    ("tools", "Tools"),
                    ("knowledge_sources", "Knowledge Sources"),
                    ("files", "Files"),
                    ("projects", "Projects"),
                    ("llm_configs", "LLM Configs"),
                    ("secrets", "Secrets"),
                    ("voice", "Voice"),
                    ("surfaces", "Surfaces"),
                ],
                max_length=32,
            ),
        ),
    ]
