# Generated by Django 5.1.7 on 2026-09-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0238_alter_agentgraphrag_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defaultllmconfig",
            name="headers",
        ),
        migrations.RemoveField(
            model_name="llmconfig",
            name="headers",
        ),
    ]
