# Generated by Django 5.1.7 on 2026-09-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0233_merge_20260901_1819'),
        ('tables', '0238_alter_agentgraphrag_options_and_more'),
    ]

    operations = [
    ]
