# Generated by Django 5.1.7 on 2026-09-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0238_alter_agentgraphrag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtimechannel',
            options={'default_manager_name': 'objects'},
        ),
    ]
