# Generated by Django 5.1.7 on 2026-09-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0233_remove_secret_unique_secret_name_per_org_and_more'),
        ('tables', '0239_realtimechannel_enabled_toggle'),
    ]

    operations = [
    ]
