# Generated by Django 5.1.7 on 2026-09-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0239_realtimechannel_enabled_toggle'),
        ('tables', '0239_remove_llmconfig_headers'),
    ]

    operations = [
    ]
