# Generated by Django 5.1.7 on 2026-09-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0239_merge_secrets_use_permission'),
        ('tables', '0239_realtimechannel_enabled_toggle'),
    ]

    operations = [
    ]
