# Generated by Django 5.1.7 on 2026-09-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0239_merge_20260909_1433'),
        ('tables', '0239_realtimechannel_enabled_toggle'),
    ]

    operations = [
    ]
