# Generated by Django 5.1.7 on 2026-09-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0238_alter_agentgraphrag_options_and_more"),
        ("tables", "0239_alter_rolepermission_resource_type"),
    ]

    operations = []
