# Generated by Django 5.1.14 on 2026-09-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0236_merge_audit_trail_migrations'),
        ('tables', '0239_realtimechannel_enabled_toggle'),
    ]

    operations = [
    ]
