# Generated by Django 5.1.14 on 2026-09-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0239_merge_tool_redisgn_migrations'),
        ('tables', '0239_realtimechannel_enabled_toggle'),
    ]

    operations = [
    ]
