# Generated by Django 5.1.14 on 2026-09-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0240_merge_20260910_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgenodegraphragbasicsearchconfig',
            name='is_suggested',
            field=models.BooleanField(default=False, help_text='Whether these values came from parameter suggestion.'),
        ),
        migrations.AddField(
            model_name='knowledgenodegraphraglocalsearchconfig',
            name='is_suggested',
            field=models.BooleanField(default=False, help_text='Whether these values came from parameter suggestion.'),
        ),
        migrations.AddField(
            model_name='knowledgenodenaiveragsearchconfig',
            name='is_suggested',
            field=models.BooleanField(default=False, help_text='Whether these values came from parameter suggestion.'),
        ),
    ]
