# Generated by Django 5.1.7 on 2026-09-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0240_merge_rbac_admin_api_keys_migrations_2"),
        ("tables", "0240_merge_secrets_use_permissions"),
    ]

    operations = []
