# Generated by Django 5.1.14 on 2026-09-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0240_merge_secrets_use_permissions'),
        ('tables', '0240_merge_tools_usage_migration'),
    ]

    operations = [
    ]
