# Generated by Django 5.1.7 on 2026-09-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0240_merge_llmconfig_headers"),
        ("tables", "0240_merge_secrets_use_permissions"),
    ]

    operations = []
