# Generated by Django 5.1.14 on 2026-09-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0240_merge_20260910_1724'),
        ('tables', '0240_merge_secrets_use_permissions'),
    ]

    operations = [
    ]
