# Generated by Django 5.1.7 on 2026-09-15 10:44

from django.db import migrations


# Re-seed the built-in roles so every stored bit is one the code actually
# enforces and the permission catalog can actually grant.
#
# Three kinds of bit had accumulated in the seeds that satisfy neither:
#
# - USE (64) on `flows`, seeded for Viewer by 0171/0183 as "can run flows".
#   Nothing has ever enforced it: running a flow checks FLOWS.READ
#   (views.py RunSession), and `use` is not among the catalog's applicable
#   actions for `flows`, so it cannot be granted through the matrix either.
#   Viewer keeps READ and can still run flows.
# - LIST (128) on `secrets`, seeded by 0183 and left at 128 for Member/Viewer
#   by 0236. `Permission.LIST` is checked nowhere in the codebase and is
#   commented out of ACTION_METADATA, so it is neither enforced nor grantable.
# - UPDATE (4) on `secrets`, part of 0183's placeholder 207 written before the
#   Secret model existed. The shipped SecretViewSet has no UpdateModelMixin --
#   a Secret's name and value are immutable -- so there is no route to gate,
#   and the catalog correctly omits `update` from secrets' applicable actions.
#
# Every removal is therefore behaviour-neutral: effective access is identical
# before and after. What changes is that the table stops claiming authority
# that does not exist, which matters because the escalation ceiling compares
# these masks when deciding whether one role may be assigned by the holder of
# another.
#
# Masks are written out in full rather than computed from the catalog: a
# historical migration must not change meaning when the catalog changes.

_INTENDED = {
    "Org Admin": {
        "agents": 31,  # C R U D E
        "api_keys": 10,  # R D
        "files": 31,  # C R U D E
        "flows": 31,  # C R U D E
        "knowledge_sources": 15,  # C R U D
        "llm_configs": 15,  # C R U D
        "memberships": 15,  # C R U D
        "organizations": 6,  # R U
        "projects": 31,  # C R U D E
        "roles": 15,  # C R U D
        "secrets": 75,  # C R D use   (was 207: dropped UPDATE + LIST)
        "surfaces": 15,  # C R U D
        "tools": 31,  # C R U D E
        "voice": 15,  # C R U D
    },
    "Member": {
        "agents": 7,  # C R U
        "files": 23,  # C R U E
        "flows": 7,  # C R U
        "knowledge_sources": 2,  # R
        "llm_configs": 2,  # R
        "memberships": 0,
        "organizations": 0,
        "projects": 7,  # C R U
        "roles": 0,
        "secrets": 0,  # (was 128: dropped LIST; no USE by decision)
        "surfaces": 7,  # C R U
        "tools": 23,  # C R U E
        "voice": 2,  # R
    },
    "Viewer": {
        "agents": 2,  # R
        "files": 2,  # R
        "flows": 2,  # R   (was 66: dropped USE)
        "knowledge_sources": 2,  # R
        "llm_configs": 2,  # R
        "memberships": 0,
        "organizations": 0,
        "projects": 2,  # R
        "roles": 0,
        "secrets": 0,  # (was 128: dropped LIST; no USE by decision)
        "surfaces": 2,  # R
        "tools": 2,  # R
        "voice": 2,  # R
    },
}

# The four rows this migration actually changes, at their pre-migration values.
# Reverse restores exactly these; every other row is re-seeded to the value it
# already held, so nothing else needs undoing.
_PREVIOUS = {
    ("Org Admin", "secrets"): 207,
    ("Member", "secrets"): 128,
    ("Viewer", "flows"): 66,
    ("Viewer", "secrets"): 128,
}


def _write(apps, masks_by_role_resource):
    """Apply {(role_name, resource_type): bitmask} to the built-in roles.

    Idempotent: re-running writes the same values. A role that does not exist
    is skipped rather than failing, matching every other seed on this table.
    """
    Role = apps.get_model("tables", "Role")
    RolePermission = apps.get_model("tables", "RolePermission")

    roles = {}
    for (role_name, resource_type), bitmask in masks_by_role_resource.items():
        if role_name not in roles:
            roles[role_name] = Role.objects.filter(
                name=role_name, is_built_in=True, org__isnull=True
            ).first()
        role = roles[role_name]
        if role is None:
            continue
        RolePermission.objects.update_or_create(
            role=role,
            resource_type=resource_type,
            defaults={"permissions": bitmask},
        )


def reseed_builtin_role_permissions(apps, schema_editor):
    _write(
        apps,
        {
            (role_name, resource_type): bitmask
            for role_name, by_resource in _INTENDED.items()
            for resource_type, bitmask in by_resource.items()
        },
    )


def restore_previous_permissions(apps, schema_editor):
    _write(apps, _PREVIOUS)


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0241_merge_rbac_admin_api_keys_migrations_3"),
    ]

    operations = [
        migrations.RunPython(
            reseed_builtin_role_permissions, restore_previous_permissions
        ),
    ]
