# Generated by Django 5.1.14 on 2026-09-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0241_merge_headers_and secrets'),
        ('tables', '0241_merge_tools_usage_migration_2'),
    ]

    operations = [
    ]
