# Generated by Django 5.1.14 on 2026-09-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0242_alter_knowledgenode_search_method_and_more'),
        ('tables', '0242_merge_tools_usage_migrations_3'),
    ]

    operations = [
    ]
