# Generated by Django 5.1.14 on 2026-09-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0241_merge_audit_trail_migrations_2'),
        ('tables', '0243_merge_graph_rag_and_tools_usage_migrations'),
    ]

    operations = [
    ]
