# Generated by Django 5.1.7 on 2026-09-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0242_reseed_builtin_role_permissions"),
        ("tables", "0243_merge_graph_rag_and_tools_usage_migrations"),
    ]

    operations = []
