# Generated by Django 5.1.7 on 2026-09-16 12:00

from django.db import migrations


# Grant the EXPORT bit on `knowledge_sources` to the built-in Org Admin so the
# document-download surface (DocumentViewSet.download), newly gated on
# KNOWLEDGE_SOURCES.EXPORT instead of READ, remains accessible to admins.
#
# Member and Viewer are left untouched: they hold READ (2) on knowledge_sources
# and neither had CRUD nor EXPORT before -- gating download on EXPORT tightens
# the surface deliberately, matching how `files`/`tools` are already shaped.
#
# Idempotent: re-running writes the same value. A role that does not exist is
# skipped rather than failing, matching every other seed on this table.
#
# Masks are written out in full rather than computed from the catalog: a
# historical migration must not change meaning when the catalog changes.

_KNOWLEDGE_SOURCES = "knowledge_sources"

_NEW = {
    "Org Admin": 31,  # C R U D E   (was 15: added EXPORT)
}

_PREVIOUS = {
    "Org Admin": 15,  # C R U D
}


def _write(apps, masks_by_role):
    Role = apps.get_model("tables", "Role")
    RolePermission = apps.get_model("tables", "RolePermission")

    for role_name, bitmask in masks_by_role.items():
        role = Role.objects.filter(
            name=role_name, is_built_in=True, org__isnull=True
        ).first()
        if role is None:
            continue
        RolePermission.objects.update_or_create(
            role=role,
            resource_type=_KNOWLEDGE_SOURCES,
            defaults={"permissions": bitmask},
        )


def grant_knowledge_sources_export(apps, schema_editor):
    _write(apps, _NEW)


def revoke_knowledge_sources_export(apps, schema_editor):
    _write(apps, _PREVIOUS)


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0244_merge_rbac_admin_api_keys_migrations_4"),
    ]

    operations = [
        migrations.RunPython(
            grant_knowledge_sources_export, revoke_knowledge_sources_export
        ),
    ]
