# Generated by Django 5.1.7 on 2026-09-16 15:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0244_merge_rbac_admin_api_keys_migrations_4"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                models.F("org"),
                django.db.models.functions.text.Lower("name"),
                name="rbac_role_org_name_ci_uniq",
            ),
        ),
    ]
