# Generated by Django 5.1.14 on 2026-09-15 11:47

from django.db import migrations


def backfill_session_principal(apps, schema_editor):
    Session = apps.get_model("tables", "Session")
    SessionPrincipal = apps.get_model("tables", "SessionPrincipal")

    BATCH_SIZE = 1000

    with_user = (
        Session.objects.filter(graph_user__isnull=False)
        .select_related("graph_user__organization_user__user")
        .iterator()
    )
    batch = []
    for session in with_user:
        user = session.graph_user.organization_user.user
        batch.append(
            SessionPrincipal(
                session_id=session.id, kind="user", user_id=user.id, email=user.email
            )
        )
        if len(batch) >= BATCH_SIZE:
            SessionPrincipal.objects.bulk_create(batch, batch_size=BATCH_SIZE)
            batch = []
    if batch:
        SessionPrincipal.objects.bulk_create(batch, batch_size=BATCH_SIZE)

    without_user = (
        Session.objects.filter(graph_user__isnull=True, principal__isnull=True)
        .values_list("id", flat=True)
        .iterator()
    )
    batch = []
    for sid in without_user:
        batch.append(SessionPrincipal(session_id=sid, kind="unknown"))
        if len(batch) >= BATCH_SIZE:
            SessionPrincipal.objects.bulk_create(batch, batch_size=BATCH_SIZE)
            batch = []
    if batch:
        SessionPrincipal.objects.bulk_create(batch, batch_size=BATCH_SIZE)


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0244_sessionprincipal"),
    ]

    operations = [
        migrations.RunPython(backfill_session_principal, migrations.RunPython.noop)
    ]
