# Generated by Django 5.1.14 on 2026-09-17 14:10

from django.db import migrations

_INTENDED = {
    ("Org Admin", "webhooks"): 15,  # C R U D
    ("Member", "webhooks"): 15,  # C R U D
    ("Viewer", "webhooks"): 2,  # R
}


def _write(apps, masks_by_role_resource):
    Role = apps.get_model("tables", "Role")
    RolePermission = apps.get_model("tables", "RolePermission")

    roles = {}
    for (role_name, resource_type), bitmask in masks_by_role_resource.items():
        if role_name not in roles:
            roles[role_name] = Role.objects.filter(
                name=role_name, is_built_in=True, org__isnull=True
            ).first()
        role = roles[role_name]
        if role is None:
            continue
        RolePermission.objects.update_or_create(
            role=role, resource_type=resource_type, defaults={"permissions": bitmask}
        )


def seed_webhooks_permissions(apps, schema_editor):
    _write(apps, _INTENDED)


def remove_webhooks_permissions(apps, schema_editor):
    Role = apps.get_model("tables", "Role")
    RolePermission = apps.get_model("tables", "RolePermission")
    role_names = {role_name for role_name, _ in _INTENDED}
    RolePermission.objects.filter(
        resource_type="webhooks",
        role__name__in=role_names,
        role__is_built_in=True,
        role__org__isnull=True,
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0245_role_rbac_role_org_name_ci_uniq"),
    ]

    operations = [
        migrations.RunPython(seed_webhooks_permissions, remove_webhooks_permissions),
    ]
