# Generated by Django 5.1.7 on 2026-09-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0245_knowledge_sources_export_permission"),
        ("tables", "0245_role_rbac_role_org_name_ci_uniq"),
    ]

    operations = []
