# Generated by Django 5.1.14 on 2026-09-15 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0246_merge_knowledge_permission_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('user', 'User'), ('api_key_user', 'Api Key User'), ('api_key_system', 'Api Key System'), ('trigger', 'Trigger'), ('unknown', 'Unknown')], db_index=True, max_length=32)),
                ('email', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('api_key', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.apikey')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal', to='tables.session')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
