# Generated by Django 5.1.14 on 2026-09-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0244_merge_audit_trail_migrations_3'),
        ('tables', '0246_merge_knowledge_permission_migrations'),
    ]

    operations = [
    ]
