# Generated by Django 5.1.14 on 2026-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0246_seed_webhooks_resource_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='resource_type',
            field=models.CharField(choices=[('organizations', 'Organizations'), ('roles', 'Roles'), ('memberships', 'Members'), ('api_keys', 'API Keys'), ('flows', 'Flows'), ('agents', 'Agents'), ('tools', 'Tools'), ('knowledge_sources', 'Knowledge Sources'), ('files', 'Files'), ('projects', 'Projects'), ('llm_configs', 'LLM Configs'), ('secrets', 'Secrets'), ('voice', 'Voice'), ('surfaces', 'Surfaces'), ('webhooks', 'Webhooks')], max_length=32),
        ),
    ]
