# Generated by Django 5.1.14 on 2026-09-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0247_alter_rolepermission_resource_type'),
        ('tables', '0247_sessionprincipal'),
    ]

    operations = [
    ]
