# Generated by Django 5.1.14 on 2026-09-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0246_webhook_trigger_path_global_unique'),
        ('tables', '0248_merge_webhook_resource_type_migrations'),
    ]

    operations = [
    ]
