# Generated by Django 5.1.14 on 2026-09-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0240_classificationdecisiontablenode_post_use_storage_and_more'),
        ('tables', '0249_merge_webhook_path_scoping_migrations'),
    ]

    operations = [
    ]
