# Generated by Django 5.1.14 on 2026-09-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0247_merge_audit_trail_migrations_4'),
        ('tables', '0249_merge_webhook_path_scoping_migrations'),
    ]

    operations = [
    ]
