# Generated by Django 5.1.14 on 2026-09-28 09:07

"""Backfill ClassificationConditionGroupSection rows for legacy `section` values.

Before this migration, ClassificationConditionGroup.section was a free-text
CharField (0178_classificationconditiongroup_section.py), not a foreign key.
Existing rows already hold a client-generated grouping key there, but no
ClassificationConditionGroupSection row was ever created to back it — the
concept didn't exist yet. Converting the column straight to a ForeignKey (the
AlterField below) makes Postgres check every existing section_id against the
brand-new, empty section table.

Most legacy values are valid UUID strings and map onto a new section row
as-is. A minority may not be (the field accepted any text up to 128 chars) —
for those we mint a fresh UUID per distinct garbage value and rewrite
ClassificationConditionGroup.section to match, so the AlterField cast
(section::uuid) below doesn't fail on the same text. Groups that shared an
identical garbage value stay grouped under the one replacement section.
"""

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_condition_group_sections(apps, schema_editor):
    ClassificationConditionGroup = apps.get_model(
        "tables", "ClassificationConditionGroup"
    )
    ClassificationConditionGroupSection = apps.get_model(
        "tables", "ClassificationConditionGroupSection"
    )

    ClassificationConditionGroup.objects.filter(section="").update(section=None)
    # Materialized (not a lazy queryset): walked twice below, and the second
    # pass needs each row's own id to target the bulk_update precisely.
    rows = list(
        ClassificationConditionGroup.objects.filter(section__isnull=False)
        .order_by("classification_decision_table_node_id", "id")
        .values_list("id", "classification_decision_table_node_id", "section")
    )

    # First-seen order per node, deduped — multiple groups sharing the same
    # section value belong to the same section.
    sections_by_node = {}
    for _, node_id, section_value in rows:
        seen = sections_by_node.setdefault(node_id, {})
        seen.setdefault(section_value, None)

    to_create = []
    replacements = {}
    claimed_by = {}  # uuid -> node_id that first claimed it
    for node_id, section_values in sections_by_node.items():
        for index, section_value in enumerate(section_values, start=1):
            try:
                parsed = uuid.UUID(section_value)
            except (ValueError, AttributeError, TypeError):
                parsed = None

            if parsed is not None and claimed_by.setdefault(parsed, node_id) == node_id:
                section_id = parsed
            else:
                section_id = uuid.uuid4()
                while section_id in claimed_by:
                    section_id = uuid.uuid4()
                claimed_by[section_id] = node_id
                replacements[(node_id, section_value)] = section_id
            
            to_create.append(
                ClassificationConditionGroupSection(
                    id=section_id,
                    classification_decision_table_node_id=node_id,
                    name=f"Group {index}",
                    metadata={"color": "#D9D9D9"},
                )
            )

    if to_create:
        ClassificationConditionGroupSection.objects.bulk_create(to_create)

    if replacements:
        ids_to_update = [
            group_id
            for group_id, node_id, section_value in rows
            if (node_id, section_value) in replacements
        ]
        groups_to_update = list(
            ClassificationConditionGroup.objects.filter(id__in=ids_to_update)
        )
        for group in groups_to_update:
            group.section = str(
                replacements[
                    (group.classification_decision_table_node_id, group.section)
                ]
            )
        ClassificationConditionGroup.objects.bulk_update(groups_to_update, ["section"])


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0249_merge_webhook_path_scoping_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationdecisiontablenode",
            name="post_use_storage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classificationdecisiontablenode",
            name="pre_use_storage",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ClassificationConditionGroupSection",
            fields=[
                (
                    "is_soft_deleted",
                    models.BooleanField(db_default=False, default=False),
                ),
                ("soft_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "classification_decision_table_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="tables.classificationdecisiontablenode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            create_condition_group_sections, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="classificationconditiongroup",
            name="section",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="condition_groups",
                to="tables.classificationconditiongroupsection",
            ),
        ),
    ]
