# Generated by Django 5.1.14 on 2026-09-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0250_alter_sessionprincipal_api_key_alter_agent_org_and_more'),
        ('tables', '0250_classificationdecisiontablenode_post_use_storage_and_more'),
    ]

    operations = [
    ]
