# Generated by Django 5.1.14 on 2026-09-23 16:52

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0251_seed_persistent_data_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persistence_tables', to='tables.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersistenceTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=512)),
                ('value', models.JSONField(null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tables.persistencetable')),
                ('updated_by_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='persistencetable',
            index=models.Index(fields=['org'], name='tables_pers_org_id_ce5c87_idx'),
        ),
        migrations.AddConstraint(
            model_name='persistencetable',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('org'), name='unique_persistence_table_name_per_org_ci'),
        ),
        migrations.AddConstraint(
            model_name='persistencetableentry',
            constraint=models.UniqueConstraint(fields=('table', 'key'), name='unique_persistence_entry_key_per_table'),
        ),
    ]
