# Generated by Django 5.1.14 on 2026-09-29 00:26

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import tables.models.base_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_key_value_tables_resource_type'),
        ('tables', '0251_backfill_session_finished_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_value_tables', to='rbac.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyValueNode',
            fields=[
                ('is_soft_deleted', models.BooleanField(db_default=False, default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mode', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete')], default='read', max_length=16)),
                ('entries', models.JSONField(blank=True, default=list)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_value_node_list', to='tables.graph')),
                ('key_value_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='tables.keyvaluetable')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=512)),
                ('value', models.JSONField(null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tables.keyvaluetable')),
                ('updated_by_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='keyvaluetable',
            index=models.Index(fields=['org'], name='tables_keyv_org_id_fbf581_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyvaluetable',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('org'), name='unique_key_value_table_name_per_org_ci'),
        ),
        migrations.AddConstraint(
            model_name='keyvaluenode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_soft_deleted', False), ('soft_deleted_at__isnull', True)), models.Q(('is_soft_deleted', True), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_keyvaluenode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='keyvaluetableentry',
            constraint=models.UniqueConstraint(fields=('table', 'key'), name='unique_key_value_entry_key_per_table'),
        ),
    ]
