# Generated by Django 5.1.14 on 2026-09-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0250_alter_sessionprincipal_api_key_alter_agent_org_and_more'),
        ('tables', '0251_audit_filter_preset_owner_and_org_not_null'),
    ]

    operations = [
    ]
