# Generated by Django 5.1.14 on 2026-09-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0251_alter_secret_options_and_more'),
        ('tables', '0251_backfill_session_finished_at'),
    ]

    operations = [
    ]
