# Generated by Django 5.1.14 on 2026-09-23 17:17

import django.db.models.deletion
import django.db.models.manager
import tables.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0252_persistence_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistenceNode',
            fields=[
                ('is_soft_deleted', models.BooleanField(db_default=False, default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('id', models.BigIntegerField(db_default=tables.models.base_models.NextVal(models.Value('tables_global_node_seq')), editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(blank=True, max_length=255)),
                ('input_map', models.JSONField(default=dict)),
                ('output_variable_path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('mode', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('delete', 'Delete')], default='read', max_length=16)),
                ('entries', models.JSONField(blank=True, default=list)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persistence_node_list', to='tables.graph')),
                ('persistence_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='tables.persistencetable')),
            ],
            options={
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_soft_deleted', False), ('soft_deleted_at__isnull', True)), models.Q(('is_soft_deleted', True), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_persistencenode_soft_delete_consistency')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
