# Generated by Django 5.1.14 on 2026-09-25 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_alter_rolepermission_resource_type'),
        ('tables', '0253_move_organizationconfig_to_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfilterpreset',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='rbac.organization'),
        ),
    ]
