# Generated by Django 5.1.14 on 2026-09-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0251_merge_20260928_1131'),
        ('tables', '0255_key_value_tables'),
    ]

    operations = [
    ]
