# Generated by Django 5.1.14 on 2026-10-04 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_key_value_tables_resource_type'),
        ('tables', '0257_backfill_openai_realtime_model_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontrigger',
            name='trigger_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('webhook', 'Webhook'), ('telegram', 'Telegram'), ('parent_flow', 'Parent Flow'), ('chat', 'Chat')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ChatBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('widget', 'Widget'), ('telegram', 'Telegram')], default='widget', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('concurrency_policy', models.CharField(choices=[('interrupt', 'Interrupt'), ('queue', 'Queue')], default='interrupt', max_length=16)),
                ('history_window', models.PositiveIntegerField(default=20)),
                ('token_budget_per_conversation', models.PositiveIntegerField(blank=True, null=True)),
                ('on_budget_exhausted', models.CharField(choices=[('handoff', 'Handoff'), ('reply', 'Reply')], default='handoff', max_length=16)),
                ('budget_exhausted_message', models.TextField(blank=True, default='')),
                ('handoff_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_bindings', to='tables.graph')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_bindings', to='rbac.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('bot', 'Bot'), ('awaiting_human', 'Awaiting Human'), ('human', 'Human'), ('closed', 'Closed')], default='bot', max_length=16)),
                ('handoff_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('active_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.session')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tables.chatbinding')),
                ('sessions', models.ManyToManyField(blank=True, related_name='+', to='tables.session')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('operator', 'Operator'), ('system', 'System')], max_length=16)),
                ('content', models.TextField(blank=True, default='')),
                ('interrupted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tables.chatconversation')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tables.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='chatbinding',
            index=models.Index(fields=['org'], name='tables_chat_org_id_27ac76_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatconversation',
            constraint=models.UniqueConstraint(fields=('binding', 'external_id'), name='unique_chat_conversation_per_binding'),
        ),
    ]
