# Generated by Django 5.1.14 on 2026-10-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0257_backfill_openai_realtime_model_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='parent_session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgraph_sessions', to='tables.session'),
        ),
    ]
