# Generated by Django 5.1.14 on 2026-09-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0257_storagefile_org_scoped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcecollection',
            name='user_id',
        ),
    ]
