# Generated by Django 5.1.14 on 2026-10-02 11:12

from django.db import migrations, models


APP_LABEL = "tables"


def _soft_delete_tables(apps):
    for model in apps.get_app_config(APP_LABEL).get_models():
        field_names = {field.name for field in model._meta.local_fields}
        if {"active", "is_soft_deleted"} <= field_names:
            yield model._meta.db_table


def copy_is_soft_deleted_to_active(apps, schema_editor):
    # AddField filled every row with the DB default (true) without rewriting the
    # table. Only the binned rows need a write.
    for table in _soft_delete_tables(apps):
        schema_editor.execute(
            f"UPDATE {schema_editor.quote_name(table)} SET active = false WHERE is_soft_deleted"
        )


def copy_active_to_is_soft_deleted(apps, schema_editor):
    for table in _soft_delete_tables(apps):
        schema_editor.execute(
            f"UPDATE {schema_editor.quote_name(table)} SET is_soft_deleted = true WHERE NOT active"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0257_backfill_openai_realtime_model_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentgraphrag',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentnaiverag',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentnode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentnodetask',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentpythoncodetoolconfigs',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='agentpythoncodetools',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='audiotranscriptionnode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='baseragtype',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationconditiongroup',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationconditiongroupsection',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationdecisiontablenode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='classificationdecisiontableprompt',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='crewnode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='endnode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='fileextractornode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='flowassistant',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='flowassistantconversation',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='flowassistantmessage',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='graphnote',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='graphorganization',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='graphorganizationuser',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='graphrag',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='graphragdocument',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='graphstoragefile',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='graphversion',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='keyvaluenode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='naiverag',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='naiveragchunk',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='naiveragdocumentconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='naiveragembedding',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='naiveragpreviewchunk',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='pythoncodetool',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='pythoncodetoolconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='pythonnode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='scheduletriggernode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='sourcecollection',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='startnode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='subgraphnode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='tasknode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='taskpythoncodetoolconfigs',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='taskpythoncodetools',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='telegramtriggernode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='telegramtriggernodefield',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='webhooktriggerauth',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='webhooktriggernode',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.RunPython(copy_is_soft_deleted_to_active, copy_active_to_is_soft_deleted),
    ]
