# Generated by Django 5.1.14 on 2026-09-30 07:44

import django.core.validators
import tables.validators.finite_number_validator
import tables.validators.mcp_transport_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0257_backfill_openai_realtime_model_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcptool',
            name='init_timeout',
            field=models.FloatField(default=10, help_text='Timeout for session initialization. Optional, default is 10 seconds.', validators=[tables.validators.finite_number_validator.validate_finite_number, django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='timeout',
            field=models.FloatField(default=30, help_text='Request timeout in seconds. Recommended to set.', validators=[tables.validators.finite_number_validator.validate_finite_number, django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='mcptool',
            name='transport',
            field=models.CharField(help_text='http(s) URL of the remote MCP server (SSE). Required.', max_length=2048, validators=[tables.validators.mcp_transport_validator.validate_mcp_transport_url]),
        ),
    ]
