# Generated by Django 5.1.14 on 2026-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0257_backfill_openai_realtime_model_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtriggernode',
            name='test_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='webhooktriggernode',
            name='test_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
