# Generated by Django 5.1.14 on 2026-10-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0258_sourcecollection_drop_user_id'),
    ]

    # Adding an auto_now_add column in one AddField fills every existing row with the
    # migration time (the schema editor's effective default for auto_now_add is now()).
    # Existing rows have no known creation time, so each column is added as a plain
    # nullable field first and only then switched to auto_now_add, leaving them NULL.
    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='embeddingconfig',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='realtimechannel',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='webhooktrigger',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='embeddingconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtimechannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhooktrigger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
