# Generated by Django 5.1.14 on 2026-10-02 11:17

from django.db import migrations, models


APP_LABEL = "tables"


def _soft_delete_tables(apps):
    for model in apps.get_app_config(APP_LABEL).get_models():
        field_names = {field.name for field in model._meta.get_fields()}
        if {"active", "is_soft_deleted"} <= field_names:
            yield model._meta.db_table


def copy_active_to_is_soft_deleted(apps, schema_editor):
    # Backwards only: runs after RemoveField re-adds is_soft_deleted (every row
    # false) and before the old constraints come back, which binned rows would
    # violate until the flag is copied.
    for table in _soft_delete_tables(apps):
        schema_editor.execute(
            f"UPDATE {schema_editor.quote_name(table)} SET is_soft_deleted = true WHERE NOT active"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_drop_is_soft_deleted'),
        ('rbac', '0003_key_value_tables_resource_type'),
        ('tables', '0258_soft_delete_active_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentgraphrag',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentnaiverag',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentnode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentnodetask',
            options={'default_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='agentpythoncodetoolconfigs',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='agentpythoncodetools',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='audiotranscriptionnode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='baseragtype',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='classificationconditiongroup',
            options={'default_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='classificationdecisiontablenode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='classificationdecisiontableprompt',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'default_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='conditionaledge',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='conditiongroup',
            options={'default_manager_name': 'objects', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='crewnode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='decisiontablenode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='documentmetadata',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='edge',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='endnode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fileextractornode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='flowassistant',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='flowassistantconversation',
            options={'default_manager_name': 'objects', 'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='flowassistantmessage',
            options={'default_manager_name': 'objects', 'ordering': ['message_index']},
        ),
        migrations.AlterModelOptions(
            name='graph',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='graphnote',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='graphorganization',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='graphorganizationuser',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='graphrag',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='graphragdocument',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='graphstoragefile',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='graphversion',
            options={'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='keyvaluenode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='knowledgenode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='naiverag',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='naiveragchunk',
            options={'default_manager_name': 'objects', 'ordering': ['chunk_index']},
        ),
        migrations.AlterModelOptions(
            name='naiveragdocumentconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='naiveragembedding',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='naiveragpreviewchunk',
            options={'default_manager_name': 'objects', 'ordering': ['chunk_index']},
        ),
        migrations.AlterModelOptions(
            name='pythoncodetool',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='pythoncodetoolconfig',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='pythonnode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='scheduletriggernode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='sourcecollection',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='startnode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='subgraphnode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='tasknode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='taskpythoncodetoolconfigs',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='taskpythoncodetools',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='telegramtriggernode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='telegramtriggernodefield',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='webhooktriggerauth',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='webhooktriggernode',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='agentgraphrag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentnaiverag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentnodetask',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentpythoncodetoolconfigs',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='agentpythoncodetools',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='audiotranscriptionnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='baseragtype',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='classificationconditiongroup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='classificationdecisiontablenode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='classificationdecisiontableprompt',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='condition',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='conditionaledge',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='conditiongroup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='crewnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='decisiontablenode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='documentmetadata',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='edge',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='endnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='fileextractornode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='flowassistant',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='flowassistantconversation',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='flowassistantmessage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='graph',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='graphnote',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='graphorganization',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='graphorganizationuser',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='graphrag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='graphragdocument',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='graphstoragefile',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='graphversion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='keyvaluenode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='knowledgenode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='naiverag',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='naiveragchunk',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='naiveragdocumentconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='naiveragembedding',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='naiveragpreviewchunk',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pythoncodetool',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pythoncodetoolconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pythonnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='scheduletriggernode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sourcecollection',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='startnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subgraphnode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tasknode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='taskpythoncodetoolconfigs',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='taskpythoncodetools',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='telegramtriggernode',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='telegramtriggernodefield',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='webhooktriggerauth',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='webhooktriggernode',
            managers=[
            ],
        ),
        migrations.RemoveConstraint(
            model_name='agentgraphrag',
            name='tables_agentgraphrag_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentnaiverag',
            name='tables_agentnaiverag_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentnode',
            name='tables_agentnode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentnodetask',
            name='tables_agentnodetask_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentpythoncodetoolconfigs',
            name='tables_agentpythoncodetoolconfigs_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='agentpythoncodetools',
            name='tables_agentpythoncodetools_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='audiotranscriptionnode',
            name='tables_audiotranscriptionnode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='baseragtype',
            name='tables_baseragtype_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='classificationconditiongroup',
            name='tables_classificationconditiongroup_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='classificationdecisiontablenode',
            name='tables_classificationdecisiontablenode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='classificationdecisiontableprompt',
            name='tables_classificationdecisiontableprompt_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='condition',
            name='tables_condition_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='conditionaledge',
            name='tables_conditionaledge_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='conditiongroup',
            name='tables_conditiongroup_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='crewnode',
            name='tables_crewnode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='decisiontablenode',
            name='tables_decisiontablenode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='documentmetadata',
            name='tables_documentmetadata_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='edge',
            name='tables_edge_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='endnode',
            name='tables_endnode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='fileextractornode',
            name='tables_fileextractornode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='flowassistant',
            name='tables_flowassistant_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='flowassistantconversation',
            name='tables_flowassistantconversation_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='flowassistantmessage',
            name='tables_flowassistantmessage_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='graph',
            name='tables_graph_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='graph',
            name='unique_graph_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='graphnote',
            name='tables_graphnote_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='graphorganization',
            name='tables_graphorganization_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='graphorganizationuser',
            name='tables_graphorganizationuser_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='graphrag',
            name='tables_graphrag_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='graphragdocument',
            name='tables_graphragdocument_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='graphstoragefile',
            name='tables_graphstoragefile_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='graphversion',
            name='tables_graphversion_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='keyvaluenode',
            name='tables_keyvaluenode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='knowledgenode',
            name='tables_knowledgenode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='naiverag',
            name='tables_naiverag_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='naiveragchunk',
            name='tables_naiveragchunk_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='naiveragdocumentconfig',
            name='tables_naiveragdocumentconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='naiveragembedding',
            name='tables_naiveragembedding_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='naiveragpreviewchunk',
            name='tables_naiveragpreviewchunk_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='pythoncodetool',
            name='tables_pythoncodetool_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='pythoncodetool',
            name='unique_pythoncodetool_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='pythoncodetoolconfig',
            name='tables_pythoncodetoolconfig_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='pythonnode',
            name='tables_pythonnode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='scheduletriggernode',
            name='tables_scheduletriggernode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='sourcecollection',
            name='tables_sourcecollection_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='sourcecollection',
            name='unique_collection_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='startnode',
            name='tables_startnode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='subgraphnode',
            name='tables_subgraphnode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='tasknode',
            name='tables_tasknode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='taskpythoncodetoolconfigs',
            name='tables_taskpythoncodetoolconfigs_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='taskpythoncodetools',
            name='tables_taskpythoncodetools_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='telegramtriggernode',
            name='tables_telegramtriggernode_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='telegramtriggernodefield',
            name='tables_telegramtriggernodefield_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='webhooktriggerauth',
            name='tables_webhooktriggerauth_soft_delete_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='webhooktriggernode',
            name='tables_webhooktriggernode_soft_delete_consistency',
        ),
        migrations.RunPython(migrations.RunPython.noop, copy_active_to_is_soft_deleted),
        migrations.RemoveField(
            model_name='agentgraphrag',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentnaiverag',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentnode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentnodetask',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentpythoncodetoolconfigs',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='agentpythoncodetools',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='audiotranscriptionnode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='baseragtype',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='classificationconditiongroup',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='classificationconditiongroupsection',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='classificationdecisiontablenode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='classificationdecisiontableprompt',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='conditionaledge',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='conditiongroup',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='crewnode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='decisiontablenode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='endnode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='fileextractornode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='flowassistant',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='flowassistantconversation',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='flowassistantmessage',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='graphnote',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='graphorganization',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='graphorganizationuser',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='graphrag',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='graphragdocument',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='graphstoragefile',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='graphversion',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='keyvaluenode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='knowledgenode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='naiverag',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='naiveragchunk',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='naiveragdocumentconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='naiveragembedding',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='naiveragpreviewchunk',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='pythoncodetool',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='pythoncodetoolconfig',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='pythonnode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='scheduletriggernode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='sourcecollection',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='startnode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='subgraphnode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='tasknode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='taskpythoncodetoolconfigs',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='taskpythoncodetools',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='telegramtriggernode',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='telegramtriggernodefield',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='webhooktriggerauth',
            name='is_soft_deleted',
        ),
        migrations.RemoveField(
            model_name='webhooktriggernode',
            name='is_soft_deleted',
        ),
        migrations.AddConstraint(
            model_name='agentgraphrag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_agentgraphrag_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentnaiverag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_agentnaiverag_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_agentnode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentnodetask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_agentnodetask_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentpythoncodetoolconfigs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_agentpythoncodetoolconfigs_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='agentpythoncodetools',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_agentpythoncodetools_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='audiotranscriptionnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_audiotranscriptionnode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='baseragtype',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_baseragtype_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='classificationconditiongroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_classificationconditiongroup_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='classificationdecisiontablenode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_classificationdecisiontablenode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='classificationdecisiontableprompt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_classificationdecisiontableprompt_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_condition_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='conditionaledge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_conditionaledge_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='conditiongroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_conditiongroup_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='crewnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_crewnode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='decisiontablenode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_decisiontablenode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='documentmetadata',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_documentmetadata_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_edge_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='endnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_endnode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='fileextractornode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_fileextractornode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='flowassistant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_flowassistant_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='flowassistantconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_flowassistantconversation_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='flowassistantmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_flowassistantmessage_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_graph_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('org', 'name'), name='unique_graph_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='graphnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_graphnote_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='graphorganization',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_graphorganization_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='graphorganizationuser',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_graphorganizationuser_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='graphrag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_graphrag_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='graphragdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_graphragdocument_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='graphstoragefile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_graphstoragefile_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='graphversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_graphversion_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='keyvaluenode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_keyvaluenode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='knowledgenode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_knowledgenode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='naiverag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_naiverag_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='naiveragchunk',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_naiveragchunk_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='naiveragdocumentconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_naiveragdocumentconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='naiveragembedding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_naiveragembedding_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='naiveragpreviewchunk',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_naiveragpreviewchunk_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='pythoncodetool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_pythoncodetool_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='pythoncodetool',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('org', 'name'), name='unique_pythoncodetool_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='pythoncodetoolconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_pythoncodetoolconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='pythonnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_pythonnode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='scheduletriggernode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_scheduletriggernode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='sourcecollection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_sourcecollection_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='sourcecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('org', 'collection_name'), name='unique_collection_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='startnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_startnode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='subgraphnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_subgraphnode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='tasknode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_tasknode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='taskpythoncodetoolconfigs',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_taskpythoncodetoolconfigs_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='taskpythoncodetools',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_taskpythoncodetools_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='telegramtriggernode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_telegramtriggernode_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='telegramtriggernodefield',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_telegramtriggernodefield_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='webhooktriggerauth',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_webhooktriggerauth_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='webhooktriggernode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_webhooktriggernode_soft_delete_consistency'),
        ),
    ]
