# Generated by Django 5.1.14 on 2026-10-02 07:58

from django.db import migrations, models
from django.utils import timezone


def mark_existing_users_tour_completed(apps, schema_editor):
    """Treat every user that predates the tour as having already seen it.

    Without this, every existing user would get the Quick Start tour auto-started
    on their next login after the upgrade. Only users created after this migration
    start with a null timestamp.
    """
    User = apps.get_model("tables", "User")  # noqa: N806
    User.objects.filter(quickstart_tour_completed_at__isnull=True).update(
        quickstart_tour_completed_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0258_session_parent_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quickstart_tour_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the user finished or skipped the Quick Start tour; null means not completed or skipped yet.', null=True),
        ),
        migrations.RunPython(
            mark_existing_users_tour_completed, migrations.RunPython.noop
        ),
    ]
