# Generated by Django 5.1.14 on 2026-10-06 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create AuditFilterPreset and enforce NOT NULL on its org_id.

    `org` comes from the OrgScopedModel mixin and stays null=True in Django
    state, so the constraint is plain RunSQL with no state operation, like
    0209_realtime_channel_org_not_null. The viewset always stamps org on create.
    """

    dependencies = [
        ('rbac', '0004_organization_config'),
        ('tables', '0258_session_parent_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('filter_body', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='rbac.organization')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['org'], name='tables_audi_org_id_dd7995_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'name'), name='unique_audit_filter_preset_name_per_org')],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE tables_auditfilterpreset ALTER COLUMN org_id SET NOT NULL;",
            reverse_sql="ALTER TABLE tables_auditfilterpreset ALTER COLUMN org_id DROP NOT NULL;",
        ),
    ]
