# Generated by Django 5.1.14 on 2026-10-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0258_telegramtriggernode_test_payload_and_more'),
        ('tables', '0259_audit_filter_preset'),
    ]

    operations = [
    ]
