# Generated by Django 5.1.14 on 2026-10-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0260_merge_20261007_0846'),
    ]

    # Same two steps as 0259_created_at_on_authored_configs: an auto_now_add column
    # added in one AddField fills every existing row with the migration time. Existing
    # configs have no known creation time, so each column is added as a plain nullable
    # field first and only then switched to auto_now_add, leaving them NULL.
    operations = [
        migrations.AddField(
            model_name='openairealtimeconfig',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='elevenlabsrealtimeconfig',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='geminirealtimeconfig',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='openairealtimeconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='elevenlabsrealtimeconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='geminirealtimeconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
