# Generated by Django 5.1.14 on 2026-10-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0260_merge_20261007_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphsessionmessage',
            name='node_type',
            field=models.CharField(blank=True, default=''),
        ),
    ]
