# Generated by Django 5.1.14 on 2026-10-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0260_merge_20261007_1241'),
        ('tables', '0260_search_config_non_finite_floats'),
    ]

    operations = [
    ]
