# Generated by Django 5.1.14 on 2026-10-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_organization_config'),
        ('tables', '0261_merge_20261007_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'default_manager_name': 'objects'},
        ),
        migrations.RemoveConstraint(
            model_name='secret',
            name='unique_secret_name_per_org',
        ),
        migrations.AddField(
            model_name='secret',
            name='system',
            field=models.BooleanField(default=False, editable=False, help_text='Infrastructure secret (e.g. org-level storage credentials) managed internally by storage_credentials. Never exposed through the user-facing Secret API.'),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(condition=models.Q(('system', False)), fields=('org', 'name'), name='unique_secret_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(condition=models.Q(('system', True)), fields=('org', 'name'), name='unique_system_secret_name_per_org'),
        ),
    ]
