# Generated by Django 5.1.14 on 2026-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0261_merge_20261007_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfilterpreset',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
