# Generated by Django 5.1.14 on 2026-10-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0258_session_parent_cascade'),
        ('tables', '0261_soft_delete_batch'),
    ]

    operations = [
    ]
