# Generated by Django 5.1.14 on 2026-10-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0259_user_quickstart_tour_completed_at'),
        ('tables', '0261_merge_20261007_1300'),
    ]

    operations = [
    ]
