# Generated by Django 5.1.14 on 2026-10-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0261_graphsessionmessage_node_type'),
        ('tables', '0261_merge_20261007_1300'),
    ]

    operations = [
    ]
