# Generated by Django 5.1.7 on 2026-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0262_delete_conditionaledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphversion',
            name='snapshot',
            field=models.JSONField(help_text='Serialized graph state: nodes, edges, metadata.'),
        ),
    ]
