# Generated by Django 5.1.14 on 2026-10-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0261_created_at_on_realtime_provider_configs'),
        ('tables', '0262_merge_20261009_0834'),
    ]

    operations = [
    ]
