# Generated by Django 5.1.14 on 2026-10-05 13:06

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_key_value_tables_resource_type'),
        ('tables', '0263_soft_delete_owned_children'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcptool',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'verbose_name': 'MCP Tool Data', 'verbose_name_plural': 'MCP Tool Data'},
        ),
        migrations.AlterModelManagers(
            name='mcptool',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='mcptool',
            name='unique_mcptool_name_per_org',
        ),
        migrations.AddField(
            model_name='mcptool',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='mcptool',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mcptool',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='mcptool',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_mcptool_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='mcptool',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('org', 'name'), name='unique_mcptool_name_per_org'),
        ),
    ]
