# Generated by Django 5.1.7 on 2026-10-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0262_merge_20261009_0834'),
        ('tables', '0263_graphversion_snapshot_help_text'),
    ]

    operations = [
    ]
