# Generated by Django 5.1.7 on 2026-10-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0263_merge_20261009_0941'),
        ('tables', '0264_merge_20261009_1109'),
    ]

    operations = [
    ]
