# Generated by Django 5.1.14 on 2026-10-07 06:50

import django.db.models.functions.text
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_key_value_tables_resource_type'),
        ('tables', '0265_storage_file_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyvaluetable',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='keyvaluetableentry',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='keyvaluetable',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='keyvaluetableentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='keyvaluetable',
            name='unique_key_value_table_name_per_org_ci',
        ),
        migrations.AddField(
            model_name='keyvaluetable',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='keyvaluetable',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='keyvaluetable',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyvaluetableentry',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='keyvaluetableentry',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='keyvaluetableentry',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='keyvaluetable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_keyvaluetable_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='keyvaluetable',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('org'), condition=models.Q(('active', True)), name='unique_key_value_table_name_per_org_ci'),
        ),
        migrations.AddConstraint(
            model_name='keyvaluetableentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_keyvaluetableentry_soft_delete_consistency'),
        ),
    ]
