# Generated by Django 5.1.14 on 2026-10-08 08:19

import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_key_value_tables_resource_type'),
        ('tables', '0266_key_value_table_soft_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localhostwebhookconfig',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='ngrokwebhookconfig',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='realtimechannel',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='secret',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='twiliochannel',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='webhooktrigger',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='localhostwebhookconfig',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ngrokwebhookconfig',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='realtimechannel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='secret',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='twiliochannel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='webhooktrigger',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='secret',
            name='unique_secret_name_per_org',
        ),
        migrations.AddField(
            model_name='localhostwebhookconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='localhostwebhookconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='localhostwebhookconfig',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngrokwebhookconfig',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='ngrokwebhookconfig',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ngrokwebhookconfig',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimechannel',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='realtimechannel',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='realtimechannel',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='secret',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliochannel',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='twiliochannel',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='twiliochannel',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhooktrigger',
            name='active',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name='webhooktrigger',
            name='soft_delete_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='webhooktrigger',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twiliochannel',
            name='phone_number',
            field=models.CharField(blank=True, help_text='E.164 format, e.g. +15551234567', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webhooktrigger',
            name='path',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Path may only contain letters, numbers, hyphens, and underscores, and must start with a letter or number.', regex='^[a-zA-Z0-9]{1}[a-zA-Z0-9-_]*$')]),
        ),
        migrations.AddConstraint(
            model_name='localhostwebhookconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_localhostwebhookconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='ngrokwebhookconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_ngrokwebhookconfig_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='realtimechannel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_realtimechannel_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_secret_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('org', 'name'), name='unique_secret_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='twiliochannel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_twiliochannel_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='twiliochannel',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('phone_number',), name='unique_live_twilio_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='webhooktrigger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('soft_deleted_at__isnull', True)), models.Q(('active', False), ('soft_deleted_at__isnull', False)), _connector='OR'), name='tables_webhooktrigger_soft_delete_consistency'),
        ),
        migrations.AddConstraint(
            model_name='webhooktrigger',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('path',), name='unique_live_webhook_path'),
        ),
    ]
