# Generated by Django 5.1.14 on 2026-10-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0261_merge_20261007_1300'),
        ('tables', '0267_settings_resources_soft_delete'),
    ]

    operations = [
    ]
