export enum NodeType {
    AGENT = 'agent',
    TASK = 'task',
    TOOL = 'tool',
    PYTHON = 'python',
    START = 'start',
    TABLE = 'table',
    CLASSIFICATION_TABLE = 'classification-decision-table',
    NOTE = 'note',
    FILE_EXTRACTOR = 'file-extractor',
    WEBHOOK_TRIGGER = 'webhook-trigger',
    TELEGRAM_TRIGGER = 'telegram-trigger',
    END = 'end',
    SUBGRAPH = 'subgraph',
    AUDIO_TO_TEXT = 'audio-to-text-node',
    SCHEDULE_TRIGGER = 'schedule-trigger',
    KNOWLEDGE_RETRIEVER = 'knowledge-retriever',
    KEY_VALUE = 'key-value',
}
