[tool.poetry]
name = "django-app"
version = "0.1.0"
description = "backend server"
authors = ["Ihor Orlenko", "Maksym Yevstratiev"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
Django = "5.1.7"
djangorestframework = "3.16.0"
djangorestframework-simplejwt = "5.4.0"
psycopg2 = "2.9.10"
django-filter = "24.3"
django-cors-headers = "4.6.0"
redis = "==5.3.1"
loguru = "0.7.3"
pydantic = "==2.13.4"
pgvector = "0.3.6"
pdfplumber = "0.11.5"
python-docx = "1.1.2"
beautifulsoup4 = "4.13.3"
django-health-check = "3.18.3"
litellm = "==1.85.1"
django-redis = "5.4.0"
uvicorn = "==0.49.0"
websockets = "16.0"
gunicorn = "23.0.0"
boto3 = "^1.35.0"
drf-spectacular = "^0.29.0"
apscheduler = "^3.10.4"
channels = "^4.1"
channels-redis = "^4.3.0"
jsonschema = "^4.25.1"
cryptography = "==50.0.1"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
pythonpath = [".", "../.."]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-mock = "^3.14.0"
pytest-django = "^4.9.0"
pytest-asyncio = "^1.0.0"
fakeredis = "^2.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
select = ["E"]
ignore = ["E402","E501"]

[tool.poetry.group.secfloor.dependencies]
urllib3 = "==2.7.0"
requests = "==2.34.2"
jinja2 = "==3.1.6"
certifi = "==2026.7.22"
aiohttp = "==3.14.3"
python-dotenv = "==1.2.2"
idna = "==3.18"
pyjwt = "==2.13.0"
charset-normalizer = "==3.4.7"
yarl = "==1.24.5"
anyio = "==4.14.2"
