from django_app.settings import env, REDIS_HOST, REDIS_PASSWORD, REDIS_PORT

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "host": REDIS_HOST,
                    "port": REDIS_PORT,
                    "password": REDIS_PASSWORD,
                }
            ],
        },
    },
}

KNOWLEDGE_DOCUMENT_CHUNK_REQUEST_CHANNEL = env.str("KNOWLEDGE_DOCUMENT_CHUNK_REQUEST_CHANNEL")
KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE_CHANNEL = env.str("KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE_CHANNEL")
KNOWLEDGE_INDEXING_CHANNEL = env.str("KNOWLEDGE_INDEXING_CHANNEL")
STOP_SESSION_CHANNEL = env.str("STOP_SESSION_CHANNEL")
REQUEST_WEBHOOK_UPDATE_CHANNEL = env.str("REQUEST_WEBHOOK_UPDATE_CHANNEL")
SESSION_STATUS_CHANNEL = env.str("SESSION_STATUS_CHANNEL")
SESSION_SCHEMA_CHANNEL = env.str("SESSION_SCHEMA_CHANNEL")
CODE_RESULT_CHANNEL = env.str("CODE_RESULT_CHANNEL")
GRAPH_MESSAGES_CHANNEL = env.str("GRAPH_MESSAGES_CHANNEL")
GRAPH_MESSAGE_UPDATE_CHANNEL = env.str("GRAPH_MESSAGE_UPDATE_CHANNEL")
WEBHOOK_MESSAGE_CHANNEL = env.str("WEBHOOK_MESSAGE_CHANNEL")
STORAGE_MUTATION_CHANNEL = env.str("STORAGE_MUTATION_CHANNEL")
SCHEDULE_CHANNEL = env.str("SCHEDULE_CHANNEL")
CODE_EXEC_CHANNEL = env.str("CODE_EXEC_CHANNEL")
MEMORY_UPDATE_CHANNEL = env.str("MEMORY_UPDATE_CHANNEL")
SCHEDULE_MIN_INTERVAL = 60
SCHEDULE_MAX_CONCURRENT_SESSIONS_PER_ORG = 20
