from django_app.settings import REDIS_HOST, REDIS_PASSWORD, REDIS_PORT, env

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "host": REDIS_HOST,
                    "port": REDIS_PORT,
                    "password": REDIS_PASSWORD,
                }
            ],
        },
    },
}

KNOWLEDGE_DOCUMENT_CHUNK_REQUEST_CHANNEL = env.str("KNOWLEDGE_DOCUMENT_CHUNK_REQUEST_CHANNEL")
KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE_CHANNEL = env.str("KNOWLEDGE_DOCUMENT_CHUNK_RESPONSE_CHANNEL")
KNOWLEDGE_INDEXING_CHANNEL = env.str("KNOWLEDGE_INDEXING_CHANNEL")
STOP_SESSION_CHANNEL = env.str("STOP_SESSION_CHANNEL")
REQUEST_WEBHOOK_UPDATE_CHANNEL = env.str("REQUEST_WEBHOOK_UPDATE_CHANNEL")
SESSION_SCHEMA_CHANNEL = env.str("SESSION_SCHEMA_CHANNEL")
REALTIME_AGENTS_SCHEMA_CHANNEL = env.str("REALTIME_AGENTS_SCHEMA_CHANNEL")
CODE_RESULT_CHANNEL = env.str("CODE_RESULT_CHANNEL")
# Graph messages read from the stream and stored per batch. Each can be ~300 KB and
# costs ~2 MB of worker RAM while it is parsed and stored, so RAM ~ this x 2 MB.
GRAPH_MESSAGE_BATCH_SIZE = env.int("DJANGO_GRAPH_MESSAGE_BATCH_SIZE", 50)
WEBHOOK_MESSAGE_CHANNEL = env.str("WEBHOOK_MESSAGE_CHANNEL")
STORAGE_MUTATION_CHANNEL = env.str("STORAGE_MUTATION_CHANNEL")
SCHEDULE_CHANNEL = env.str("SCHEDULE_CHANNEL")
CODE_EXEC_CHANNEL = env.str("CODE_EXEC_CHANNEL")
REALTIME_AGENTS_SCHEMA_CHANNEL = env.str("REALTIME_AGENTS_SCHEMA_CHANNEL")
REALTIME_CHANNELS_INVALIDATE_CHANNEL = env.str("REALTIME_CHANNELS_INVALIDATE_CHANNEL")
SCHEDULE_MIN_INTERVAL = 60
SCHEDULE_MAX_CONCURRENT_SESSIONS_PER_ORG = 20
