SPECTACULAR_SETTINGS = {
    "TITLE": "EpicStaff API",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "django_app.spectacular_hooks.add_stream_upload_postprocessing_hook",
        "django_app.spectacular_hooks.assign_tags_postprocessing_hook",
        "django_app.spectacular_hooks.add_org_header_postprocessing_hook",
    ],
    "ENUM_NAME_OVERRIDES": {
        "SourceCollectionStatusEnum": "tables.models.knowledge_models.collection_models.SourceCollection.SourceCollectionStatus",
        "NaiveRagDocumentStatusEnum": "tables.models.knowledge_models.naive_rag_models.NaiveRagDocumentConfig.NaiveRagDocumentStatus",
        "SessionStatusEnum": "tables.models.session_models.Session.SessionStatus",
        "RagTypeEnum": "tables.models.knowledge_models.collection_models.BaseRagType.RagType",
        "RagImplementationTypeEnum": ["naive", "graph"],
        "GraphRagChunkStrategyEnum": "tables.models.knowledge_models.graphrag_models.GraphRagChunkStrategyType",
        "NaiveRagChunkStrategyEnum": "tables.models.knowledge_models.naive_rag_models.NaiveRagDocumentConfig.ChunkStrategy",
        "StorageItemTypeEnum": ["file", "folder"],
        "DocumentFileTypeEnum": "tables.models.knowledge_models.collection_models.DocumentMetadata.DocumentFileType",
        "GraphRagInputFileTypeEnum": "tables.models.knowledge_models.graphrag_models.GraphRagInputFileType",
        "SearchMethodEnum": "tables.models.knowledge_models.graphrag_models.AgentGraphRag.SearchMethod",
        "GraphSearchMethodEnum": "tables.serializers.search_config_serializers.GRAPH_SEARCH_METHODS",
        "ToolModeEnum": "agents.models.surface_models.ToolMode",
    },
}
