[tool.poetry]
name = "epicstaff-graph"
version = "1.0.0"
description = "This service is inteded to build and run EpicStaff Flows."
authors = ["Epicstaff"]
license = "MIT"
readme = "README.md"
package-mode = false
packages = [
    { include = "src" }
]


[tool.poetry.dependencies]
python = ">=3.12,<3.13"
langgraph = "^0.5.4"
pyyaml = "6.0.2"
python-dotenv = "==1.2.2"
datamodel-code-generator = "0.26.0"
redis = "==5.3.1"
loguru = "0.7.2"
litellm = "1.75.7"

[tool.poetry.group.dotdict.dependencies]
dotdict = { path = "../shared/dotdict" }

[tool.poetry.group.dev.dependencies]
watchfiles = "^0.22.0"
pytest = "^8.3.2"
black = "^25.9.0"
flake8 = "^7.1.1"
mypy = "^1.11.1"
pre-commit = "^3.8.0"
pytest-mock = "^3.14.0"
pytest-asyncio = "^0.24.0"
pytest-vcr = "^1.0.2"
fakeredis = "^2.26.1"
polyfactory = "^2.17.0"
pydantic = "==2.13.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
select = ["F","E"]
ignore = ["E402","E501"]


[tool.poetry.group.secfloor.dependencies]
urllib3 = "==2.7.0"
requests = "==2.34.2"
jinja2 = "==3.1.6"
certifi = "==2026.7.22"
aiohttp = "==3.14.3"
idna = "==3.18"
pyjwt = "==2.13.0"
charset-normalizer = "==3.4.7"
yarl = "==1.24.5"
anyio = "==4.14.2"
