# Generated by Django 5.1.14 on 2026-10-06 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0004_plugins_resource_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugin_id', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=64)),
                ('format_version', models.PositiveSmallIntegerField()),
                ('bridge_version', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_data_url', models.TextField(blank=True, default='')),
                ('ui_entry', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(choices=[('preparing', 'Preparing'), ('ready', 'Ready'), ('needs_attention', 'Needs attention')], default='ready', max_length=32)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('suspended', models.BooleanField(default=False)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('access', models.JSONField(blank=True, default=list)),
                ('secret_slots', models.JSONField(blank=True, default=list)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='rbac.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PluginAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('content', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='plugins.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='PluginResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('flow', 'Flow'), ('agent_definition', 'Agent'), ('surface', 'Surface'), ('llm_config', 'LLM config'), ('embedding_config', 'Embedding config'), ('python_code_tool', 'Python tool'), ('mcp_tool', 'MCP tool'), ('webhook_trigger', 'Webhook trigger'), ('secret', 'Secret'), ('source_collection', 'Knowledge collection'), ('storage_file', 'Storage file'), ('llm_model', 'LLM model'), ('embedding_model', 'Embedding model')], max_length=32)),
                ('object_id', models.BigIntegerField()),
                ('manifest_ref', models.CharField(blank=True, default='', max_length=255)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='plugins.plugin')),
            ],
        ),
        migrations.AddIndex(
            model_name='plugin',
            index=models.Index(fields=['org'], name='plugins_plu_org_id_5a1e50_idx'),
        ),
        migrations.AddConstraint(
            model_name='plugin',
            constraint=models.UniqueConstraint(fields=('org', 'plugin_id'), name='unique_plugin_id_per_org'),
        ),
        migrations.AddConstraint(
            model_name='pluginasset',
            constraint=models.UniqueConstraint(fields=('plugin', 'path'), name='unique_plugin_asset_path'),
        ),
        migrations.AddIndex(
            model_name='pluginresource',
            index=models.Index(fields=['resource_type', 'object_id'], name='plugins_plu_resourc_be4eef_idx'),
        ),
        migrations.AddConstraint(
            model_name='pluginresource',
            constraint=models.UniqueConstraint(fields=('plugin', 'resource_type', 'object_id'), name='unique_plugin_resource'),
        ),
    ]
