# Generated by Django 5.1.14 on 2026-10-07 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='dev_ui_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plugin',
            name='dev_ui_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pluginresource',
            name='resource_type',
            field=models.CharField(choices=[('flow', 'Flow'), ('agent_definition', 'Agent'), ('surface', 'Surface'), ('llm_config', 'LLM config'), ('embedding_config', 'Embedding config'), ('python_code_tool', 'Python tool'), ('mcp_tool', 'MCP tool'), ('webhook_trigger', 'Webhook trigger'), ('secret', 'Secret'), ('source_collection', 'Knowledge collection'), ('storage_file', 'Storage file'), ('llm_model', 'LLM model'), ('embedding_model', 'Embedding model'), ('key_value_table', 'Key-value table')], max_length=32),
        ),
    ]
