import { BasePort } from '../../models/port.model';

// Simple Agent node (NodeType.AGENT) — single In/Out ports, mirrors the
// Task/Python node port layout.
export const DEFAULT_AGENT_NODE_PORTS: BasePort[] = [
    {
        port_type: 'input',
        role: 'agent-in',
        multiple: true,
        label: 'In',
        allowedConnections: [
            'project-out',
            'python-out',
            'edge-out',
            'start-start',
            'table-out',
            'llm-out-right',
            'file-extractor-out',
            'subgraph-out',
            'audio-to-text-out',
            'webhook-trigger-out',
            'telegram-trigger-out',
            'schedule-trigger-out',
            'code-agent-out',
            'task-out',
            'decision-default',
            'decision-error',
            'agent-out',
            'knowledge-retriever-out',
        ],
        position: 'left',
        color: '#685fff',
    },
    {
        port_type: 'output',
        role: 'agent-out',
        multiple: false,
        label: 'Out',
        allowedConnections: [
            'project-in',
            'python-in',
            'edge-in',
            'table-in',
            'llm-out-left',
            'file-extractor-in',
            'end-in',
            'subgraph-in',
            'audio-to-text-in',
            'code-agent-in',
            'task-in',
            'agent-in',
            'knowledge-retriever-in',
        ],
        position: 'right',
        color: '#685fff',
    },
];
