"""Coverage for egress_firewall: the iptables-restore input it builds, the
resolv.conf parsing behind its DNS carve-out, and how apply() reports failure.

No real iptables: `subprocess.run` and `socket.getaddrinfo` are faked so the
tests run unprivileged on any host.
"""

import socket
import subprocess
from pathlib import Path

import pytest

import egress_firewall
from egress_firewall import (
    EgressCarveOuts,
    EgressFirewallUnavailableError,
    build_ipv4_rules,
    build_ipv6_rules,
    read_ipv4_nameservers,
)


@pytest.fixture(autouse=True)
def firewall_not_applied(monkeypatch):
    monkeypatch.setattr(egress_firewall, "_active_carve_outs", None)


class TestBuildIpv4Rules:
    def test_full_ruleset(self):
        rules = build_ipv4_rules(
            uid=1000,
            nameservers=("10.89.0.1",),
            storage_endpoints=(("172.20.0.5", 9000),),
        )

        assert rules == (
            "*filter\n"
            ":SANDBOX_EGRESS - [0:0]\n"
            "-A OUTPUT -m owner --uid-owner 1000 -j SANDBOX_EGRESS\n"
            "-A SANDBOX_EGRESS -d 10.89.0.1/32 -p udp --dport 53 -j ACCEPT\n"
            "-A SANDBOX_EGRESS -d 10.89.0.1/32 -p tcp --dport 53 -j ACCEPT\n"
            "-A SANDBOX_EGRESS -d 172.20.0.5/32 -p tcp --dport 9000 -j ACCEPT\n"
            "-A SANDBOX_EGRESS -d 0.0.0.0/8 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 10.0.0.0/8 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 100.64.0.0/10 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 169.254.0.0/16 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 172.16.0.0/12 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 192.0.0.0/24 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 192.168.0.0/16 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 198.18.0.0/15 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 224.0.0.0/4 -j REJECT --reject-with icmp-admin-prohibited\n"
            "-A SANDBOX_EGRESS -d 240.0.0.0/4 -j REJECT --reject-with icmp-admin-prohibited\n"
            "COMMIT\n"
        )

    def test_every_accept_precedes_every_reject(self):
        lines = build_ipv4_rules(
            uid=1000,
            nameservers=("10.89.0.1", "192.168.1.1"),
            storage_endpoints=(("172.20.0.5", 9000), ("10.0.0.7", 9000)),
        ).splitlines()

        accept_indexes = [index for index, line in enumerate(lines) if line.endswith("ACCEPT")]
        reject_indexes = [index for index, line in enumerate(lines) if "-j REJECT" in line]
        assert len(accept_indexes) == 6
        assert max(accept_indexes) < min(reject_indexes)

    def test_loopback_is_not_blocked(self):
        rules = build_ipv4_rules(uid=1000, nameservers=("127.0.0.11",), storage_endpoints=())

        assert "127.0.0.0/8" not in rules
        assert "127.0.0.11/32 -p udp --dport 53 -j ACCEPT" in rules


def test_build_ipv6_rules_rejects_all_non_loopback_traffic_of_uid():
    assert build_ipv6_rules(uid=1000) == (
        "*filter\n-A OUTPUT -m owner --uid-owner 1000 ! -o lo -j REJECT --reject-with icmp6-adm-prohibited\nCOMMIT\n"
    )


class TestReadIpv4Nameservers:
    def test_keeps_only_ipv4_nameserver_lines(self, tmp_path):
        resolv_conf = tmp_path / "resolv.conf"
        resolv_conf.write_text(
            "# Generated by Docker\n"
            "# nameserver 8.8.8.8\n"
            "search example.internal\n"
            "nameserver 127.0.0.11\n"
            "nameserver   10.89.0.1   \n"
            "nameserver fe80::1%eth0\n"
            "nameserver ::1\n"
            "nameserver not-an-ip\n"
            "nameserver\n"
            "options ndots:0\n"
        )

        assert read_ipv4_nameservers(resolv_conf) == ("127.0.0.11", "10.89.0.1")

    def test_missing_file_yields_no_nameservers(self, tmp_path):
        assert read_ipv4_nameservers(tmp_path / "absent") == ()


class _FakeRestore:
    """Stands in for subprocess.run, recording each restore command and its input."""

    def __init__(self, failing_command: str | None = None, error: Exception | None = None):
        self.calls: list[tuple[str, str]] = []
        self._failing_command = failing_command
        self._error = error

    def __call__(self, argv, *, input, check, capture_output, text):
        assert check and capture_output and text
        self.calls.append((argv[0], input))
        if argv[0] == self._failing_command:
            raise self._error
        return subprocess.CompletedProcess(argv, 0, "", "")


@pytest.fixture
def firewall_host(monkeypatch, tmp_path):
    """Point apply() at a fake resolv.conf, IPv6 marker and storage DNS answer."""
    resolv_conf = tmp_path / "resolv.conf"
    resolv_conf.write_text("nameserver 10.89.0.1\n")
    if_inet6 = tmp_path / "if_inet6"
    if_inet6.write_text("")
    monkeypatch.setattr(egress_firewall, "RESOLV_CONF_PATH", resolv_conf)
    monkeypatch.setattr(egress_firewall, "_IF_INET6_PATH", if_inet6)
    monkeypatch.setattr(egress_firewall.settings, "STORAGE_HOST", "storage")
    monkeypatch.setattr(egress_firewall.settings, "STORAGE_PORT", "9000")

    def _fake_getaddrinfo(host, port, family, type):
        assert (host, port, family, type) == ("storage", 9000, socket.AF_INET, socket.SOCK_STREAM)
        address_info = (socket.AF_INET, socket.SOCK_STREAM, 6, "", ("172.20.0.5", 9000))
        return [address_info, address_info]

    monkeypatch.setattr(egress_firewall.socket, "getaddrinfo", _fake_getaddrinfo)
    return if_inet6


def _install_fake_restore(monkeypatch, fake: _FakeRestore) -> _FakeRestore:
    monkeypatch.setattr(egress_firewall.subprocess, "run", fake)
    return fake


class TestApply:
    def test_installs_both_rulesets_and_marks_active(self, monkeypatch, firewall_host):
        fake = _install_fake_restore(monkeypatch, _FakeRestore())

        egress_firewall.apply(1000)

        assert fake.calls == [
            (
                "iptables-restore",
                build_ipv4_rules(
                    uid=1000,
                    nameservers=("10.89.0.1",),
                    storage_endpoints=(("172.20.0.5", 9000),),
                ),
            ),
            ("ip6tables-restore", build_ipv6_rules(uid=1000)),
        ]
        assert egress_firewall.is_active()
        assert egress_firewall.active_carve_outs() == EgressCarveOuts(
            nameservers=("10.89.0.1",), storage_endpoints=(("172.20.0.5", 9000),)
        )

    def test_skips_ip6tables_without_ipv6_in_the_netns(self, monkeypatch, firewall_host: Path):
        firewall_host.unlink()
        fake = _install_fake_restore(monkeypatch, _FakeRestore())

        egress_firewall.apply(1000)

        assert [command for command, _ in fake.calls] == ["iptables-restore"]
        assert egress_firewall.is_active()

    def test_unresolvable_storage_host_drops_only_the_storage_carve_out(
        self, monkeypatch, firewall_host
    ):
        def _unresolvable(*args, **kwargs):
            raise socket.gaierror("Name or service not known")

        monkeypatch.setattr(egress_firewall.socket, "getaddrinfo", _unresolvable)
        fake = _install_fake_restore(monkeypatch, _FakeRestore())

        egress_firewall.apply(1000)

        assert "--dport 9000" not in fake.calls[0][1]
        assert egress_firewall.active_carve_outs().storage_endpoints == ()

    def test_missing_binary_raises_and_stays_inactive(self, monkeypatch, firewall_host):
        _install_fake_restore(
            monkeypatch,
            _FakeRestore("iptables-restore", FileNotFoundError(2, "No such file", "iptables-restore")),
        )

        with pytest.raises(EgressFirewallUnavailableError, match="iptables-restore could not be run"):
            egress_firewall.apply(1000)

        assert not egress_firewall.is_active()

    def test_restore_failure_raises_with_stderr_and_stays_inactive(
        self, monkeypatch, firewall_host
    ):
        # ip6tables fails after iptables succeeded: a half-installed firewall
        # must not count as active.
        error = subprocess.CalledProcessError(
            2, ["ip6tables-restore"], stderr="ip6tables-restore: Permission denied (you must be root)\n"
        )
        _install_fake_restore(monkeypatch, _FakeRestore("ip6tables-restore", error))

        with pytest.raises(EgressFirewallUnavailableError) as raised:
            egress_firewall.apply(1000)

        assert "ip6tables-restore exited with 2" in str(raised.value)
        assert "Permission denied (you must be root)" in str(raised.value)
        assert not egress_firewall.is_active()
