import { BasePort } from '../../models/port.model';

export const DEFAULT_SUBGRAPH_NODE_PORTS: BasePort[] = [
    {
        port_type: 'input',
        role: 'subgraph-in',
        multiple: true,
        label: 'In',
        allowedConnections: [
            'project-out',
            'python-out',
            'file-extractor-out',
            'table-out',
            'start-start',
            'subgraph-out',
            'audio-to-text-out',
            'webhook-trigger-out',
            'telegram-trigger-out',
            'schedule-trigger-out',
            'table-out',
            'task-out',
            'agent-out',
            'knowledge-retriever-out',
            'key-value-out',
        ],
        position: 'left',
        color: '#00bfa5',
    },
    {
        port_type: 'output',
        role: 'subgraph-out',
        multiple: false,
        label: 'Out',
        allowedConnections: [
            'project-in',
            'python-in',
            'table-out',
            'file-extractor-in',
            'end-in',
            'subgraph-in',
            'audio-to-text-in',
            'table-in',
            'task-in',
            'agent-in',
            'knowledge-retriever-in',
            'key-value-in',
        ],
        position: 'right',
        color: '#00bfa5',
    },
];
